### 설문조사 자료 전처리
    
    최초 작성일 : 20/03/23
    작성자 : 조예슬
    
    <작성내용>
        
        - hueFixed_harmony + class + cnt 전처리 추가  
        
        - sex + hueFixed_harmony_class + cnt 전처리 추가
        
        - age + hueFixed_harmony_class + cnt 전처리 추가

        - interest + hueFixed_harmony_class + cnt 전처리 추가

        - Definition + Need + hueFixed_harmony 전처리 추가

        - Age + Sex + hueFixed_harmony 전처리 추가
            
        
    < 출처 >
    은주언니 햣!!▼
    https://github.com/slmteruto/CAI/blob/master/jay/Statistical%20hypothesis%20testing/Survey_preprocessing.ipynb

In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.font_manager as fm
font_name = fm.FontProperties(fname='C:\Windows/Fonts/malgun.ttf').get_name()
plt.rc('font', family=font_name)
mpl.rcParams["axes.unicode_minus"] = False

import pymysql, math, time
from sklearn import preprocessing
import urllib

from IPython.display import Image

### hueFixed_harmony + class + cnt

In [3]:
## 밝은색 설문 결과 불러오기
hueFixed_bright = pd.read_excel("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/퍼스널컬러 정량화 모델 가설검정을 위한 설문 (2).xlsx",
                          sheet_name = 'Sheet1', header=0,na_values = 'NaN',
                          usecols="M, N, O, P, Q, R")

hueFixed_bright.rename(columns={hueFixed_bright.columns[0]:"comp",
                                hueFixed_bright.columns[1]:"triangle1",
                                hueFixed_bright.columns[2]:"triangle2",
                                hueFixed_bright.columns[3]:"doubleness1",
                                hueFixed_bright.columns[4]:"doubleness2",
                                hueFixed_bright.columns[5]:"doubleness3"}, inplace=True)

columns = ["comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]

## 선택항목 별 부위 매칭 (①-채도(-5)/명도(-5), ②-채도(-5)/명도(+5), ③-original, ④-채도(+5)/명도(+5), ⑤-채도(+5)/명도(-5))
for i in range(int(hueFixed_bright.shape[0])):
    for col in columns:
        if hueFixed_bright[col][i] == "①":
            hueFixed_bright[col][i] = "-S-V"
        elif hueFixed_bright[col][i] == "②":
            hueFixed_bright[col][i] = "-S+V"
        elif hueFixed_bright[col][i] == "③":
            hueFixed_bright[col][i] = "original"
        elif hueFixed_bright[col][i] == "④":
            hueFixed_bright[col][i] = "+S+V"
        else:
            hueFixed_bright[col][i] = "+S-V"

            
## 하나씩 원하는 df형태로 만들기 
# comp 
c_hFixed  = pd.DataFrame(hueFixed_bright["comp"])
c_hFixed["class"] = "comp"
c_hFixed.rename(columns={"comp":"select"}, inplace=True)

# triangle1
t1_hFixed  = pd.DataFrame(hueFixed_bright["triangle1"])
t1_hFixed["class"] = "triangle1"
t1_hFixed.rename(columns={"triangle1":"select"}, inplace=True)

# triangle2
t2_hFixed  = pd.DataFrame(hueFixed_bright["triangle2"])
t2_hFixed["class"] = "triangle2"
t2_hFixed.rename(columns={"triangle2":"select"}, inplace=True)

# doubleness1
d1_hFixed  = pd.DataFrame(hueFixed_bright["doubleness1"])
d1_hFixed["class"] = "doubleness1"
d1_hFixed.rename(columns={"doubleness1":"select"}, inplace=True)

# doubleness2
d2_hFixed  = pd.DataFrame(hueFixed_bright["doubleness2"])
d2_hFixed["class"] = "doubleness2"
d2_hFixed.rename(columns={"doubleness2":"select"}, inplace=True)

# doubleness3
d3_hFixed  = pd.DataFrame(hueFixed_bright["doubleness3"])
d3_hFixed["class"] = "doubleness3"
d3_hFixed.rename(columns={"doubleness3":"select"}, inplace=True)


## 다 합치기
hFixed_harmony = pd.concat([c_hFixed, t1_hFixed, t2_hFixed, d1_hFixed, d2_hFixed, d3_hFixed])

# 개수 넣기
hFixed_harmony["cnt"] = 1

hFixed_harmony

      select        class  cnt
0       +S-V         comp    1
1       +S-V         comp    1
2       +S-V         comp    1
3       +S-V         comp    1
4       +S-V         comp    1
..       ...          ...  ...
91      -S+V  doubleness3    1
92      +S-V  doubleness3    1
93      +S+V  doubleness3    1
94  original  doubleness3    1
95      +S-V  doubleness3    1

[576 rows x 3 columns]

In [4]:
# hFixed_harmony 전처리 결과 저장
hFixed_harmony.to_csv("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/hFixed_harmony.csv")

### sex + hueFixed_harmony_class + cnt

In [6]:
## 밝은색 설문 결과 불러오기
S_hFB_cnt = pd.read_excel("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/퍼스널컬러 정량화 모델 가설검정을 위한 설문 (2).xlsx",
                          sheet_name = 'Sheet1', header=0,na_values = 'NaN',
                          usecols="C, M, N, O, P, Q, R")

S_hFB_cnt.rename(columns={S_hFB_cnt.columns[0]:"sex",
                                S_hFB_cnt.columns[1]:"comp",
                                S_hFB_cnt.columns[2]:"triangle1",
                                S_hFB_cnt.columns[3]:"triangle2",
                                S_hFB_cnt.columns[4]:"doubleness1",
                                S_hFB_cnt.columns[5]:"doubleness2",
                                S_hFB_cnt.columns[6]:"doubleness3"}, inplace=True)

columns = ["sex", "comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]


for i in range(int(S_hFB_cnt.shape[0])):
    ## sex : Male, Female 리스트 담기
    if S_hFB_cnt["sex"][i] == "남성":
        S_hFB_cnt["sex"][i] = "Male"
    else:
        S_hFB_cnt["sex"][i] = "Female"


## 선택항목 별 부위 매칭 (①-채도(-5)/명도(-5), ②-채도(-5)/명도(+5), ③-original, ④-채도(+5)/명도(+5), ⑤-채도(+5)/명도(-5))

col_list = ["comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]

for i in range(int(S_hFB_cnt.shape[0])):
    for col in col_list:
        if S_hFB_cnt[col][i] == "①":
            S_hFB_cnt[col][i] = "-S-V"
        elif S_hFB_cnt[col][i] == "②":
            S_hFB_cnt[col][i] = "-S+V"
        elif S_hFB_cnt[col][i] == "③":
            S_hFB_cnt[col][i] = "original"
        elif S_hFB_cnt[col][i] == "④":
            S_hFB_cnt[col][i] = "+S+V"
        else:
            S_hFB_cnt[col][i] = "+S-V"


## 하나씩 원하는 df형태로 만들기 
# comp 
c_hFixed  = pd.DataFrame(data = (S_hFB_cnt["sex"], S_hFB_cnt["comp"]))
c_hFixed = c_hFixed.T
c_hFixed.rename(columns={"comp":"select"}, inplace=True)

# triangle1
t1_hFixed  = pd.DataFrame(data = (S_hFB_cnt["sex"], S_hFB_cnt["triangle1"]))
t1_hFixed = t1_hFixed.T
t1_hFixed.rename(columns={"triangle1":"select"}, inplace=True)

# triangle2
t2_hFixed  = pd.DataFrame(data = (S_hFB_cnt["sex"], S_hFB_cnt["triangle2"]))
t2_hFixed = t2_hFixed.T
t2_hFixed.rename(columns={"triangle2":"select"}, inplace=True)

# doubleness1
d1_hFixed  = pd.DataFrame(data = (S_hFB_cnt["sex"], S_hFB_cnt["doubleness1"]))
d1_hFixed = d1_hFixed.T
d1_hFixed.rename(columns={"doubleness1":"select"}, inplace=True)

# doubleness2
d2_hFixed  = pd.DataFrame(data = (S_hFB_cnt["sex"], S_hFB_cnt["doubleness2"]))
d2_hFixed = d2_hFixed.T
d2_hFixed.rename(columns={"doubleness2":"select"}, inplace=True)

# doubleness3
d3_hFixed  = pd.DataFrame(data = (S_hFB_cnt["sex"], S_hFB_cnt["doubleness3"]))
d3_hFixed = d3_hFixed.T
d3_hFixed.rename(columns={"doubleness3":"select"}, inplace=True)


## 다 합치기
S_hFH_cnt2 = pd.concat([c_hFixed, t1_hFixed, t2_hFixed, d1_hFixed, d2_hFixed, d3_hFixed])

# 개수 넣기
S_hFH_cnt2["cnt"] = 1

S_hFH_cnt2

       sex    select  cnt
0   Female      +S-V    1
1     Male      +S-V    1
2   Female      +S-V    1
3     Male      +S-V    1
4   Female      +S-V    1
..     ...       ...  ...
91  Female      -S+V    1
92  Female      +S-V    1
93  Female      +S+V    1
94  Female  original    1
95  Female      +S-V    1

[576 rows x 3 columns]

In [7]:
# S_hFH_cnt2 전처리 결과 저장
S_hFH_cnt2.to_csv("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/S_hFH_cnt.csv")

### age + hueFixed_harmony_class + cnt

In [8]:
## 밝은색 설문 결과 불러오기
A_hFB_cnt = pd.read_excel("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/퍼스널컬러 정량화 모델 가설검정을 위한 설문 (2).xlsx",
                          sheet_name = 'Sheet1', header=0,na_values = 'NaN',
                          usecols="D, M, N, O, P, Q, R")

A_hFB_cnt.rename(columns={A_hFB_cnt.columns[0]:"age",
                                A_hFB_cnt.columns[1]:"comp",
                                A_hFB_cnt.columns[2]:"triangle1",
                                A_hFB_cnt.columns[3]:"triangle2",
                                A_hFB_cnt.columns[4]:"doubleness1",
                                A_hFB_cnt.columns[5]:"doubleness2",
                                A_hFB_cnt.columns[6]:"doubleness3"}, inplace=True)

columns = ["age", "comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]


## age_class : 10, 20, 30, 40, 50으로 리스트 담기
for i in range(int(A_hFB_cnt.shape[0])):
    if A_hFB_cnt["age"][i] == "10대":
        A_hFB_cnt["age"][i] = "10"
    elif A_hFB_cnt["age"][i] == "20대":
        A_hFB_cnt["age"][i] = "20"
    elif A_hFB_cnt["age"][i] == "30대":
        A_hFB_cnt["age"][i] = "30"
    elif A_hFB_cnt["age"][i] == "40대":
        A_hFB_cnt["age"][i] = "40"
    else:
        A_hFB_cnt["age"][i] = "50"        


## 선택항목 별 부위 매칭 (①-채도(-5)/명도(-5), ②-채도(-5)/명도(+5), ③-original, ④-채도(+5)/명도(+5), ⑤-채도(+5)/명도(-5))

col_list = ["comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]

for i in range(int(A_hFB_cnt.shape[0])):
    for col in col_list:
        if A_hFB_cnt[col][i] == "①":
            A_hFB_cnt[col][i] = "-S-V"
        elif A_hFB_cnt[col][i] == "②":
            A_hFB_cnt[col][i] = "-S+V"
        elif A_hFB_cnt[col][i] == "③":
            A_hFB_cnt[col][i] = "original"
        elif A_hFB_cnt[col][i] == "④":
            A_hFB_cnt[col][i] = "+S+V"
        else:
            A_hFB_cnt[col][i] = "+S-V"


## 하나씩 원하는 df형태로 만들기 
# comp 
c_hFixed  = pd.DataFrame(data = (A_hFB_cnt["age"], A_hFB_cnt["comp"]))
c_hFixed = c_hFixed.T
c_hFixed.rename(columns={"comp":"select"}, inplace=True)

# triangle1
t1_hFixed  = pd.DataFrame(data = (A_hFB_cnt["age"], A_hFB_cnt["triangle1"]))
t1_hFixed = t1_hFixed.T
t1_hFixed.rename(columns={"triangle1":"select"}, inplace=True)

# triangle2
t2_hFixed  = pd.DataFrame(data = (A_hFB_cnt["age"], A_hFB_cnt["triangle2"]))
t2_hFixed = t2_hFixed.T
t2_hFixed.rename(columns={"triangle2":"select"}, inplace=True)

# doubleness1
d1_hFixed  = pd.DataFrame(data = (A_hFB_cnt["age"], A_hFB_cnt["doubleness1"]))
d1_hFixed = d1_hFixed.T
d1_hFixed.rename(columns={"doubleness1":"select"}, inplace=True)

# doubleness2
d2_hFixed  = pd.DataFrame(data = (A_hFB_cnt["age"], A_hFB_cnt["doubleness2"]))
d2_hFixed = d2_hFixed.T
d2_hFixed.rename(columns={"doubleness2":"select"}, inplace=True)

# doubleness3
d3_hFixed  = pd.DataFrame(data = (A_hFB_cnt["age"], A_hFB_cnt["doubleness3"]))
d3_hFixed = d3_hFixed.T
d3_hFixed.rename(columns={"doubleness3":"select"}, inplace=True)


## 다 합치기
A_hFH_cnt2 = pd.concat([c_hFixed, t1_hFixed, t2_hFixed, d1_hFixed, d2_hFixed, d3_hFixed])

# 개수 넣기
A_hFH_cnt2["cnt"] = 1

A_hFH_cnt2

   age    select  cnt
0   20      +S-V    1
1   20      +S-V    1
2   20      +S-V    1
3   20      +S-V    1
4   20      +S-V    1
..  ..       ...  ...
91  50      -S+V    1
92  50      +S-V    1
93  50      +S+V    1
94  50  original    1
95  20      +S-V    1

[576 rows x 3 columns]

In [9]:
# A_hFH_cnt2 전처리 결과 저장
A_hFH_cnt2.to_csv("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/A_hFH_cnt.csv")

### interest + hueFixed_bright_class + cnt

In [10]:
## 밝은색 설문 결과 불러오기
I_hFB_cnt = pd.read_excel("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/퍼스널컬러 정량화 모델 가설검정을 위한 설문 (2).xlsx",
                          sheet_name = 'Sheet1', header=0,na_values = 'NaN',
                          usecols="H, M, N, O, P, Q, R")

I_hFB_cnt.rename(columns={I_hFB_cnt.columns[0]:"interest",
                                I_hFB_cnt.columns[1]:"comp",
                                I_hFB_cnt.columns[2]:"triangle1",
                                I_hFB_cnt.columns[3]:"triangle2",
                                I_hFB_cnt.columns[4]:"doubleness1",
                                I_hFB_cnt.columns[5]:"doubleness2",
                                I_hFB_cnt.columns[6]:"doubleness3"}, inplace=True)

columns = ["interes", "comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]  


## 선택항목 별 부위 매칭 (①-채도(-5)/명도(-5), ②-채도(-5)/명도(+5), ③-original, ④-채도(+5)/명도(+5), ⑤-채도(+5)/명도(-5))

col_list = ["comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]

for i in range(int(I_hFB_cnt.shape[0])):
    for col in col_list:
        if I_hFB_cnt[col][i] == "①":
            I_hFB_cnt[col][i] = "-S-V"
        elif I_hFB_cnt[col][i] == "②":
            I_hFB_cnt[col][i] = "-S+V"
        elif I_hFB_cnt[col][i] == "③":
            I_hFB_cnt[col][i] = "original"
        elif I_hFB_cnt[col][i] == "④":
            I_hFB_cnt[col][i] = "+S+V"
        else:
            I_hFB_cnt[col][i] = "+S-V"


## 하나씩 원하는 df형태로 만들기 
# comp 
c_hFixed  = pd.DataFrame(data = (I_hFB_cnt["interest"], I_hFB_cnt["comp"]))
c_hFixed = c_hFixed.T
c_hFixed.rename(columns={"comp":"select"}, inplace=True)

# triangle1
t1_hFixed  = pd.DataFrame(data = (I_hFB_cnt["interest"], I_hFB_cnt["triangle1"]))
t1_hFixed = t1_hFixed.T
t1_hFixed.rename(columns={"triangle1":"select"}, inplace=True)

# triangle2
t2_hFixed  = pd.DataFrame(data = (I_hFB_cnt["interest"], I_hFB_cnt["triangle2"]))
t2_hFixed = t2_hFixed.T
t2_hFixed.rename(columns={"triangle2":"select"}, inplace=True)

# doubleness1
d1_hFixed  = pd.DataFrame(data = (I_hFB_cnt["interest"], I_hFB_cnt["doubleness1"]))
d1_hFixed = d1_hFixed.T
d1_hFixed.rename(columns={"doubleness1":"select"}, inplace=True)

# doubleness2
d2_hFixed  = pd.DataFrame(data = (I_hFB_cnt["interest"], I_hFB_cnt["doubleness2"]))
d2_hFixed = d2_hFixed.T
d2_hFixed.rename(columns={"doubleness2":"select"}, inplace=True)

# doubleness3
d3_hFixed  = pd.DataFrame(data = (I_hFB_cnt["interest"], I_hFB_cnt["doubleness3"]))
d3_hFixed = d3_hFixed.T
d3_hFixed.rename(columns={"doubleness3":"select"}, inplace=True)


## 다 합치기
I_hFH_cnt2 = pd.concat([c_hFixed, t1_hFixed, t2_hFixed, d1_hFixed, d2_hFixed, d3_hFixed])

# 개수 넣기
I_hFH_cnt2["cnt"] = 1

I_hFH_cnt2

C:\ana\lib\site-packages\ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ana\lib\site-packages\ipykernel_launcher.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ana\lib\site-packages\ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ana\lib\site-packages\ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
C:\ana\lib\site-packages\ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

   interest    select  cnt
0         3      +S-V    1
1         5      +S-V    1
2         5      +S-V    1
3         3      +S-V    1
4         3      +S-V    1
..      ...       ...  ...
91        3      -S+V    1
92        5      +S-V    1
93        3      +S+V    1
94        4  original    1
95        4      +S-V    1

[576 rows x 3 columns]

In [11]:
# I_hFH_cnt2 전처리 결과 저장
I_hFH_cnt2.to_csv("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/I_hFH_cnt.csv")

### Definition + Need + hueFixed_harmony

In [12]:
# 기본항목 설문결과 (모집단 분리하지 않은 항목) 데이터 준비

## 밝은색 설문 결과 불러오기
elementaryItem = pd.read_excel("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/퍼스널컬러 정량화 모델 가설검정을 위한 설문 (2).xlsx",
                          sheet_name = 'Sheet1', header=0,na_values = 'NaN',
                          usecols="E, F, M, N, O, P, Q, R")
elementaryItem.rename(columns={elementaryItem.columns[0]:"definition",
                          elementaryItem.columns[1]:"need",
                          elementaryItem.columns[2]:"comp",
                          elementaryItem.columns[3]:"triangle1",
                          elementaryItem.columns[4]:"triangle2",
                          elementaryItem.columns[5]:"doubleness1",
                          elementaryItem.columns[6]:"doubleness2",
                          elementaryItem.columns[7]:"doubleness3"}, inplace=True)


columns = ["comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]
## 선택항목 별 부위 매칭 (①-채도(-5)/명도(-5), ②-채도(-5)/명도(+5), ③-original, ④-채도(+5)/명도(+5), ⑤-채도(+5)/명도(-5))
for i in range(int(elementaryItem.shape[0])):
    for col in columns:
        if elementaryItem[col][i] == "①":
            elementaryItem[col][i] = "-S-V"
        elif elementaryItem[col][i] == "②":
            elementaryItem[col][i] = "-S+V"
        elif elementaryItem[col][i] == "③":
            elementaryItem[col][i] = "original"
        elif elementaryItem[col][i] == "④":
            elementaryItem[col][i] = "+S+V"
        else:
            elementaryItem[col][i] = "+S-V"

            
## 값 변경 반복문
for i in range(int(elementaryItem.shape[0])):
    
    ## definition : bright, harmony로 리스트 담기
    if ("생기" in elementaryItem["definition"][i]):
        elementaryItem["definition"][i] = "bright"
    else:
        elementaryItem["definition"][i] = "harmony"
    
    ## need :  bright, harmony로 리스트 담기
    if ("생기" in elementaryItem["need"][i]):
        elementaryItem["need"][i] = "bright"
    else:
        elementaryItem["need"][i] = "harmony"
       
        
## 하나씩 원하는 df형태로 만들기 
# comp 
c_hFixed  = pd.DataFrame(data = (elementaryItem["definition"], elementaryItem["need"], elementaryItem["comp"]))
c_hFixed = c_hFixed.T
c_hFixed.rename(columns={"comp":"select"}, inplace=True)

# triangle1
t1_hFixed  = pd.DataFrame(data = (elementaryItem["definition"], elementaryItem["need"], elementaryItem["triangle1"]))
t1_hFixed = t1_hFixed.T
t1_hFixed.rename(columns={"triangle1":"select"}, inplace=True)

# triangle2
t2_hFixed  = pd.DataFrame(data = (elementaryItem["definition"], elementaryItem["need"], elementaryItem["triangle2"]))
t2_hFixed = t2_hFixed.T
t2_hFixed.rename(columns={"triangle2":"select"}, inplace=True)

# doubleness1
d1_hFixed  = pd.DataFrame(data = (elementaryItem["definition"], elementaryItem["need"], elementaryItem["doubleness1"]))
d1_hFixed = d1_hFixed.T
d1_hFixed.rename(columns={"doubleness1":"select"}, inplace=True)

# doubleness2
d2_hFixed  = pd.DataFrame(data = (elementaryItem["definition"], elementaryItem["need"], elementaryItem["doubleness2"]))
d2_hFixed = d2_hFixed.T
d2_hFixed.rename(columns={"doubleness2":"select"}, inplace=True)

# doubleness3
d3_hFixed  = pd.DataFrame(data = (elementaryItem["definition"], elementaryItem["need"], elementaryItem["doubleness3"]))
d3_hFixed = d3_hFixed.T
d3_hFixed.rename(columns={"doubleness3":"select"}, inplace=True)


## 다 합치기
DN_hFH_cnt = pd.concat([c_hFixed, t1_hFixed, t2_hFixed, d1_hFixed, d2_hFixed, d3_hFixed])

# 개수 넣기
DN_hFH_cnt["cnt"] = 1

DN_hFH_cnt

   definition     need    select  cnt
0      bright   bright      +S-V    1
1     harmony  harmony      +S-V    1
2      bright   bright      +S-V    1
3      bright  harmony      +S-V    1
4      bright   bright      +S-V    1
..        ...      ...       ...  ...
91     bright   bright      -S+V    1
92    harmony  harmony      +S-V    1
93     bright   bright      +S+V    1
94    harmony  harmony  original    1
95     bright  harmony      +S-V    1

[576 rows x 4 columns]

In [13]:
# DN_hFH_cnt 전처리 결과 저장
DN_hFH_cnt.to_csv("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/DN_hFH_cnt.csv")

### Sex + Age + hueFixed_Harmony

In [14]:
# 기본항목 설문결과 (모집단 분리하지 않은 항목) 데이터 준비

## 밝은색 설문 결과 불러오기
elementaryItem = pd.read_excel("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/퍼스널컬러 정량화 모델 가설검정을 위한 설문 (2).xlsx",
                          sheet_name = 'Sheet1', header=0,na_values = 'NaN',
                          usecols="C, D, M, N, O, P, Q, R")
elementaryItem.rename(columns={elementaryItem.columns[0]:"sex",
                          elementaryItem.columns[1]:"age_class",
                          elementaryItem.columns[2]:"comp",
                          elementaryItem.columns[3]:"triangle1",
                          elementaryItem.columns[4]:"triangle2",
                          elementaryItem.columns[5]:"doubleness1",
                          elementaryItem.columns[6]:"doubleness2",
                          elementaryItem.columns[7]:"doubleness3"}, inplace=True)


columns = ["comp", "triangle1", "triangle2", "doubleness1", "doubleness2", "doubleness3"]
## 선택항목 별 부위 매칭 (①-채도(-5)/명도(-5), ②-채도(-5)/명도(+5), ③-original, ④-채도(+5)/명도(+5), ⑤-채도(+5)/명도(-5))
for i in range(int(elementaryItem.shape[0])):
    for col in columns:
        if elementaryItem[col][i] == "①":
            elementaryItem[col][i] = "-S-V"
        elif elementaryItem[col][i] == "②":
            elementaryItem[col][i] = "-S+V"
        elif elementaryItem[col][i] == "③":
            elementaryItem[col][i] = "original"
        elif elementaryItem[col][i] == "④":
            elementaryItem[col][i] = "+S+V"
        else:
            elementaryItem[col][i] = "+S-V"

            
## 값 변경 반복문
for i in range(int(elementaryItem.shape[0])):

    ## sex : Male, Female 리스트 담기
    if elementaryItem["sex"][i] == "남성":
        elementaryItem["sex"][i] = "Male"
    else:
        elementaryItem["sex"][i] = "Female"
        
    ## age_class : 10, 20, 30, 40, 50으로 리스트 담기
    if elementaryItem["age_class"][i] == "10대":
        elementaryItem["age_class"][i] = "10"
    elif elementaryItem["age_class"][i] == "20대":
        elementaryItem["age_class"][i] = "20"
    elif elementaryItem["age_class"][i] == "30대":
        elementaryItem["age_class"][i] = "30"
    elif elementaryItem["age_class"][i] == "40대":
        elementaryItem["age_class"][i] = "40"
    else:
        elementaryItem["age_class"][i] = "50"
       
        
## 하나씩 원하는 df형태로 만들기 
# comp 
c_hFixed  = pd.DataFrame(data = (elementaryItem["sex"], elementaryItem["age_class"], elementaryItem["comp"]))
c_hFixed = c_hFixed.T
c_hFixed.rename(columns={"comp":"select"}, inplace=True)

# triangle1
t1_hFixed  = pd.DataFrame(data = (elementaryItem["sex"], elementaryItem["age_class"], elementaryItem["triangle1"]))
t1_hFixed = t1_hFixed.T
t1_hFixed.rename(columns={"triangle1":"select"}, inplace=True)

# triangle2
t2_hFixed  = pd.DataFrame(data = (elementaryItem["sex"], elementaryItem["age_class"], elementaryItem["triangle2"]))
t2_hFixed = t2_hFixed.T
t2_hFixed.rename(columns={"triangle2":"select"}, inplace=True)

# doubleness1
d1_hFixed  = pd.DataFrame(data = (elementaryItem["sex"], elementaryItem["age_class"], elementaryItem["doubleness1"]))
d1_hFixed = d1_hFixed.T
d1_hFixed.rename(columns={"doubleness1":"select"}, inplace=True)

# doubleness2
d2_hFixed  = pd.DataFrame(data = (elementaryItem["sex"], elementaryItem["age_class"], elementaryItem["doubleness2"]))
d2_hFixed = d2_hFixed.T
d2_hFixed.rename(columns={"doubleness2":"select"}, inplace=True)

# doubleness3
d3_hFixed  = pd.DataFrame(data = (elementaryItem["sex"], elementaryItem["age_class"], elementaryItem["doubleness3"]))
d3_hFixed = d3_hFixed.T
d3_hFixed.rename(columns={"doubleness3":"select"}, inplace=True)


## 다 합치기
SA_hFH_cnt = pd.concat([c_hFixed, t1_hFixed, t2_hFixed, d1_hFixed, d2_hFixed, d3_hFixed])

# 개수 넣기
SA_hFH_cnt["cnt"] = 1

SA_hFH_cnt

       sex age_class    select  cnt
0   Female        20      +S-V    1
1     Male        20      +S-V    1
2   Female        20      +S-V    1
3     Male        20      +S-V    1
4   Female        20      +S-V    1
..     ...       ...       ...  ...
91  Female        50      -S+V    1
92  Female        50      +S-V    1
93  Female        50      +S+V    1
94  Female        50  original    1
95  Female        20      +S-V    1

[576 rows x 4 columns]

In [15]:
# SA_hFH_cnt 전처리 결과 저장
SA_hFH_cnt.to_csv("C:/Users/cho ye seul/Documents/예슬/Acorn/FinalProject/Statistical Analysis/SA_hFH_cnt.csv")