    작성일 : 20/01/03
    작성자 : 양희승
    작성내용 : 브랜드 정보 크롤링

    최종 : 2020-01-04

In [12]:
#brand_info
from bs4 import BeautifulSoup
import requests
import pymysql
import re

#특수문자, 숫자 제거 정규표현식
def cleanText(readData):
 
    #텍스트에 포함되어 있는 특수 문자 제거
    p = re.compile("[^0-9]")
    numData = "".join(p.findall(readData))
    text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》]', '', numData)
 
    return text
 



def get_html(url):
    html = ""
    resp = requests.get(url)
    
    if resp.status_code == 200 :
        html = resp.text
        
    return html

#좋아요 크롤링
def crawl_musinsa_brand_info(url) :
    brand_name = []
    brand_tab = []
    tab_list = ["상품","룩북","기사","스타일","콘텐츠","후기"]    
    brand_like = []

    link = url
    
    c = get_html(url)
    soup = BeautifulSoup(c)

    
    #브랜드 이름 가져오기
    temp = []
    for brand_div in soup('div', class_="brand_logo") :
        temp.extend(brand_div.p.img['alt'].replace(")", "").split("("))
        brand_name.append(["brd_name_kor" ,temp[0]])
        brand_name.append(["brd_name_eng" ,temp[1]])
        
    dict_name = dict(brand_name)
    
    #상품 탭 내용 크롤링
    for brand_div in soup('div', class_="brand_logo_contents") :
        for brand_li in brand_div('li', class_="box-tab-btn") :
            if( 'class' in brand_li.attrs) :
                  if(cleanText(brand_li.a.get_text()) in tab_list) :     #우리가 뽑은 탭목록에 있을때만 저장
                        brand_tab.append(brand_li.a.get_text().replace(")", "").split("("))   
    
    
    dict_tab = dict(brand_tab)

    
    #좋아요 가져오기
    for brand_div in soup('div', class_="brand_logo_contents") :
        for brand_div2 in brand_div('div', class_="icon_interest") :
            brand_like.append(["like",str(brand_div2.get_text().replace("좋아요", "").strip())])
    
    dict_like = dict(brand_like)

#     print(dict_name)
#     print(dict_tab)
#     print(dict_like)    
  
     #값 테스트
#     print(dict_name["brd_name_eng"], dict_name["brd_name_kor"], 
#           dict_tab.get("상품", 0), dict_tab.get("룩북", 0), dict_tab.get("기사", 0), 
#           dict_tab.get("스타일", 0), dict_tab.get("콘텐츠", 0), dict_tab.get("후기", 0), dict_like.get("like", 0))
    
    #DB 적재
    cursor = conn.cursor()
    data = [dict_name.get("brd_name_eng", str(link.replace("https://store.musinsa.com/app/brand/goods_list/", ""))), 
            dict_name.get("brd_name_kor", "오류"), 
            dict_tab.get("상품", '0'), 
            dict_tab.get("룩북", '0'), 
            dict_tab.get("기사", '0'),
            dict_tab.get("스타일", '0'),
            dict_tab.get("콘텐츠", '0'),
            dict_tab.get("후기", '0'),
            dict_like.get("like", '0')
           ]
    
    sql = "INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) "\
         + "VALUES("\
         + "'" + dict_name["brd_name_eng"] +"'" +  ","\
         + "'" + dict_name["brd_name_kor"] +"'" +  ","\
         + "'" + dict_tab.get("상품", '0') +"'" +  ","\
         + "'" + dict_tab.get("룩북", '0') +"'" +  ","\
         + "'" + dict_tab.get("기사", '0') +"'" +  ","\
         + "'" + dict_tab.get("스타일", '0') +"'" +  ","\
         + "'" + dict_tab.get("콘텐츠", '0') +"'" +  ","\
         + "'" + dict_tab.get("후기", '0') +"'" +  ","\
         + "'" + dict_like.get("like", '0') +"'" +  ");"
    
    
#     cursor.execute(sql)    

    cursor.execute("insert into BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) values(%s, %s, %s, %s, %s, %s, %s, %s, %s)", data)
    print(sql)
    conn.commit()

In [10]:
# 상품 
# 룩북
# 기사
# 스타일
# 콘텐츠
# 후기

In [13]:
config = {"host":"192.168.0.12", "user":"musinsa", "passwd":"1111", "db":"PR_TEST"}
conn = pymysql.connect(**config)
cursor = conn.cursor()


sql = "SELECT BRD_LINK FROM BRAND_LIST"

cursor.execute(sql)


for i in cursor.fetchall() :
    url = str(i[0])
    crawl_musinsa_brand_info(url)

        


conn.close()

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AAC','더블에이씨','74','4','8','2','25','260','762');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AGNEL','아그넬','58','1','0','0','0','7','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACOTEDEMOI','아꼬떼드모이','109','0','0','0','0','31','88');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANATECH','아나텍','19','0','1','1','0','4','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANALOG MOOD','아날로그무드','34','2','1','18','1','64','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AGNESB','아네스베','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANELLO','아넬로','43','1','3','4','0','2','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANONIMO-A','아노니모아노니마','39','4','4','9','4','39','328');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOMIE COMPLEX','아노미컴플렉스','55','3','27','57','16','81','398');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOBLIR','아노블리어','78','10','31','86','61','6,277','2,205');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADAMS HEADWEAR','아담스 헤드웨어','2','0','0','0','0','7','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARDOROBE','아더로브','211','5','24','90','13','643','737');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADOY','아도이','13','0','1','0','0','15','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADNEE','아드네','29','1','1','0','0','0','179');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADIDAS','아디다스','2,224','1','1,821','2,020','308','126,705','136,539');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADIDAS SHOECARE','아디다스 슈케어','9','0','0','0','0','110','508');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADIDAS EYEWEAR','아디다스 아이웨어','161','0','2','0','0','22','447');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADIDAS WATCH','아디다스 워치','12','0','0','0','0','14','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARAREE','아라리','19','0','0','0','0','46','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARAC.9','아라크나인','70','0','1','0','1','1','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARAM','아람','250','6','6','6','155','307','444');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARENA','아레나','988','2','3','0','3','190','188');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARENA BALSSAM','아레나 발쌈','36','0','0','0','0','1','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARETE','아레테','64','0','0','0','0','85','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARGO','아르고','254','0','1','0','0','152','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARGOTH','아르고스','21','0','0','0','1','9','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARDENT VELLONA','아르덴티 벨로나','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARTTI','아르띠','61','0','0','0','0','10','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARMANI UNDERWEAR','아르마니 언더웨어','516','0','1','0','0','796','404');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARMANI EXCHANGE','아르마니 익스체인지','280','0','2','0','0','42','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARMO','아르모','132','0','0','0','2','48','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARVV','아르브','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARSCONTACT','아르스 콘택트','14','1','2','0','1','1','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARCO','아르코','251','0','6','0','3','158','486');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARTENO STUDIO','아르테노 스튜디오','92','3','10','19','33','619','544');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARISH75','아리쉬75','0','0','0','0','0','0','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMENO','아메노','30','1','1','0','0','4','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMERICAN APPAREL','아메리칸 어패럴','67','0','2','0','0','57','4,635');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMERICAN OPTICAL','아메리칸옵틱컬','0','0','0','0','0','0','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMERICANEAGLE','아메리칸이글','1,531','1','6','34','1','292','625');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMERICAN TOURISTER','아메리칸투어리스터','196','0','7','2','1','135','300');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMOEBA CULTURE','아메바컬쳐','15','1','8','0','4','101','1,152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMES-WORLDWIDE','아메스 월드와이드','241','9','30','9','40','1,126','1,363');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMELLIE','아멜리에','300','0','10','0','1','31','209');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMON MOVEMENT','아몬무브먼트','150','4','4','7','5','364','1,245');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMU KOREA','아무 코리아','190','1','5','0','1','486','1,013');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMIO SEOUL','아미오서울','6','1','2','0','1','4','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVA MOLLI','아바몰리','134','1','5','0','5','53','210');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVANZAR HERMOSO','아반자 에르모쏘','21','0','1','0','0','0','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVECATTIE','아베까띠','149','0','1','0','0','4','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVENOIR','아베느와','64','0','0','0','0','18','130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVEC','아베크','1','0','0','1','0','0','699');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABERCROMBIE & FITCH','아베크롬비','11','0','0','1','0','3','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABERCROMBIE & FITCH','아베크롬비앤피치','517','0','0','0','0','19','710');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVEC VOUS','아베크부','37','1','2','0','1','16','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVVENTURA','아벤투라','156','1','1','0','20','107','214');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABONNE','아보네','25','1','4','3','1','76','195');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABRAHAM MOON','아브라함문','44','0','0','0','0','11','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABRAHAMKHANGUL','아브라함케이한글','55','0','0','0','0','2','67');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABIRUZ','아비루즈','1,276','1','6','1','0','1,826','221');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABYSS','아비스','31','0','0','0','0','3','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARVVIN','아빈','101','0','0','18','0','96','341');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASURA','아수라','25','1','2','0','2','4','180');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASH','아쉬','74','0','0','1','0','0','109');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASTAROTH','아스타로스','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASTONIQUE GHOST','아스토닉고스트','11','0','0','0','0','12','437');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASTRAL PROJECTION','아스트랄 프로젝션','60','1','2','30','0','14','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASPARAGUS','아스파라거스','63','2','10','57','3','7','284');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASPHALT KINT','아스팔트 킨트','31','1','0','2','0','1','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASIHA','아시하','116','3','2','0','1','476','2,450');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASICS','아식스','334','0','36','143','30','4,885','1,042');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AYAYA','아야야','23','1','4','0','0','7','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AEIOU','아에이오우','22','0','1','0','0','27','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AYC','아영상사','87','2','16','63','5','1,838','1,127');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AHOH','아오','23','0','1','1','0','33','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AOEMQ','아오엠크','219','1','0','0','0','20','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AIIIGHT','아잇','33','0','0','0','0','4','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AJOBYAJO ORIGINAL LABEL','아조바이아조 오리지널 라벨','94','7','27','84','127','4,645','2,752');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AJOBYAJO FINK LABEL','아조바이아조 핑크 라벨','106','7','25','75','33','787','1,192');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACHA','아차','84','0','20','2','14','14,857','5,968');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACHO','아쵸','38','2','3','0','4','18','145');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACHIO','아치오','172','3','5','14','9','195','458');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARKADIUS','아카디우스','156','1','1','0','0','0','80');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARCHIVMENTS','아카이브먼츠','66','2','2','0','0','87','209');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACAPULCO GOLD','아카풀코 골드','50','0','0','0','0','3','190');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AKECII','아케시','109','4','1','0','2','67','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARCADE CODE','아케이드코드','39','2','1','139','8','349','195');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AQOstudiospace','아코스튜디오스페이스','56','3','7','7','74','535','840');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACOC','아코크','12','1','3','2','0','2','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARCOPEDICO','아코페디코','30','0','2','0','0','1','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARKON','아콘 거치대','101','0','0','0','0','2','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACUD','아쿠드','85','2','5','1','0','11','135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AQUWIRE','아쿠와이어','39','0','1','0','0','75','68');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACNE STUDIO','아크네 스튜디오','99','0','11','3','0','13','1,588');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AQUMARIN','아크마린','46','0','0','0','5','3','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACKERMANN','아크만','0','0','0','0','0','0','0');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACME888','아크메888','20','1','3','0','0','70','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACME DE LA VIE','아크메드라비','281','2','5','0','120','708','1,577');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARC1','아크원','33','0','2','0','1','81','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARKK COPENHAGEN','아크코펜하겐','112','0','5','6','1','12','313');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AKIA','아키아','129','3','3','25','9','1,911','760');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AKIYORU','아키요루','93','5','4','0','1','1,084','1,235');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATAR','아타르','287','9','26','33','29','4,232','2,359');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATHENADESIGNS','아테나디자인','57','1','1','0','0','12','250');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATEMPO','아템포','150','2','2','0','12','19','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATOMIC 138','아토믹 138','25','1','0','0','1','6','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ART IF ACTS','아트 이프 액츠','191','4','4','1','17','171','734');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARTLABLE','아트레이블','73','0','0','0','0','19','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATELIERPARK','아틀리에파크','33','3','12','6','5','80','879');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATEASE','아티스','48','0','0','0','0','1','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARTISTWEAR','아티스트웨어','140','6','10','154','23','774','1,112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ARTTITUDE','아티튜드','19','2','5','19','3','4','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APARTMENT','아파트먼트','995','6','43','79','0','4,029','7,106');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A.P.C.','아페쎄','223','1','16','7','2','153','4,651');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APOCOFANFARE','아포코팡파레','130','0','4','2','0','284','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APOLIS','아폴리스','26','0','0','0','0','5','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APHROSE','아프로즈','51','0','2','18','8','17','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AHAVA','아하바','9','0','2','0','0','0','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AKTEO','악테오','28','0','0','0','0','25','698');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Anna Sui','안나수이','0','0','0','0','0','0','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANNI','안니','11','0','0','2','0','7','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANDAR','안다르','671','2','39','15','9','567','953');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANSMIEL','안스미엘','31','2','4','0','2','215','157');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANGELO BIANCO','안젤로비안코','15','0','0','2','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANTONY MORATO','안토니모라토','1,051','0','4','0','1','651','547');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANTEPOST','안트포스트','46','0','0','0','1','26','117');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANTI SOCIAL SOCIAL CLUB','안티 소셜 소셜 클럽','42','0','15','0','0','1','988');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANTI HERO','안티히어로','52','0','0','0','0','4','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALDO BRUE','알도브루에','26','0','1','0','1','0','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALAINN','알라인','100','1','6','76','0','15','162');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALETA SANDAL','알레타 샌들','35','0','4','13','2','9','82');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALEXANDER McQUEEN','알렉산더 맥퀸','180','0','10','5','0','6','1,876');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALLEN EDMONDS','알렌에드몬즈','7','0','0','2','0','46','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALLEN.O','알렌오','34','0','1','0','4','1','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALORS','알로스','112','1','5','0','10','159','440');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALBA','알바','102','0','0','0','0','73','171');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Alviero Martini 1A Classe','알비에로마르티니 프리마클라쎄','408','0','0','0','0','1','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Altamont','알타몬트','425','0','4','0','0','85','457');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALT','알트','18','1','1','0','1','1','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALTRA','알트라','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALPHA INDUSTRIES','알파 인더스트리','265','4','147','182','36','8,422','10,841');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANGE ODOR','앙쥬오도르','38','0','0','0','0','1','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AEKKI','애끼','367','2','1','0','8','395','310');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANY MEMES','애니매매스','56','0','0','0','0','4','53');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANIMATE','애니메이트','101','0','1','0','0','1,146','1,013');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADDOFF','애드오프','17','0','2','0','0','4','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATWOOD ROPE','애드우드로프','13','0','0','0','0','2','234');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADHOC','애드호크','489','0','4','0','1','258','260');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASHBURY','애쉬버리','84','0','0','0','0','43','822');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASHCROFT','애쉬크로프트','124','3','19','0','2','420','362');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATHLETE','애슬리트','59','0','0','0','0','19','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AFTER PRAY','애프터프레이','36','2','1','6','2','94','171');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APPLENDIP','애플앤딥','112','2','6','22','5','112','417');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('andneeds','앤니즈','65','1','2','0','0','11','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANDERSSON BELL','앤더슨벨','131','13','208','148','419','45,889','51,221');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANDERSSON BELL for WOMEN','앤더슨벨 포 우먼','173','2','33','44','28','861','638');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANDREW & CO','앤드류앤코','182','0','0','0','0','39','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AND SEE YOU','앤드씨유','204','1','6','0','0','178','930');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AND Z','앤드지','669','3','19','0','1','1,293','550');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANDTHEOTHER','앤디아더','132','4','13','103','0','299','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANDBUTTON','앤버튼','350','0','2','0','1','523','356');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANDBLANK','앤블랭크','58','0','1','0','1','6','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANSWERING BIRD','앤서링버드','93','0','5','0','0','40','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANODDS','앤오즈','22','0','0','2','0','18','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANNSPAPER','앤즈페이퍼','70','2','4','0','2','389','137');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANKER','앤커','47','2','1','0','0','218','206');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANTLER','앤틀러','292','0','0','0','0','72','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANTLER CARRIER','앤틀러 캐리어','9','0','1','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALICEMARTHA','앨리스마샤','109','0','5','13','1','1,289','1,301');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABNORMALTHING','앱놀머씽','1,118','6','1','5','0','2,364','4,114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABCDE','앱씨디','29','1','7','47','6','109','199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APTO','앱토','37','1','5','35','0','19','125');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APTO DE LUJO','앱토드루호','23','0','0','0','0','1','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AT THE MOMENT','앳 더 모먼트','482','9','57','130','40','5,445','3,674');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AT FIRST SIGHT','앳퍼스트사이트','50','2','1','1','1','6','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANGMOO','앵무','9','0','0','0','0','1','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A COLD WALL','어 콜드 월','1','0','12','2','0','0','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A PAPER CUT','어 페이퍼 컷','184','5','5','5','4','142','292');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AUGUSTA SPORTSWEAR','어거스타 스포츠웨어','3','0','0','0','0','15','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('August Harmony','어거스트 하모니','410','0','9','1','0','3,797','1,447');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AUGUST9','어거스트나인','104','0','0','0','0','236','172');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANONYMOUS ARTISAN','어나니머스아티즌','133','1','2','0','1','243','907');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHER OFFICE','어나더 오피스','403','1','6','1','0','1,017','1,636');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHER LOUNGE','어나더라운지','57','0','0','0','0','2','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHER BRIDGE','어나더브릿지','62','2','5','0','6','353','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHER A','어나더에이','935','5','29','4','8','513','3,019');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHER ONE','어나더원','1','0','0','0','0','9','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHERYOUTH','어나더유스','369','8','30','39','7','8,556','3,310');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHER FRAME','어나더프레임','561','12','5','13','45','2,627','1,773');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOTHER PLANET','어나더플래닛','207','0','6','0','2','118','410');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A NOTHING','어낫띵','111','5','15','139','38','823','718');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANOLORCODE','어널러코드','21','1','1','1','0','133','403');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADORE','어도어','75','0','0','0','0','1','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADVISORY','어드바이저리','130','3','45','151','27','3,619','1,972');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AROUND','어라운드','18','0','27','0','0','4','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMONG','어몽','804','11','47','41','8','1,061','5,269');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AVAN','어반','89','0','2','81','1','136','416');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AWE BORN US','어본어스','53','0','1','0','0','3','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACOVER','어커버','492','10','48','129','26','117,180','36,344');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AWCO','어코','77','1','0','0','0','452','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATTENTIONROW','어텐션로우','537','9','84','319','106','22,562','12,482');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APPARELXIT','어패럴싯','506','10','45','37','39','4,818','3,624');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APPNDXX','어펜딕스','16','1','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A;UFSTAND','어퓨스탠드','21','1','3','12','0','9','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APOC','어피스오브케이크','530','7','41','110','73','6,615','8,077');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AOTT','언아웃핏','600','8','32','38','16','8,586','5,060');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANEDIT','언에디트','349','7','39','198','17','359','898');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALMOSTBLUE','얼모스트블루','64','1','1','3','14','78','303');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADD','에드','636','15','98','111','116','21,236','9,765');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADDSENSE','에드센스','1,482','1','10','17','1','262','1,372');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABBEYHORN','에비혼','11','0','0','0','0','14','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ASPIVOT','에스파이벗','81','3','2','0','2','50','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATHLINABLUE','에슬리나블루','41','0','1','2','1','2','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACIDBLACK','에시드블랙','347','3','1','2','4','2,782','1,170');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AEROGRAPHER VANE','에어로그래퍼 베인','63','0','0','0','0','35','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AIR WALK','에어워크','51','0','1','0','0','15','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AIRPUNCH','에어펀치','56','2','3','0','9','90','199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A BY A','에이 바이 에이','39','0','0','0','0','12','187');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACONTENTSLAB','에이 컨텐츠 랩','96','3','7','10','42','79','211');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AGLOWW','에이글로우','218','8','36','78','50','1,511','704');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADE','에이드','70','3','7','13','5','96','532');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ADLE','에이들','240','0','5','0','3','19,780','5,572');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A-LABEL','에이라벨','39','1','2','10','3','146','149');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMENTE','에이멘테','54','2','0','16','0','88','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A.BELL','에이벨','101','0','9','1','0','10','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ABROAD','에이비로드','230','0','0','0','0','973','761');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACEOUT','에이스아웃','100','0','0','0','0','118','525');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACR','에이씨알','22','0','0','0','0','30','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AIOU','에이아이오유','41','0','0','0','0','2','307');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AER','에이어','31','0','20','18','4','164','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AM EYEWEAR','에이엠아이웨어','28','0','0','0','0','18','755');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AZERO','에이제로','204','0','0','0','0','20','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AGENDER','에이젠더','330','7','31','191','48','1,018','865');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AGE','에이지','46','7','22','3','69','2,076','2,612');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AGED GRAY','에이지 그레이','165','7','15','125','4','5,132','1,382');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AGINGCCC','에이징씨씨씨','237','5','64','56','55','5,920','2,786');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AECA WHITE','에이카화이트','62','4','7','26','3','194','857');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A-KURTZ','에이커츠','0','0','0','0','0','0','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A.CLOWN','에이클라운','65','2','3','2','3','532','703');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A-TAILOR','에이테일러','43','0','0','0','0','1,081','366');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ATT','에이티티','74','0','15','35','5','5','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('A PURY','에이퓨리','11','1','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('APRIL77','에이프릴77','99','0','1','1','0','130','1,365');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Ain't crack','에인트크랙','346','5','11','54','4','4,768','2,986');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AB AETERNO','에테르노','67','0','0','0','0','31','213');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ACTUAL PAIN','엑추얼 페인','37','0','0','0','0','2','1,081');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANNC','엔도씨','17','0','0','0','0','14','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ANGEL SOCKS','엔젤삭스','135','0','2','0','0','5,157','572');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMBERJACK','엠버잭','48','0','2','0','0','1','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMBLER','엠블러','229','4','1','0','2','4,171','4,849');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AMBITIONEM','엠비치오넴','7','0','0','1','0','14','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AUTRE','오뚜르','131','0','3','0','0','129','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AUTOUR DU MONDE','오뜨르 뒤 몽드','274','0','4','0','0','170','199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AUBE DE J','오브드제이','27','0','2','0','0','4','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALL KANG DESIGN STUDIO','올강 디자인 스튜디오','31','1','2','0','1','1','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALTHOUGH','올도우','42','1','1','36','0','62','182');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALMOST','올모스트','100','0','1','0','0','10','396');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALLAND','올앤드','185','0','4','1','2','463','410');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALL ABOUT DENIM','올어바웃데님','75','0','6','0','0','66','147');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ALLCLASSIC','올클래식','141','0','1','0','0','13','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AAA','트리플에이','66','0','5','3','0','23,573','5,102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('AAA WOMENS','트리플에이 우먼','12','0','0','0','0','1','119');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BG BERLIN','BG 베를린','23','0','1','0','0','1','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BANASIL SHOP','바나실 샵','86','0','2','0','0','28','298');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BONNIE&BLANCHE','바니앤블랜치','80','1','0','0','22','250','696');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BODY BLUE','바디블루','39','0','0','0','0','12','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BARACCA','바라까','22','0','0','0','0','37','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BARIGATE','바리게이트','257','0','3','0','0','598','130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BARBOUR','바버','22','0','1','1','0','11','425');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BARBER 501','바버 501','5','0','1','0','0','24','139');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BASS','바스','85','0','4','5','0','429','562');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BASQUET EAST','바스켓 이스트','5','0','1','0','0','2','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BASSOHOMME','바쏘옴므','80','2','10','7','1','194','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAAL','바알','25','0','0','0','0','19','524');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAUST','바우스트','22','0','1','0','0','0','116');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BY ROEM','바이로엠','99','4','12','23','2','125','988');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BYMOSS','바이모스','37','0','0','0','0','108','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIBYSEOB','바이바이섭','469','6','19','64','13','750','1,781');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BYSTANDARD','바이스탠다드','101','5','15','45','138','1,142','384');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BICYCLETROPHY','바이시클트로피','30','1','4','31','0','280','155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BYALLMINS','바이얼민스','62','4','4','30','26','86','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BYEDIT','바이에딧','37','0','8','9','2','9','248');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BY.L','바이엘','429','3','3','1','31','368','237');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAGGU','바쿠','17','0','0','0','0','4','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOX&COX','박스앤콕스','28','4','1','7','2','225','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOXY','박시','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAAN','반','223','0','0','1','0','1,379','568');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BANTS','반츠','143','1','1','4','0','35','306');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALANSA','발란사','0','0','0','0','0','0','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALANT','발란트','564','5','11','10','29','582','982');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALENCIAGA','발렌시아가','672','0','80','66','0','11','2,063');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALLUTE','발루트','183','5','2','4','2','254','820');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALLY','발리','0','0','0','0','0','0','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALMAIN','발망','46','0','2','1','0','4','187');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALCONY','발코니','87','2','5','0','6','15','274');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOBMARLEY FOOTWEAR','밥말리 풋웨어','26','0','0','0','0','10','519');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BADBLOOD','배드블러드','0','0','0','0','0','0','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BADINBAD','배드인배드','231','6','32','6','21','965','1,964');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BADEE','배디','104','2','15','23','4','186','1,598');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BARREL','배럴','2,639','18','57','6','14','8,445','2,922');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAEMINSTORE','배민문방구','22','0','4','0','1','11','420');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAEK-YA','백야','53','1','2','7','1','42','207');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BACKYARD','백야드','66','0','0','0','0','19','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAN.DO','밴도','117','0','10','0','1','3','160');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALANCEWOOD','밸런스우드','205','9','27','90','157','509','491');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BALLOP','밸롭','647','2','4','3','2','569','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BANGERS','뱅어스','97','4','1','41','46','989','954');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BANC','뱅크','73','0','1','1','0','28','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BURNING','버닝','94','4','54','30','26','5,975','5,775');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BURBERRY','버버리','1,251','0','29','19','0','17','895');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUBILIAN','버빌리안','263','0','2','1','1','4,804','990');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUCKAROO','버커루','218','2','15','7','1','103','583');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIRKENSTOCK','버켄스탁','623','0','153','215','30','21,651','9,236');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUCKET','버켓','137','8','22','21','12','804','598');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUTTON WORKS','버튼웍스','32','0','0','0','0','6','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUTDEEP','벗딥','371','2','10','4','0','549','263');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUNKERBUSTER','벙커버스터','176','1','0','7','1','156','142');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Benetton','베네통','21','0','1','1','0','2','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEDFORD11TH','베드포드일레븐스','29','0','0','0','0','2','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BETTERTHAN88','베러댄88','27','0','0','0','4','315','198');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BETTERS','베럴즈','43','0','1','0','0','5','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BERGAL','베르갈','20','0','0','0','0','27','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BURIED ALIVE','베리드얼라이브','358','5','22','73','169','3,339','3,908');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BESTDON','베스트돈','29','0','0','0','0','3','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BABYCENTAUR','베이비센토르','519','2','17','1','3','138','943');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BABY-G','베이비지','64','0','1','0','0','2','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BASEMOMENT','베이스모먼트','278','10','15','91','10','1,177','605');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BASIC COTTON','베이직코튼','163','1','9','9','3','5,755','6,676');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAKE-SOLE','베이크솔','36','1','1','0','0','24','202');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BAPE','베이프','1,638','0','91','50','0','104','6,606');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEIPRIL','베이프릴','68','0','0','0','0','106','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Beca&Bell','베카앤벨','39','0','0','0','0','1','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEN DAVIS','벤 데이비스','961','1','33','76','5','3,341','4,872');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BENSIMON','벤시몽','158','1','16','22','7','69','245');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BENFIX','벤픽스','7','0','0','0','0','5','7');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BELLEFFA','벨레파','40','0','0','0','0','8','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BELLROY','벨로이','12','0','0','0','1','8','529');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BELIER','벨리에','220','9','37','41','34','4,001','3,017');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BELLIEF','벨리프','227','2','0','0','0','106','328');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BELLE BEAU','벨보','38','0','0','1','0','11','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BELSTAFF','벨스타프','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BETGURES','벳규어스','175','1','2','26','40','165','138');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BONIEE','보늬','124','7','0','5','2','418','357');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOSS BY HUGO BOSS','보스','85','0','0','0','0','1','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOSTANTEN','보스탄틴','72','0','0','0','0','73','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOWLLOON','보울룬','26','0','0','3','0','1','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOYLONDON WATCH','보이런던와치','540','0','0','0','0','543','881');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOTTEGA VENETA','보테가베네타','538','0','3','0','0','2','229');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOHEMIANBLUE','보헤미안블루','126','0','5','1','0','49','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BON','본','403','0','5','7','0','98','254');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BONNE CHANCE','본샹스','12','0','0','0','0','2','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BONZ','본즈','29','1','0','1','0','87','231');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BORN CHAMPS','본챔스','555','10','87','37','69','13,157','9,449');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BONEHEAD','본헤드','60','3','8','25','11','865','107');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOLLA','볼라','40','0','0','0','0','20','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOWLS','볼즈','269','4','29','176','32','1,787','704');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BONBEAU','봉보','253','0','6','4','0','13','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOODY','부디','44','1','3','0','0','9','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOOSTIC SUPPLY','부스틱서플라이','155','1','1','0','16','98','230');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOUCLIER','부클리어','61','1','0','0','3','1','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUTTERO','부테로','99','0','2','2','4','18','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BOOK ON THE PARK','북온더파크','33','1','4','16','5','273','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUND','분트','20','0','5','7','100','143','301');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BVLGARI','불가리','78','0','0','2','0','5','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BULGAKOV','불가코프','59','2','1','7','19','14','127');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRADOR','브라도르','14','0','2','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRADIPO','브라디포','20','1','5','3','0','124','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRAHMANE','브라만','171','4','23','12','42','430','809');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRAVADO','브라바도','190','3','6','41','70','3,517','3,083');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRASSBOATS','브라스보트','13','0','0','1','0','9','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROWNBREATH','브라운브레스','1,006','7','40','41','9','8,238','7,602');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROWNPEANUT','브라운피넛','128','0','1','0','0','363','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRADYBAGS','브래디백','83','1','21','4','0','347','571');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRANDED','브랜디드','77','1','38','27','11','23,658','4,564');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRUSHER','브러셔','18','0','0','0','0','54','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BREDA','브레다','133','0','4','0','0','125','161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRENSON','브렌슨','65','0','7','0','0','36,964','3,954');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROGUE AND MORROW','브로그앤머로우','61','0','3','0','0','46','93');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRONOMAD','브로노마드','3','0','1','4','0','1','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROSHPOMADE','브로쉬 포마드','5','0','0','0','0','6','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROANDTIPS','브로앤팁스','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROW END','브로우엔드','54','3','2','1','1','4','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRONSON','브론슨','0','0','0','0','0','0','16');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRUNO MAGLI','브루노말리','17','1','2','0','0','2','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRUMAN','브루먼','208','9','34','115','22','1,556','1,377');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRUTE','브루트','37','0','0','0','0','5','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROOKS','브룩스','682','1','5','1','5','61','130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BROOKLY','브룩클리','6','0','0','0','0','67','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRISCO','브리스코','168','0','0','0','0','92','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRISTON','브리스톤','50','1','3','4','16','19','266');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BREEZY EXCURSION','브리즈 익스커션','6','0','0','0','0','4','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRICK','브릭','59','2','8','22','0','243','653');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BRICKBRICK','브릭브릭','0','0','0','0','0','0','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLIND','블라인드','100','0','0','0','0','4','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLINDNESS','블라인드니스','19','0','1','0','0','2','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLAKOON','블라쿤','232','6','4','14','11','355','463');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLAK','블락','13','0','0','0','0','31','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLAK SPACE','블락 스페이스','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACX YOHANIX','블락스 요하닉스','474','2','5','0','17','198','722');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLANC de NOIRS','블랑드누아','47','0','2','0','1','71','336');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLANCBLACK','블랑블랙','143','0','0','0','0','16','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLAIM','블래임','73','3','1','0','8','116','291');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACK.NOTHING','블랙낫씽','252','0','0','0','0','33','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACKDIAMOND','블랙다이아몬드','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACK ROSES','블랙로즈','12','0','0','0','0','2','296');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACK MARTINE SITBON','블랙마틴싯봉','141','0','0','1','0','5','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACKMAMBA','블랙맘바','269','1','1','22','0','2,241','1,624');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACKMONSTER','블랙몬스터','27','0','1','0','0','110','310');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACKBLOND','블랙블론드','265','7','1','0','70','533','973');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACK SHEEP','블랙쉽','17','0','0','0','0','24','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACK SCALE','블랙스케일','1,183','0','0','0','0','156','1,114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACKADE','블랙에이드','51','2','3','24','1','35','259');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACKHIND','블랙하인드','26','2','9','47','6','29','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLACK HOODY','블랙후디','62','4','0','9','17','163','473');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLANK','블랭크','621','7','26','24','91','337','1,046');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLANK03','블랭크03','60','0','5','8','1','20','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLANK ROOM','블랭크룸','138','12','30','67','16','9,556','3,423');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLNKBLANC','블랭크블랑','120','1','11','5','2','17','211');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLANK SIDE','블랭크사이드','0','0','0','0','0','0','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUV','블러브','194','0','7','9','0','273','281');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUSHED','블러쉬드','15','0','0','0','0','2','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUFF','블러프','141','1','8','2','2','409','335');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLEH','블레','40','0','0','194','0','154','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLEDITION','블레디션','129','1','5','37','1','570','319');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLESSED BULLET','블레스드 뷸렛','368','5','12','70','53','3,012','1,558');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLESS BELL','블레스벨','3','0','0','0','0','41','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLESSCOSMETICS','블레스코스메틱','3','0','0','0','0','16','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLENDOFF','블렌도프','375','0','1','0','0','33','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLND','블렌드','121','4','10','36','18','204','227');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLOWIND','블로윈드','47','3','1','11','5','44','80');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLOND9','블론드나인','320','3','13','0','34','5,085','4,725');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUE LOUNGE MAESTRO','블루 라운지 마에스트로','632','0','1','0','0','85','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUE BAGUETTE','블루 바게트','33','0','0','0','0','26','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUE LEAF','블루리프','50','0','0','0','0','122','520');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUEVINE','블루바인','111','1','3','13','0','1','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUE ELEPHANT','블루엘리펀트','1,098','6','23','7','13','2,437','792');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUEY','블루이','103','0','3','7','0','557','920');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUE PIE','블루파이','86','6','6','94','29','179','645');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLUEPEACH','블루피치','16','0','1','0','1','43','132');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BE READY','비레디','2','0','0','0','0','11','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEMYMOOD','비마이무드','27','0','3','0','0','12','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEMIGHTY','비마이티','76','0','0','0','0','49','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEFRIENDMARKET','비마켓','104','0','0','0','0','52','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEBOF','비바프','24','3','2','13','0','9','267');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEBUMS','비범스','32','2','6','0','3','36','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BVH EYEWEAR','비브이에이치','221','0','3','0','0','449','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEBLAZE','비블레이즈','72','1','0','0','0','123','82');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BB'DESOLI'DE','비비드솔리드','126','2','10','0','1','363','189');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BBC','비비씨','234','0','9','0','0','74','928');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BBYB','비비와이비','82','4','14','133','100','115','355');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BESLOW STANDARD','비슬로우 스탠다드','572','5','41','97','21','5,573','4,096');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BESLOW ORIGINALS','비슬로우 오리지널스','197','1','7','28','4','709','1,073');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BESLOW PURPLE','비슬로우 퍼플','248','4','18','43','12','722','1,954');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIARRITZ','비아리츠','62','0','5','18','0','209','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIENSUR','비앙쉬르','3','0','0','10','2','587','375');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BSRABBIT','비에스래빗','449','5','2','4','26','630','1,259');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BSQT by Classy','비에스큐티바이클래시','156','0','53','72','22','22,735','3,855');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('B ABLE TWO','비에이블투','304','4','23','112','49','298','1,203');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIEL','비엘','53','0','0','0','0','24','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLCBRAND','비엘씨브랜드','152','0','2','3','0','2,636','675');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BLKWD','비엘케이더블유디','12','0','0','0','0','2','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BMS FRANCE','비엠에스 프랑스','110','2','18','7','10','516','685');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BYWP','비와이더블유피','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BYC','비와이씨','10','0','0','0','0','10','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEYOND CLOSET','비욘드클로젯','247','23','173','591','442','19,561','22,702');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEYOND CLOSET COLLECTION LINE','비욘드클로젯 컬렉션 라인','29','0','0','0','6','3','720');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BONESOUL','비원소울','45','0','1','0','0','158','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('B13','비원쓰리','35','0','3','0','35','92','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUBP','비유비피','47','0','0','1','9','18','118');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEING','비잉','67','0','2','0','0','138','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIZARRE JEWELRY','비자르 주얼리','49','1','1','7','3','5','231');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BJEGOB','비제곱','26','0','0','0','0','69','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BE COOL','비쿨','153','0','1','0','0','154','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BE.T.OW','비토우','66','5','6','9','8','47','67');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BETWEEN A AND B','비트윈에이앤비','225','3','8','4','7','398','531');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BT21','비티21','29','0','1','0','1','146','144');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BPACK','비팩','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('B.FRAME','비프레임','281','5','3','6','1','735','276');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BPB','비피비','570','6','64','34','71','566','4,294');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BPBCLUB','비피비클럽','69','1','13','28','15','83','420');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIGWAVE COLLECTIVE','빅웨이브 컬렉티브','53','6','3','9','1','215','574');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIG UNION','빅유니온','509','1','27','9','3','1,725','1,855');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEANPOLE LADIES','빈폴 레이디스','191','0','2','0','0','4','82');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEANPOLE MEN','빈폴 멘','1,522','0','13','0','5','264','652');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEANPOLE SPORT','빈폴 스포츠','2,234','7','62','24','28','1,175','1,038');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BEANPOLE ACCESSORY','빈폴 액세서리','1,537','0','35','19','9','865','594');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BILLABONG','빌라봉','136','0','1','0','0','16','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BILLY8','빌리에잇','25','0','0','0','0','4','91');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BUILFORD','빌포드','120','0','0','0','45','45','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('BIMBLE','빔블','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONICHIWA BONJOUR','곤니치와봉쥬르','154','0','14','8','3','1,104','1,636');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CARVEN','까르뱅','18','0','0','0','0','1','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CATTLINE','까트린','64','1','4','9','24','30','484');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COTE A COTE','꼬떼아꼬떼','47','0','1','0','0','5','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMONINOZ','꼬모니노즈','58','1','2','3','1','170','336');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLLAGEVACANCE','꼴라주바캉스','10','0','0','0','0','2','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMME DES GARCONS','꼼데가르송','52','0','38','53','0','82','5,090');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('commeD723','꼼므드723','56','0','3','7','0','0','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMPAGNO','꼼파뇨','542','18','49','13','33','45,752','19,055');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COUTURE','꾸띠르','0','0','0','0','0','0','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHLOE','끌로에','130','0','2','0','0','0','545');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CIRCUSBOYBAND','서커스보이밴드','63','0','0','0','0','44','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CELEBRATE WITH US','세레브레이트위드어스','117','2','2','0','2','530','310');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CESTI','세스띠','213','1','11','86','5','194','144');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CELECON','셀렉온','226','0','1','0','0','849','247');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CELINE','셀린느','77','0','9','1','0','0','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHERTOI SEOUL','셰르뚜아 서울','42','0','5','17','0','1','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHEZJOEY','셰조에','14','0','0','0','0','6','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHOUETTE SAPE','슈엣뜨 샤폐','190','2','8','6','5','529','544');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CILOCALA','시로카라','100','0','0','0','0','3','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CIVIL REGIME','시빌 레짐','33','0','0','0','0','1','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CYAARVO','시아보','13','0','1','0','0','4','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CIECA MASCHERA','시에카 마스케라','20','0','0','0','0','13','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CITY BREEZE','시티브리즈','577','9','22','157','62','2,316','4,280');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CITIZEN','시티즌','40','0','0','0','0','25','204');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CROUTINE','씨루틴','185','3','21','62','16','1,975','301');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CEREALAND','씨리얼랜드','4','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CCC PROJECT','씨씨씨 프로젝트','82','0','1','0','0','57','303');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CIELONDA','씨엘론다','337','0','8','0','1','2,075','328');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLSC','씨엘에스씨','328','0','0','0','0','32','165');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COME','씨오엠이','167','4','3','2','12','206','293');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COQ','씨오큐','94','3','11','29','4','756','671');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CE AND','씨이앤','68','4','6','28','14','235','254');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CP Company','씨피 컴퍼니','208','0','2','0','0','6','263');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHAV','차브','59','2','3','6','14','66','274');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHINATOWN MARKET','차이나타운마켓','74','1','16','0','9','87','856');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHACO','차코','57','0','7','1','1','778','422');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHARM'S','참스','213','6','81','110','33','5,526','14,879');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHAENEWYORK','채뉴욕','37','1','5','0','20','0','182');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHANCECHANCE','챈스챈스','238','0','32','16','2','8,393','14,319');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHAMBROS','챔브로스','51','1','1','0','0','1','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHAMPION','챔피온','1,266','0','83','154','6','89,897','72,342');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHAPS','챕스','14','0','2','0','0','64','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHAPTER EIGHT','챕터에잇','84','2','3','0','1','162','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHARI&CO','챠리앤코','63','0','18','11','2','190','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHUCK','척','603','8','36','55','55','6,755','4,898');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHUMS','첨스','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHASECULT','체이스컬트','931','2','2','27','2','861','377');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHANGE IS CHANCE','체인지이즈찬스','14','0','0','0','0','24','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHOISI','쵸이지','86','8','4','46','12','284','488');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHUBASCO','츄바스코','298','0','12','15','2','8,407','7,263');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHIQUITA','치키타','153','2','2','1','1','23','404');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHIN DOWN','친다운','57','4','30','9','13','322','579');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CARGOBROS','카고브로스','130','2','0','20','5','757','645');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CANE BROS','카네브로스','290','10','23','216','69','5,120','3,163');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAMEL WORK','카멜워크','228','17','38','36','9','10,238','3,327');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAMOUFLAGE LAB','카무플라주 랩','52','0','0','0','0','5','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAMINO STREET','카미노 스트릿','395','8','5','27','8','378','575');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CASIO','카시오','2,520','0','14','3','0','10,919','2,837');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CASIO EDIFICE','카시오 에디피스','0','0','0','0','0','0','68');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAIMAN','카이만','12','0','0','0','0','62','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CARHARTT','칼하트','1,585','2','84','192','1','57,016','69,211');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CARHARTT WIP','칼하트WIP','1,160','0','10','1','0','5,098','38,279');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CARIBEE','캐리비','16','0','0','0','0','5','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CASPERJOHNAIVER','캐스퍼존아이바','62','2','1','6','1','78','188');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CATERPILLAR WATCH','캐터필라와치','105','0','2','5','1','25','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CANDYLABTOYS','캔디랩토이즈','0','0','0','0','0','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CANDY SHOP','캔디샵','10','1','4','1','1','10','534');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CANLEAP','캔리프','299','5','22','29','7','5,742','3,119');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALIFORNIA REPUBLIC','캘리포니아 리퍼블릭','29','0','0','0','0','12','150');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALIFORNIA PROJECT','캘리포니아 프로젝트','45','1','0','0','0','22','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALVIN KLEIN','캘빈클라인','40','0','23','5','0','604','2,190');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALVINKLEIN EYEWEAR','캘빈클라인 아이웨어','15','0','0','0','0','2','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALVIN KLEIN UNDERWEAR','캘빈클라인 언더웨어','672','0','21','0','4','1,948','1,433');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALVIN KLEIN JEANS','캘빈클라인 진','1,604','0','23','15','9','404','1,149');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALVIN KLEIN PERFORMANCE','캘빈클라인 퍼포먼스','575','0','6','18','2','67','253');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CALVINKLEINJEANS FOOTWEAR','캘빈클라인진 풋웨어','27','0','5','0','1','3','160');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAMBRIDGE SATCHEL','캠브릿지사첼','0','0','0','0','0','0','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAMPERS','캠퍼스','4','0','0','1','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAMPSIDE','캠프사이드','30','1','1','0','0','16','292');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAPTAINBANANA','캡틴바나나','99','3','3','3','11','94','246');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CURRENT','커렌트','140','13','75','178','19','1,591','2,064');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMMONGARMENT','커먼가먼트','50','1','8','13','2','710','145');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMMONLABEL','커먼레이블','6','1','1','0','1','1','10');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMMONSENSE','커먼센스','8','0','3','0','1','27','182');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMMON PROJECTS','커먼프로젝트','33','0','0','0','0','6','276');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COVERNAT','커버낫','2,261','27','807','950','237','268,144','121,912');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COVERS','커버스','56','0','0','0','1','3','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CURB','커브','56','0','1','0','0','32','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CUSTOMELLOW','커스텀멜로우','788','8','29','3','4','669','2,651');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CUSTOMUS','커스텀어스','275','6','9','87','26','52','194');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COSTUME O’CLOCK','커스텀어클락','1,128','12','142','111','48','59,454','14,879');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CUSTOMADE','커스텀에이드','16','2','10','54','9','3,556','481');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONVERSE','컨버스','434','5','398','866','48','45,647','35,659');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONCEPTS1ONE','컨셉원','64','1','46','41','9','4,942','3,196');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONCEPTUAL','컨셉츄얼','155','2','5','36','11','651','233');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONSPARA','컨스파라','13','0','0','0','0','32','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COUNTRYPOWDER','컨츄리파우더','49','3','8','9','5','189','594');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLOR ROAD','컬러로드','41','0','1','0','1','3','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLORZ NEW YORK','컬러즈뉴욕','110','0','1','0','0','22','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLOR COLLA','컬러콜라','113','2','2','6','1','74','225');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLUMBIA','컬럼비아','82','1','95','61','19','2,030','1,386');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMSPACE1980','컴스페이스1980','112','2','3','3','19','33','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COMPORTA','컴포르타','65','0','1','0','0','81','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CASELOGIC','케이스로직','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAPE HEIGHTS','케이프 하이츠','7','0','1','0','0','4','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CAME UPON','케임어폰','27','1','3','8','1','2','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COGU','코구','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONAMOR','코나모르','29','0','1','7','0','8','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CORNERCOLUMN','코너칼럼','83','1','0','0','0','5','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONATT','코네트','67','3','3','0','0','133','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CODES COMBINE','코데즈컴바인','149','0','6','6','3','74','741');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CODES COMBINE INNERWEAR','코데즈컴바인 이너웨어','42','2','5','0','3','1,836','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHORRD','코드','62','4','13','6','2','86','421');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CODE OF BAD','코드 오브 배드','65','3','1','16','7','476','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CODENAME: LOOLAPALOOZA','코드네임 룰라팔루자','92','1','0','3','1','0','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CODE I'M','코드아이엠','279','5','7','31','7','454','413');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CODE.H','코드에이치','132','0','0','0','0','21','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CODEHOLIC','코드홀릭','33','0','0','0','0','3','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COROTTS','코로츠','65','0','1','0','1','788','244');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CORCA','코르카','66','3','17','1','32','274','605');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CORCO','코르코','51','0','0','0','3','91','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COVE','코브','73','3','12','28','5','318','420');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COSMOLOGY','코스몰로지','11','0','3','8','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COSRX','코스알엑스','61','0','6','0','3','96','304');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COAGMENT','코아그먼트','74','0','7','15','0','3','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONCREAT','코앤크릿','187','0','2','0','0','132','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COUCOU','코우코우','120','1','2','0','0','132','271');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COZYCOMMA','코지콤마','23','0','0','0','0','12','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COACH','코치','4,433','0','6','24','0','28','446');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COQUET STUDIO','코케트 스튜디오','334','7','12','19','48','884','846');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COQUAD','코쿼드','231','0','2','0','0','618','111');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COKIE','코키','65','7','1','4','11','83','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONDOR','콘도르','202','0','0','0','0','33','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONVOY','콘보이','182','4','17','76','11','1,472','1,279');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CORNSOX','콘삭스','31','0','1','0','0','202','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONCENT12','콘센트12','86','4','2','21','4','206','221');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONCREATE','콘크리에이트','18','2','2','0','5','24','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CONTROBANAL3','콘트로바날레','74','4','7','42','19','471','179');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COAL','콜','371','2','1','1','0','652','462');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLLABOTORY','콜라보토리','141','2','20','13','5','57','227');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLLONIL','콜로닐','51','0','0','0','0','236','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COLE HAAN','콜한','84','0','2','1','0','6','140');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COOD GEAR','쿠드기어','46','0','1','0','0','5','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COOR','쿠어','209','5','95','33','32','23,311','13,445');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COOKERY','쿠커리','29','0','1','0','0','13','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('COOTERBOY','쿠터보이','41','0','0','0','0','51','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CURETTY','큐리티','308','6','34','78','17','588','1,744');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CUBE ME','큐브미','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CUECLYP','큐클리프','394','0','3','3','0','42','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRASH BAGGAGE','크래쉬 배기지','35','2','7','2','2','34','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRAP EYEWEAR','크랩 아이웨어','0','0','0','0','0','0','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRANK','크랭크','494','7','42','50','13','2,379','6,160');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRSHR','크러셔','37','0','1','0','0','223','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRUMP','크럼프','624','18','118','300','73','53,133','19,314');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CREIMA','크레이마','34','0','1','0','0','170','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CREP PROTECT','크렙 프로텍트','6','0','0','0','0','385','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRONOUS','크로노스','157','0','0','0','0','6','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CROSS AVENUE','크로스 애비뉴','57','4','1','5','8','33','67');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CROSSCURRENT','크로스커렌트','112','1','2','4','0','243','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CROCS','크록스','407','0','11','1','0','185','640');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CROOKS & CASTLES','크룩스앤캐슬','873','0','0','0','0','46','360');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHRISBROWN','크리스브라운','84','1','1','4','1','196','196');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHRISTIAN LOUBOUTIN','크리스찬 루부탱','58','0','0','0','0','1','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHRISTIAN DIOR','크리스챤 디올','64','0','14','1','0','0','170');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHRIS CHRISTY','크리스크리스티','328','7','21','41','21','1,625','1,299');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRYSTALKEI','크리스탈케이','30','0','1','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CHRISTINE PROJECT','크리스틴 프로젝트','47','3','11','51','13','15','134');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRITIC','크리틱','1,137','19','347','417','140','40,825','28,826');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CREAMS LAB','크림스랩','115','0','0','0','0','146','116');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CRIB','크립','16','0','0','3','1','1,229','632');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CREEP STREET','크립 스트릿','11','0','0','0','0','1','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLAVADISTA','클라바디스타','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLOVIS','클라비스','1,526','14','4','17','8','641','798');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLASSICO','클라시코','91','1','13','20','3','1,413','486');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLRIDEN','클라이드앤','135','1','7','8','1','292','360');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLACO','클라코','43','0','0','50','0','43','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLATO','클라토','95','0','0','0','0','17','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLARKS','클락스','201','0','16','0','2','183','603');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLATAGE','클래티지','12','0','2','11','0','0','18');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLAXCLO','클랙스클로','17','1','1','1','1','49','193');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLUT STUDIO','클럿 스튜디오','341','8','46','108','105','903','3,536');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLEVER MOVE','클레버무브','209','0','7','0','2','106','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLAY SMITH','클레이스미스','0','0','0','0','0','0','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLET','클렛','356','2','10','15','2','169','1,146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLROTTE','클로떼','275','0','1','0','2','4','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLOMOR','클로모르','19','0','0','0','0','2','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLOVE','클로브','62','0','4','0','0','1','171');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLOI','클로이','43','0','0','0','0','366','703');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLOTHEST.','클로제스트.','0','0','0','0','0','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLOTTY','클로티','44','1','5','6','30','478','1,315');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLUSE','클루즈','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLIF','클리프','221','10','34','113','126','5,763','956');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLICCLAC','클릭클락','253','0','2','0','15','4','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('CLEAN','클린','39','0','0','0','0','14','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DADASUPREME','다다슈프림','51','0','0','0','0','76','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAVIDOFF','다비도프','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DASOM','다솜','125','0','0','0','0','1','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DASHU','다슈','69','0','5','0','2','4,566','545');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DA:EL','다엘','203','0','10','24','0','5','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAWN AND DUSK','다운앤더스크','43','2','5','0','4','10','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUBT EVERYTHING','다웃에브리띵','0','0','0','0','0','0','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DYNAFIT','다이나핏','86','1','5','0','1','18','655');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIAMOND LAYLA','다이아몬드 레이라','226','9','76','159','48','44,328','16,156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIAGONAL','다이애그널','383','8','35','41','8','351','1,186');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DYCLEZ','다이클레즈','395','1','15','1','0','19,820','2,593');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAKINE','다카인','20','0','0','0','0','10','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DARKSTAR','다크스타','98','0','0','0','0','2','61');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DR.DENIM','닥터데님','488','0','2','0','0','589','697');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DR.MARTENS','닥터마틴','495','0','290','1,000','34','27,469','22,612');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DR SKA','닥터스카','63','0','0','0','0','1','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRWONDER','닥터원더','12','0','0','0','0','1','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRG','닥터지','29','0','2','0','0','2','322');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRTIE','닥터타이','94','0','1','1','0','41','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DR.FUNNEST','닥터퍼니스트','1','1','1','0','6','2','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DANSOON','단순생활','31','0','0','0','0','37','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAAN HAUS','단하우스','31','1','1','0','8','230','287');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAL','달','27','0','0','0','0','5','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DADLIK','대드릭','50','0','0','0','0','20','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAEJOONGSO','대중소','0','0','0','0','0','0','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEXXTER','댁스터','139','4','12','235','188','1,258','514');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUBLE ADRENALINE SYNDROME','더블 아드레날린 신드롬','175','3','0','29','12','495','691');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUBLE NANG','더블낭','261','0','4','1','0','528','498');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUBLE LOVERS','더블러버스','96','1','19','0','1','96','272');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUBLE AA FITTED','더블에이에이 피티드','206','0','0','0','0','36','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUBLEU2','더블유2','179','0','0','0','0','15','137');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUBLE COMBO','더블콤보','70','0','1','0','0','181','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DUSTERS','더스터스','0','0','0','0','0','0','48');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DUSTYLAB','더스티랩','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DUCKDIVE','덕다이브','385','9','55','337','65','6,058','2,286');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DUNLOP','던롭','17','0','0','0','0','23','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DUNST','던스트','136','5','20','22','216','1,354','2,439');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DESMAMAN','데 마망','13','0','1','0','0','3','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DENNYFIELD','데니필드','60','0','1','0','0','21','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DENIMINDIGOMASTER','데님인디고마스터','83','2','5','0','0','2,051','1,199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEADEND','데드엔드','103','5','4','41','2','545','371');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DE LA LUNE','데라룬','195','0','0','0','0','3','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEMONSTRATE','데몬스트레이트','55','0','0','0','0','343','465');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEMONADE','데몬에이드','19','0','0','0','1','22','122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEMON HIDE','데몬하이드','36','0','1','0','0','27','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAMAGE MNEMONIC','데미지니모닉','168','0','0','0','0','6','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEVIWEAR','데비웨어','252','0','5','6','0','52','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DESCENTE','데상트','1,964','3','56','43','10','3,559','3,898');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEATH LENS','데스렌즈','13','0','0','0','0','28','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DER ROHE','데어로에','656','4','3','4','10','2,016','2,004');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Deus Ex Machina','데우스 엑스 마키나','10','0','2','2','0','38','273');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAYDARE','데이데어','96','2','18','46','5','208','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAYLIFE','데이라이프','140','7','2','8','0','1,081','957');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAYMELLOW','데이멜로우','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAVID STONE','데이빗스톤','139','3','5','16','1','1,404','1,527');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAYOFF','데이오프','22','0','0','2','0','322','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAZE DAYZ','데이즈데이즈','98','0','4','0','3','13','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAYTRIP','데이트립','62','0','4','60','12','1,758','381');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAILLORNY','데일로니','81','0','0','0','0','47','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DE12LOOK','데일리룩','45','0','0','2','0','328','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAILY INN','데일리인','154','6','6','0','10','306','680');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DECKY','데키','13','0','0','0','0','1','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DÉCKE','덱케','63','0','8','18','1','152','255');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DENMADE','덴메이드','31','3','3','19','0','632','199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DENHAM','덴함','99','1','9','12','4','11','204');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DELLA STELLA','델라스텔라','46','1','2','0','0','1','100');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DELILIUM','델리리움','49','2','0','0','1','68','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DELSEY','델시','57','0','1','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEBB','뎁','322','4','47','29','14','121','2,965');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DONNAKARANNEWYORK','도나카란뉴욕','138','0','0','0','0','5','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DORATORE','도라토레','189','5','14','29','2','196','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOLM','도름','120','0','2','5','16','1,660','1,024');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DORIS','도리스','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOMINANT','도미넌트','109','8','34','269','63','3,108','2,268');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOSSIER ZERO','도시에 제로','63','2','3','4','0','3','192');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOZOH','도조','346','2','7','4','22','8','239');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOPE','도프','1,145','0','1','2','0','146','1,499');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOPE BOY MAGIC','도프보이매직','6','0','0','0','0','1','100');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOFFJASON','도프제이슨','39','3','30','26','12','7,719','2,018');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUPWN','도픈','38','2','3','8','5','8','150');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DAMP','돈애스크마이플랜','284','3','6','384','15','1,108','1,659');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DONKIE','돈키','265','0','16','26','9','610','1,036');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DONTFORGETME','돈포겟미','154','8','4','0','3','255','119');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOL','돌','228','3','8','3','1','54','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOLDOL','돌돌','1,445','0','1','1','0','67','289');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOLCE & GABBANA','돌체앤가바나','37','0','3','0','0','0','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOLPHIN','돌핀','90','0','2','0','0','11','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOMBA','돔바','180','8','16','7','5','16,331','2,488');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOUCHE BAGS','두시백','30','0','0','0','0','2','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DOIN'MATHANG','두인마땡','52','5','2','5','2','59','210');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DURAN','뒤란','279','1','3','1','0','89','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEWEDEWE','듀이듀이','633','6','53','24','53','177','1,717');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEWE HEART DEWE','듀이하트듀이','247','6','25','2','18','132','885');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DUJES','듀제스','20','0','0','0','0','3','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEUTERO','듀테로','20','2','8','1','1','103','394');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DUFA','듀파','0','0','0','0','0','0','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DE MARTINI','드 마르티니','23','0','0','0','0','74','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DENAGE','드네이지','87','1','24','119','39','415','1,006');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRY STEPPERS','드라이스테퍼스','3','0','2','0','0','31','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRIFE','드라이프','350','1','1','1','0','4,397','1,178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRAGON','드래곤','138','0','0','1','0','80','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRUG WITHOUT SIDE EFFECT','드러그 위드아웃 사이드 이펙트','229','4','78','277','47','21,429','2,860');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DREPISODE','드레피소드','95','1','3','7','1','171','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRAW.M','드로우엠','10','0','0','0','0','111','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRAW FIT','드로우핏','712','8','223','38','114','103,304','32,159');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DREWDRAW','드류드로','11','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRIFTOUT','드리프트아웃','1,150','7','4','0','9','8,291','4,015');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DRILLEYS','드릴리스','73','1','3','4','22','82','99');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEMARC','드마크','46','2','0','2','0','3','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DeuMeu&','드므앤','128','0','3','0','1','24','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEVERRMAN','드베르망','10','0','0','0','0','3','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEBELL','드벨','14','0','3','0','0','0','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DZEMER','드제메르','26','0','0','0','0','41','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEFOND','드퐁','174','7','5','3','8','77','255');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DELHARMONIE','드하모니','97','0','22','10','5','1,477','2,040');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DGNAK12','디그낙12','257','8','41','31','206','2,671','3,574');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DGRE','디그레','66','1','3','20','0','51','134');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D9 RESERVE','디나인','27','0','0','0','0','3','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DENOTE','디노트','32','0','0','0','0','25','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D.LAB','디랩','134','0','4','0','0','1,900','488');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D-MAN','디맨','6','0','1','0','0','3','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DMOMENT','디모멘트','81','0','1','0','0','13','247');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIMINISHED SEVENTH CHORDS','디미니쉬드 세븐스 코즈','242','0','0','0','0','449','338');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIMITRI BLACK','디미트리블랙','315','6','9','134','8','609','1,233');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DVERGR','디베르그','15','0','1','0','0','0','188');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DVSN STUDIOS','디브이에스엔 스튜디오','56','0','2','0','29','53','164');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DISS OR THAT','디스오얼댓','4','0','0','0','0','1','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DISCOVERY EXPEDITION','디스커버리 익스페디션','1,040','5','199','24','37','16,953','15,101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DSQUARED2','디스퀘어드2','120','0','2','1','0','0','61');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DISTANCER','디스텐서','59','0','0','0','0','12','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DESXXVE','디시브','131','1','0','1','0','2,091','522');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D.XO.H','디쏘에이치','76','1','3','0','50','105','293');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DC','디씨','0','0','4','0','0','0','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DISSIZIT','디씨짓','223','0','0','0','0','3','78');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DC COMICS','디씨코믹스','88','0','0','0','0','97','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIADORA','디아도라','52','1','28','62','4','1,937','333');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIAFVINE','디아프바인','466','9','45','28','111','2,944','3,872');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Dear Dictators','디어 딕테이터스','109','0','0','0','0','124','201');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEAR GARDEN','디어가든','156','1','0','0','0','287','270');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEARYU','디어류','33','0','1','0','12','0','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEARSTALKER','디어스토커','1,033','8','37','75','7','1,675','4,691');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEAR,PEER','디어피어','63','1','11','55','5','38','434');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIEPHOD','디에봇','15','0','1','13','0','9','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DMT_PSTVM','디엠티_피에스티브이엠','333','6','10','12','2','124','315');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIOR','디올','68','0','4','3','0','0','136');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIOR HOMME','디올 옴므','31','0','14','0','0','0','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DESIGNER INVITATION','디자이너 인비테이션','52','0','23','70','7','1,394','1,574');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DESIGN UNITED','디자인 유나이티드','550','1','15','0','2','2,493','964');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Design By TSS','디자인바이티에스에스','86','0','0','0','0','20','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DESIGNSKIN','디자인스킨','880','0','1','0','0','471','201');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DESSERT','디저트','0','5','29','115','5','138','463');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIESEL','디젤','166','0','4','4','0','16','516');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIESEL UNDERWEAR','디젤 언더웨어','288','0','1','0','0','227','99');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Disney','디즈니','152','0','3','0','0','24','276');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DISNEY','디즈니','247','0','0','0','0','107','104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIZI','디지','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DGK','디지케이','58','0','1','0','0','2','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DECOLOR','디컬러','26','1','1','10','0','7','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DKNY','디케이엔와이','10','0','0','0','0','2','82');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DKTUNE','디케이툰','96','0','0','0','0','641','202');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DCUMA','디쿠마','200','1','0','10','0','681','385');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D.CRAFT','디크래프트','24','0','0','0','0','4','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D-CLIP','디클립','470','4','24','240','473','1,508','981');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DICKIES','디키즈','743','1','38','61','7','2,871','2,747');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DTRT','디티알티','21','0','3','0','3','46','116');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEPASCAL','디파스칼','96','2','3','21','41','923','644');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEPARTURE','디파쳐','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D'PARKS','디팍스','53','0','0','0','0','223','198');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIFFERENTBUTSAME','디퍼런트벗세임','39','5','5','9','13','284','319');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIFFERENTIS.OK','디퍼런트이즈.오케이','39','2','1','1','3','9','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEFAULT','디폴트','64','9','68','31','5','15,625','5,186');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D.PRIQUE','디프리크','306','5','10','34','67','1,761','1,160');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D.FLEUR','디플레르','13','0','1','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DELIDI','딜라이디','32','1','1','0','1','3','106');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DELIGHTPOOL','딜라잇풀','42','2','3','0','4','49','142');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DEALERS NY','딜러스 엔와이','0','0','0','0','0','0','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DELUX BOMBA','딜럭스 봄바','45','4','3','31','10','107','49');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('D'LUV','딜럽','31','1','0','0','1','63','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIM. E CRES','딤에크레스','102','2','13','11','8','1,648','6,577');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('DIMPLIT','딤플릿','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EINEN','아이넨','129','3','2','4','0','268','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EIDER','아이더','497','0','10','0','12','328','1,392');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EYELUCY','아이루시','45','0','0','0','0','139','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EYEYE','아이아이','643','11','60','11','72','453','6,532');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENTRE REVES','앙트레브','148','3','7','6','4','132','767');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENDYMION','앤디미온','52','0','0','0','0','34','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EARTHWELL','어스웰','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EARPEARP','어프어프','3,485','0','1','0','0','2,525','1,425');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EARL STUDIO','얼스튜디오','65','2','3','0','4','1','135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('E-IT','에-잇','50','0','0','1','0','12','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EGARDEN','에가든','181','2','0','1','1','334','124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENALLOID','에나로이드','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENOU','에노우','20','1','4','26','1','56','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EDHARDY EYEWEAR','에드하디아이웨어','21','0','0','0','0','1','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EDITION','에디션','505','3','11','1','4','202','204');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EMERSON','에머슨','164','0','0','0','0','3','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EBERLESTOCK','에버라스탁','0','0','0','0','0','0','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EVERLAST','에버라스트','9','0','0','0','0','4','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EVERWHATEVER','에버왓에버','33','0','1','4','1','17','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EVERKI','에버키','49','0','0','0','0','8','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EVANLAFORET','에번라포레','304','2','2','7','25','616','1,065');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EBICHU','에비츄','105','0','0','0','0','3','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EZRAARTHUR','에스라아서','76','0','0','0','0','24','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ESTO','에스토','210','1','1','1','1','1,018','1,694');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ESFAI','에스파이','66','2','3','0','0','46','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ESPIONAGE','에스피오나지','460','10','135','146','17','33,561','21,619');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EIEN29','에이엔29','248','2','7','19','13','29','157');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EIGHTVOLUME','에잇볼륨','670','0','0','0','0','330','343');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EZKATON','에즈카톤','244','4','1','1','0','1,999','1,168');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EKAN','에칸','68','4','7','3','1','1,379','269');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ECOROO','에코루','19','0','6','7','2','198','222');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ECRU','에크루','49','1','11','9','0','209','188');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ETRE','에터','16','1','0','0','0','7','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Etnies','에트니스','461','0','3','0','0','159','134');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Etnies Girls','에트니스 걸스','53','0','5','0','0','132','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ETRO','에트로','0','0','0','0','0','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ETRESEOUL','에트르','31','3','0','0','0','2','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ETIQA','에티카','3','0','1','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EFELD','에펠드','45','0','2','0','14','6','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EPOS','에포스','0','0','0','0','0','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EPIC','에픽','50','0','1','0','0','5','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EPICSODE','에픽소드','138','3','2','0','1','88','184');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EXCELSIOR','엑셀시오르','171','3','92','45','35','9,508','3,677');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EXYAIW','엑스와이','81','0','2','0','1','7','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EX2O2','엑스투오투','23','0','6','21','7','18','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENTHUSIA','엔더시아','20','0','3','0','3','195','39');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EN OR','엔오르','95','3','8','1','2','24','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENZO BLUES','엔조 블루스','198','8','18','10','31','1,827','1,038');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENJOI','엔조이','140','0','5','0','0','55','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELAGO','엘라고','107','0','6','0','5','6,261','354');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELLONARC','엘런아크','253','0','8','0','2','15','176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELLESSE','엘레쎄','1,092','10','68','15','13','2,370','3,219');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELOQ','엘록','133','4','0','5','0','831','593');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELLE SWIMWEAR','엘르 스윔웨어','256','1','2','0','0','9','71');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELM','엘름','167','0','0','0','0','6','120');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELYONA','엘리오나','73','3','12','39','13','6','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELLIOTI','엘리오티','153','7','67','49','204','5,058','2,921');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELIZABETH ARDEN','엘리자베스아덴','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELITE SURVIVAL SYSTEM','엘리트 서바이벌 시스템','84','0','0','0','0','1','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELEPHANT BOX','엘리펀트박스','44','2','2','3','0','0','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELEPH','엘리프','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELBATEGEV','엘바테게브','25','2','22','19','15','273','495');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ELCANTO','엘칸토','532','3','23','45','4','917','366');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EMBIZIONE','엠비지오네','63','0','1','0','0','44','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EMPTY THE CLOSET','엠티더클로젯','18','2','2','9','0','1','118');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EMPORIO ARMANI','엠포리오 아르마니','171','0','0','0','0','64','356');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Emp.T Label','엠프티레이블','43','0','0','0','0','10','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EAU CLAIR','오끌레르','26','1','2','0','0','7','129');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EUREKASHOES','유레카슈즈','51','0','2','0','1','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EGOTRIP','이고트립','53','1','5','21','6','51','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ENOUGH IS ENOUGH','이너프이즈이너프','30','1','2','0','1','5','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Emerica','이메리카','467','0','3','0','0','190','208');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EMOTION PLANET','이모션플래닛','85','2','2','14','2','138','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EBBETSFIELD','이벳필드','407','5','93','139','94','3,003','2,053');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EBBUDA BOUTIQ','이쁘다 양장점','121','1','13','44','6','89','475');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASTERNS','이스턴스','48','0','5','2','1','428','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASTLAND','이스트랜드','39','0','2','0','0','62','160');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASTINDIGO','이스트인디고','107','1','4','68','6','340','303');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASTPAK','이스트팩','294','0','28','21','7','520','1,200');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASTILO','이스틸로','7','1','2','6','0','23','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ES','이에스','70','0','0','61','0','28','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ESC STUDIO','이에스씨 스튜디오','254','0','5','28','0','934','2,126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ESN','이에스엔','129','10','85','227','10','62,548','5,454');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EMCORIGINALGARMENTS','이엠씨오리지널가먼츠','31','1','2','5','1','8','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EMM','이엠엠','14','1','2','2','1','4','118');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EYE BY EYE','이예바이이예','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EOU STUDIO','이오유스튜디오','45','2','7','0','4','28','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EOTS','이오츠','25','0','1','1','0','4','414');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EONE','이원','11','0','1','4','0','66','185');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EUM','이음','31','1','4','0','1','3','140');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASE','이즈','12','1','0','0','1','167','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASEOFF','이즈오프','50','0','0','0','1','154','127');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASYMUE','이지무이','60','2','0','0','0','92','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASYBUSY','이지비지','257','2','6','21','0','837','1,228');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EZYSTUDIO','이지스튜디오','28','0','0','0','0','472','192');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EZIO','이지오','164','1','6','5','0','959','482');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EASYPEASY','이지피지','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('EXPEDITION','익스페디션','0','0','0','0','0','0','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIFTEEN THIRTY SEVEN','1537','32','0','0','0','2','156','185');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FDM','에프디엠','45','1','2','0','3','47','141');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FBYIHM','에프바이아이에이치엠','20','0','0','0','0','6','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FCMM','에프씨엠엠','212','3','17','19','3','6,958','6,092');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('F/CE','에프씨이','47','0','16','23','2','173','296');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRJ','에프알제이','369','2','19','1','3','85','149');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUN FOLLOWS FUNCTION','에프에프에프','113','3','3','8','2','12','174');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FM91.02','에프엠9102','46','2','1','1','4','0','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FTC','에프티씨','24','0','0','0','0','12','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FTP','에프티피','12','0','5','1','0','2','122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAMULUS','파뮬러스','14','1','0','0','0','1','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAMIGO','파미고','0','0','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAV TEMPO','파브 템포','0','0','0','0','0','0','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FASCIERA','파시에라','70','0','3','8','2','138','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FFAI','파이','32','3','1','9','0','44','186');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIVE DECK','파이브데크','248','1','0','0','0','702','492');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIND KAPOOR','파인드카푸어','85','5','9','9','16','80','456');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIINNDG SCOPE','파인딩스코프','22','0','0','0','0','5','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FANTASTIC GENERATION','판타스틱 제너레이션','37','2','1','10','10','7','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FADDY','패디','1','0','0','1','0','0','120');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FABRIK','패브릭','7','0','1','1','0','0','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FABRIXLAMP','패브릭스램프','39','5','3','17','1','363','201');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FASTLE','패슬','30','0','1','1','0','175','233');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FTLW','팩토리레더웍스','25','0','0','0','0','12','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FATBELLY','팻밸리','392','5','1','0','1','175','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FANGOH','팽고','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIRSTLIGHT','퍼스트라이트','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIRSTBUCK','퍼스트벅','21','0','1','0','0','9','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIRSTFLOOR','퍼스트플로어','89','3','28','1','47','6,835','2,727');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUZZ','퍼즈','29','3','21','12','4','77','873');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUCKING AWESOME','퍼킹어썸','88','0','21','25','6','272','626');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUNDAMENTALIST','펀다멘탈리스트','43','2','2','2','2','55','214');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FERN SHOES','펀슈즈','24','1','0','3','0','60','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUNEATHER','펀에더','35','1','3','16','0','2','109');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUNFROMFUN','펀프롬펀','148','2','29','188','2','342','956');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUNKYCOCO','펑키코코','55','0','0','0','0','4','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUNKIHUSK','펑키허스크','78','1','2','0','0','6','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FENNEC','페넥','489','9','56','22','23','4,877','2,496');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FED3','페드쓰리','55','2','3','1','3','36','244');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FEMANISH','페매니쉬','279','1','2','3','0','1,498','430');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FADE6','페이드6','39','0','0','0','0','185','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAYRI','페이리','15','1','2','0','0','7','61');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAMOUS S.A.S','페이머스 에스에이에스','102','0','0','0','0','4','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAVV','페이브','79','3','7','0','15','2','43');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FACETION','페이션','97','0','3','0','0','8','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FACE FACTORY','페이스팩토리','14','0','2','0','0','5','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FEIYUE','페이유에','154','0','9','26','0','240','512');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAKERSEOUL','페이커서울','336','3','16','74','6','2,317','876');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAKEMAMA','페이크마마','103','1','6','0','0','2','193');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FAKEME','페이크미','201','3','34','1','7','115','219');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FATALISM','페이탈리즘','94','9','136','551','58','41,479','11,612');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FP142','페플','616','2','2','1','0','31,025','5,445');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FENDI','펜디','485','0','11','3','0','4','229');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FELLAS1932','펠라스1932','48','2','7','83','1','223','276');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FELTICS','펠틱스','156','0','0','0','0','1,357','1,058');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOGBOW','포그보우','43','0','1','0','0','168','103');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FORMEL CAMELE','포멜카멜레','341','1','3','0','0','49','215');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('fossa','포사','22','0','0','0','0','12','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOCEPS','포셉','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOURTHK','포스케','17','0','1','0','0','519','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOREVERYBARI','포에브리바리','75','0','0','0','0','8','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOCE','포체','447','0','2','0','0','1,545','277');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOCE LADY','포체 레이디','70','1','2','10','0','2','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FORCHASER','포체이서','52','0','0','0','0','4','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOURCOMMA','포콤마','37','0','1','7','4','10','195');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FONDERIA','폰데리아','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FOLDER LABEL','폴더 라벨','103','1','11','1','2','782','236');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUSELLA','푸셀라','2','0','0','0','2','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FULL STEAM','풀스팀','217','2','0','0','0','94','157');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FUZA','퓨자','215','3','16','0','14','42','199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FYUCHR','퓨처','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREI','프라이','73','7','56','15','91','8,077','4,908');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREIKNOCK','프라이노크','88','3','32','8','99','4,307','3,014');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREIHEIT','프라이하잇','70','4','5','1','18','63','287');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRANKENMONO','프랑켄모노','58','0','2','1','0','1,046','1,147');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRANK DOMINIC','프랭크 도미닉','154','0','0','0','1','379','291');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRANKLY','프랭클리','84','4','1','0','4','108','104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRANKY MOUSE FAMILY','프랭키 마우스 패밀리','0','0','0','0','0','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREDERICK&PANNY','프레드릭앤페니','34','1','2','0','2','60','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRED PERRY','프레드페리','94','0','4','3','0','200','1,323');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRESH I AM','프레쉬아이엠','38','0','0','0','0','8','61');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRESH ANTI YOUTH','프레시 안티 유스','336','2','9','5','5','1,064','1,271');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRAY','프레이','164','2','8','87','27','301','502');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRAME BY','프레임바이','5','0','0','0','0','14','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRAMEHUNT','프레임헌트','16','1','7','115','3','101','147');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREKA','프레카','13','0','0','0','0','6','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FROM THE YESTERDAY','프롬더예스터데이','13','2','1','0','1','10','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FROMMARK','프롬마크','147','8','5','16','18','51','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FROMB','프롬비','35','1','2','0','4','51','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FROMCHOICE','프롬초이스','67','0','14','24','0','3','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FROMHENCE','프롬헨스','59','0','0','0','0','9','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FROID','프루와','54','1','0','0','1','516','154');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRUIT OF THE LOOM','프룻오브더룸','369','5','161','107','56','19,250','6,626');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREEWILL','프리윌','20','0','0','0','0','67','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FRIZMWORKS','프리즘웍스','1,284','18','153','90','61','32,513','21,703');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREE FINGERS','프리핑거스','15','0','1','0','0','37','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREAKS','프릭스','32','3','6','2','62','2','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FREAKS AND GEEKS','프릭스 앤 긱스','33','0','0','0','0','14','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLASK','플라스크','244','4','4','0','17','401','260');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLASTTIC','플라스틱','125','2','1','23','9','58','117');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLY RUNWAY','플라이런웨이','30','1','3','0','0','7','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLYYE','플라이예','497','0','0','0','0','13','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLYING NINETY','플라잉 나인티','253','0','0','0','0','81','173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLYING COFFIN','플라잉 커핀','109','0','0','0','0','7','150');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLAGSHIP','플래그쉽','1','0','0','0','0','2','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLAT APARTMENT CIRCLE','플랫아파트먼트 써클','109','2','8','0','2','10','124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLATFITTY','플랫피티','157','0','0','0','0','158','203');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLOOD','플러드','47','3','10','38','6','171','167');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLIRT','플러트','247','1','2','20','4','593','409');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLUFFY','플러피','15','1','3','0','0','1','191');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLUXPERI','플럭스페리','148','2','4','1','6','62','100');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLASEEK','플레시크','1','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLAREUP','플레어업','115','6','21','59','15','7,833','2,873');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLAVORS','플레이버스','29','0','0','0','0','32','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLAME FLOWER','플레임 플라워','2','1','0','0','1','134','138');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLEXXION','플렉션','43','3','4','5','0','11','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLORIDA TICKET','플로리다티켓','23','1','0','0','0','0','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLOWFORD','플로우폴드','33','0','0','0','0','11','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLOT','플로트','214','0','3','0','1','135','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLOPPYBELLE','플로피벨','39','0','0','0','0','3','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLEECE MELBOURNE','플리스멜번','52','2','7','31','2','145','60');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLIAER','플리에르','58','1','10','58','1','11','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLION','플리온','82','0','0','1','0','386','529');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FLIP','플립','9','0','0','0','0','30','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIRENZE ATELIER','피렌체 아뜨리에','1,356','8','40','65','38','10,180','3,386');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIRENZE HOMME','피렌체옴므','385','0','6','12','1','397','347');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIBBER41','피버41','60','1','1','0','4','17','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FEVERTIME','피버타임','54','3','1','2','0','92','744');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FJALLRAVEN','피엘라벤','1,397','0','4','0','1','102','668');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIORE','피오레','92','0','5','23','1','98','290');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILLE','피으','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIFI LAPIN','피피라핀','490','1','4','18','0','32','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIXBINDING','픽스바인딩','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIELDMANUAL','필드매뉴얼','81','3','0','0','24','109','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FIELDWORKER','필드워커','19','1','3','0','1','23','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILOBISKNOT','필로비스놑','62','4','6','8','88','29','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILLUMINATE','필루미네이트','1,246','13','297','1,525','454','75,998','25,678');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILLIKE','필리케','80','0','0','0','1','12','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILSON','필슨','113','0','4','4','0','13','491');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FEELENUFF','필이너프','155','4','11','53','5','1,869','1,245');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILLINTHEBLANK','필인더블랭크','83','6','12','14','8','349','513');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FITFLOP','핏플랍','429','0','10','9','3','60','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FURLA','훌라','0','0','0','0','0','0','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILA','휠라','1,258','17','580','446','129','51,809','53,726');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('FILA EYEWEAR','휠라 아이웨어','0','0','0','0','0','0','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAKKA2','가까이','34','1','1','3','1','20','343');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GANEKO UNIT','가네코 유닛','143','0','0','0','3','6','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GANISONG','가니송','151','9','7','4','8','56','322');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GARO','가로','44','1','0','0','0','6','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GARNIR','가르니르','6','0','1','0','0','44','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GARCONTIMIDE','가르송티미드','68','0','1','0','0','677','1,048');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GARMENT LABLE','가먼트레이블','171','6','41','198','48','4,733','2,908');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GABRIELLEE','가브리엘리','209','3','13','17','76','54','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Gachi.','가치','114','0','12','58','1','22','68');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GACHI ON','가치온','0','0','0','0','0','0','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAKURO','가쿠로','17','1','2','4','0','4','202');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAFH','가프','62','0','0','0','0','28','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAMTANBRA','감탄브라','31','0','0','0','0','40','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOD & BLESS','갓앤블레스','8','0','0','0','0','16','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAC','객','32','0','0','0','0','5','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAP','갭','188','0','0','1','0','360','2,317');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GUNSLIP','건슬립','8','0','0','0','0','1','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Guernsey Woollens','건지 울른스','6','0','0','0','0','19','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GESTALT PROJECT','게슈탈트 프로젝트','14','0','0','0','0','22','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GUESS','게스','474','1','42','40','6','2,027','3,161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GUESS WATCH','게스 시계','110','0','4','0','16','26','285');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAZE','게이즈','16','0','0','0','0','5','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GAINSBORO','게인스보로','281','9','40','87','12','16,708','3,801');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Genzie','겐지','128','4','15','8','2','2,946','677');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GONAK','고낙','18','0','0','0','0','67','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOTHICQUE','고디크','149','0','0','0','0','40','147');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOMAWO','고마워','6','0','0','0','0','13','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOBI','고비','21','0','2','0','0','39','167');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOZER','고저','153','2','1','4','3','184','304');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOCORI','고코리','33','1','3','0','1','2','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOTT','고트','62','1','4','0','2','14','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GO TRAVEL','고트래블','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOAL','골','160','4','18','10','49','225','957');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOLDEN GOOSE','골든구스','575','0','1','17','0','93','1,570');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOLDENAI','골든아이','11','0','0','0','0','3','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOLDENPET','골든펫','12','1','0','0','0','0','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOLA','골라','44','2','7','5','4','219','556');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOLA CLASSICS','골라 클래식','138','2','3','0','0','108','125');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOLF WANG','골프왕','18','0','8','3','0','0','514');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GONGBAEK','공백','22','0','3','4','1','36','252');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOOGONGFAST','구공페스트','36','1','1','0','0','1','132');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOOGIMS COMPANY','구김스 컴퍼니','756','0','0','0','0','40','118');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GURUS','구루스','10','0','0','0','0','4','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GUSITU','구시투','9','0','0','0','0','3','5');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOOSEBERRYLAY','구즈베리레이','101','0','4','1','0','274','1,078');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GUCCI','구찌','1,407','0','93','157','0','59','3,701');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GUKA','구카','95','3','15','2','29','159','2,194');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOOD NIGHT EXPRESS','굿나잇 익스프레스','10','0','0','0','0','7','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOODNIGHTDAVE','굿나잇데이브','43','1','3','0','4','9','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLW','굿라이프웍스','106','7','13','40','49','1,482','616');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOODWOOD','굿우드','61','0','0','0','0','8','137');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOODFELLAS','굿펠라즈','164','3','2','0','0','363','161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GOODHEMP','굿햄프','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GUNGHO','궁호','42','0','0','4','0','284','826');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAMICCI','그라미치','450','5','61','2','13','3,694','3,314');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRABIN','그라빈','38','0','0','0','0','99','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GROUNDWORK','그라운드워크','471','6','4','6','1','485','775');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAFEN','그라펜','39','1','2','0','4','469','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAFIK:PLASTIC','그라픽 플라스틱','145','0','0','0','0','24','243');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRANDE LINE','그란데라인','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAND BATTEMENT','그랑바트망','16','1','0','0','1','16','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAENH','그래인','23','0','1','0','1','2','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAPH PLATFORM','그래프플랫폼','55','2','5','20','2','147','326');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAFIKUS','그래피커스','380','1','4','7','1','197','403');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRANDVISION','그랜드비전','62','0','0','0','0','306','145');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAM','그램','153','4','13','3','18','1,249','978');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAIN DE BEAUTE','그랭드보떼','79','1','3','0','0','0','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GREGORY','그레고리','706','1','44','4','6','1,660','1,216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GREYGROUND','그레이그라운드','9','0','2','0','0','32','120');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAYNOISE','그레이노이즈','41','1','0','0','3','39','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAYMELIN','그레이멜린','57','0','0','0','0','652','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAVER','그레이버','470','1','5','208','18','3,724','4,797');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAVEVAULT','그레이브볼트','38','0','1','0','0','1','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAY B','그레이비','14','0','0','0','0','28','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GREY ANT','그레이안트','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GREYF','그레이프','19','0','0','0','1','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRAY HUE','그레이휴','244','9','25','137','132','476','631');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GREATOFF','그레잇오프','75','4','0','42','3','41','207');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GROSSINVENTORY','그로스인벤토리','264','0','0','0','0','650','412');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GROOVE RHYME','그루브라임','257','14','85','17','27','52,261','19,310');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRUNLAND','그룬란드','10','0','2','0','0','1','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRISH','그리쉬','130','4','24','16','16','1,835','2,023');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GREEN STUFF','그린스터프','225','0','1','0','0','460','225');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GRIMSTAD','그림스타드','15','0','0','0','0','1','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLASSHAUS','글라스하우스','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLAMGM','글램지','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLORY_ARDEN','글로리아덴','921','0','5','1','1','18,183','1,521');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLOVERALL','글로버올','27','1','3','0','3','14','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLOBE','글로브','527','0','4','1','0','453','187');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLOSTERN','글로스턴','38','0','0','0','0','102','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLOTHESSTUDIO','글로즈스튜디오','71','6','3','0','4','742','715');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLO-TOOB','글로투브','11','0','0','0','0','1','9');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLUCK','글륵','266','0','0','0','0','164','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GLYPH','글리프','87','0','0','0','0','167','202');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GIGL','기글','13','0','0','0','0','2','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GEAR3','기어쓰리','47','0','2','0','2','643','395');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GEEKERS','기커스','145','0','2','0','0','139','103');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GEEKY','기키','388','0','4','0','16','2,882','1,512');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GIFTORIGINAL','기프트오리지널','89','16','50','101','61','12,595','3,232');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GEEKTAEYEWEAR','긱타아이웨어','40','0','1','2','0','4','176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GILDAN','길단','29','0','2','0','0','2,206','666');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GILI BAGS','길리','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GIMMETHEYOUNG','김미더영','36','1','5','13','1','6','182');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GENS DE VIEN','쟝 드 뷔엥','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GENERALIDEA STANDARD','제너럴아이디어 스탠다드','775','6','26','4','34','869','1,104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GENERAL FINALE','제네럴 피날레','39','0','0','0','0','26','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GENUIO','제누이오','41','0','1','0','0','2','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GEOX','제옥스','93','11','2','7','3','1,230','265');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GENTLEMEN'S CONCEPT','젠틀맨스 컨셉','970','0','5','10','0','525','322');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GENTLEMENS HARDWARE','젠틀맨즈하드웨어','27','0','0','0','0','2','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GENTLE MAYHEM','젠틀메이햄','33','0','0','0','0','4','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GELATOFACTORY','젤라또팩토리','11','0','7','0','7','13','180');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GEORGESBAND','조지스밴드','0','0','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GIUSSANI TESSUTI','쥬싸니테수티','16','0','1','5','0','2','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GIVENCHY','지방시','297','0','14','1','0','3','1,651');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('G-SHOCK','지샥','826','0','37','3','0','350','2,089');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GIANNI LUPO','지아니루포','470','4','0','0','7','48','122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GISELLINA','지젤리나','66','0','1','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('G-FLAT','지플랫','632','5','5','2','5','4,768','1,034');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GINGER EYEWEAR','진저아이웨어','7','1','1','0','0','5','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('GYM MASTER','짐마스터','105','0','3','2','0','7','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HERNO','에르노','0','0','0','0','0','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HERISSON','에리쏜','47','0','0','0','0','5','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEICH BLADE','에이치 블레이드','544','11','56','27','84','2,775','3,462');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HDCR','에이치디씨알','962','0','0','0','0','202','255');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HDS','에이치디에스','35','2','3','0','1','7','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HVPE','에이치브이피이','25','0','0','0','0','271','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HSD','에이치에스디','63','1','1','0','0','11','148');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HCONNECT','에이치커넥트','133','2','8','27','33','160','352');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOCHDIENEN','오흐디넌','36','1','6','36','3','297','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOMFEM','옴펨','262','4','10','17','10','339','638');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIERETDEMAIN','이에엣드맹','32','0','3','4','2','3','100');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAHARCHIVE','하 아카이브','37','5','6','4','8','374','478');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAGAHI','하가히','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HARDBOILED COMICS','하드보일드 코믹스','113','0','2','0','0','744','506');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HARDING-LANE','하딩레인','68','0','5','0','1','150','378');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HARUTA','하루타','47','2','21','0','8','2,528','1,392');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAVAIANAS','하바이아나스','232','0','12','1','0','728','203');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HARBOUR HOLIDAY','하버할리데이','27','0','0','0','0','4','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAWHA','하와','37','0','0','11','4','44','84');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOWTHERE','하우데어','75','0','2','0','0','186','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOUSE OF 1817','하우스 오브 일팔일칠','7','0','0','0','0','1','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAUT HOMME','하우트옴므','24','0','0','0','0','109','173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOUND VILLE','하운드빌','194','1','0','0','3','878','644');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOWL','하울','41','0','0','0','0','14','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOWLPOT','하울팟','46','0','0','0','0','60','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIDE','하이드','44','1','0','0','8','6','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HYDE AND WOLF','하이드 앤 울프','12','0','1','0','0','4','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIGHRESOLUTION','하이레졸루션','37','0','1','3','0','13','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HYBERNAT','하이버넷','120','4','14','62','50','211','787');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HYBITION','하이비션','219','2','5','1','11','510','351');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIGH SCHOOL DISCO','하이스쿨디스코','60','3','15','37','13','438','2,183');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIGH SIERRA','하이시에라','131','0','5','9','1','25','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIGH CHEEKS','하이칙스','85','2','42','21','16','439','1,944');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIFIFNK','하이파이펑크','0','0','0','0','0','0','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HYPER DENIM','하이퍼 데님','151','0','0','0','0','154','127');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIGH PLANET','하이플래닛','58','1','0','0','0','279','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAKKABLACKS','하카블랙스','38','0','0','0','0','1','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HACKESCH','하케쉬','239','8','29','12','16','1,134','5,198');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEART CLUB','하트클럽','78','2','0','0','20','26','481');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HALBKREIS','하프크라이즈','750','9','113','152','40','55,282','13,995');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HANRYANG','한량','68','0','1','0','0','19','60');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HANSSEM','한샘','5','0','2','0','1','4','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HANYUL','한율','26','0','0','0','0','4','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HARLIEK','할리케이','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOTDEW','핫듀','32','1','0','0','0','44','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEADWRAPS','해드랩스','27','0','2','0','0','4','153');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAMILTON','해밀턴','134','0','0','0','0','1','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HABERDASHERY','해버대셔리','47','3','17','37','13','399','267');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAVE A GOOD TIME','해브 어 굿 타임','847','3','93','52','8','7,359','10,568');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAVE LESS','해브레스','85','1','1','1','1','4','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAVISM','해비즘','228','3','10','45','3','719','1,062');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAVIT','해비트','68','0','0','0','0','63','141');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAZARD4','해자드4','216','0','0','0','0','14','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAZ','해즈','50','2','2','0','4','234','240');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HATSTORY','해츠토리','68','3','7','17','2','16','119');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HACKISH','해키쉬','102','3','3','16','0','115','173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAPPENING','해프닝','58','2','7','15','1','8','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HAPPEN IN HEAVEN','해픈인헤븐','17','0','2','0','0','186','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HANCE','핸스','265','2','3','11','6','8,649','870');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HONEY BRAIN','허니브레인','30','0','2','1','0','2,599','452');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HONEYKINNY','허니키니','61','0','3','0','0','2','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HONEY FLAMINGO','허니플라밍고','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HERSCHEL','허쉘','642','0','9','16','0','752','674');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HUTS&BAY','허츠앤베이','240','0','1','0','0','43','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HUF','허프','1,152','0','3','4','0','584','4,558');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HURLEY','헐리','14','0','0','0','0','6','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HUMMEL','험멜','104','0','7','1','1','110','131');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HENNES VAROR','헤네스바롤','22','0','1','3','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEAD','헤드','484','11','153','61','30','6,590','2,521');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HERCULES UNDERWEAR','헤라클레스 언더웨어','109','0','0','0','0','255','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HERON PRESTON','헤론 프레스톤','6','0','2','0','0','3','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HERRINGBONE','헤링본','12','1','1','3','1','27','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEAVENSENSE','헤븐센스','36','0','0','0','0','35','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEVITZ','헤비츠','129','0','3','0','0','314','308');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEAVY CULTURE','헤비컬쳐','73','2','6','151','10','77','155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HASHTAG 9','헤시테그 나인','46','0','1','0','0','14','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEYDUDE','헤이두드','15','1','2','0','0','1','116');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEYMISSTATA','헤이미스타타','24','0','1','0','0','6','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEIMIN','헤이민','28','0','1','0','1','47','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEYS','헤이즈','137','0','1','0','0','12','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HATER','헤이터','543','3','1','1','22','1,846','791');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEIMDALLR','헤임달','71','0','0','0','0','8','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEXED','헥시드','66','2','1','32','9','23','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HANDER','헨더','65','1','7','0','0','334','712');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HENRY COTTON'S','헨리코튼','82','0','1','9','9','184','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HELLDORADO','헬도라도','85','0','1','0','0','24','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HELLOBOY','헬로우보이','2','0','0','0','0','12','78');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HELINOX','헬리녹스','75','1','33','1','2','161','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HELLVN','헬븐','549','3','2','27','0','762','802');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HELLS BELLS','헬즈벨즈','11','0','0','0','0','54','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HLZBLZ','헬즈벨즈','6','0','0','0','0','15','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEM','헴','13','0','0','0','0','45','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOMMMIE','호미','24','0','0','0','0','89','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOVER','호버','20','0','0','1','0','37','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOBOKEN','호보켄','118','0','3','0','0','498','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOSHIHIME','호시히메','53','0','0','0','0','9','359');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOXTON','혹스턴','43','1','1','0','1','4','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOLLY LOVES LOVE','홀리 러브스 러브','69','1','3','12','0','19','229');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOLYNUMBER7','홀리넘버세븐','198','5','25','84','173','231','477');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOLIDAY OUTERWEAR','홀리데이 아우터웨어','53','0','0','0','0','67','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HORLISUN','홀리선','225','4','1','0','5','290','664');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOLLYSATUNS','홀리세턴즈','15','0','0','0','0','3','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOLZPUPPE','홀즈퓨페','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HOMBOIGOING','홈보이고잉','30','1','3','18','3','12','209');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HONGSHOT','홍샷','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HYOJI NORIKO','효지노리코','586','2','10','10','1','2,608','1,912');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HUGO BOSS UNDERWEAR','휴고보스 언더웨어','26','0','0','0','0','157','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HUSTAD','휴스타드','41','0','1','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HMM','흠디자인','106','0','0','0','0','1,206','155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEEGUI','희귀','67','0','0','0','0','43','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEEDIMENSIONAL','희다이멘셔널','20','0','2','11','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEENN','흰','95','0','13','21','0','3','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEROINE','히로인','63','1','5','4','9','2','68');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HSTRY','히스토리바이나스','24','0','0','0','0','1','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIPPYTREE','히피트리','114','0','1','0','0','5','36');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HIGGX','힉스','123','0','2','0','0','31','104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEAL','힐','69','2','0','0','2','42','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('HEELYS','힐리스','63','0','1','0','0','7','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IGLOVES','아이글로브스','47','1','0','0','0','397','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IDEAEND','아이디어엔드','27','1','2','2','0','11','183');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IDEAL FOR MEN','아이디얼 포맨','6','0','2','0','0','7','71');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IDEALITIC','아이딜리틱','20','0','1','0','7','87','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IRONY PORN','아이러니 포르노','188','3','3','19','3','213','428');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('I LOVE UGLY','아이러브어글리','63','0','0','0','0','6','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IMASQ','아이마스큐','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IMEI','아이미아이','40','0','3','4','2','0','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('I4P','아이사피','56','2','8','15','1','295','3,741');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ISOFLX','아이소플럭스','8','0','0','0','0','4','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IRON ROMEO','아이언로미오','22','0','1','0','0','3','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IX NINE','아이엑스 나인','40','0','1','0','0','8','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IOTTIE','아이오티','17','0','0','0','0','10','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IOPE','아이오페','37','0','0','0','0','3','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IZOLA','아이졸라','265','5','14','1','0','132','279');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ICONOGRAPHY','아이코노그라피','126','3','1','5','3','156','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ITOV','아이토브','32','0','1','0','0','2','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('I HATE MONDAY','아이헤이트먼데이','772','4','44','53','16','631','1,450');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ISLANDSLIPPER','아일랜드슬리퍼','6','0','0','1','0','8','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('I AM NOT A HUMAN BEING','아임낫어휴먼비잉','1,136','13','86','96','83','11,258','17,591');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('I’M BTFL','아임뷰티풀','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INNERCITYAUDIO','이너시티오디오','83','4','16','103','32','121','437');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IINES','이네스','109','3','6','13','0','16','161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INES','이네스','114','0','2','1','0','13','141');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INNODDCENT','이노드센트','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IH NOM UH NIT','이놈어닛','0','0','0','0','0','0','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INNISFREE','이니스프리','249','0','3','0','1','144','120');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IROAS','이루아즈','0','0','0','0','0','0','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IRIS','이리스','119','0','1','0','0','19','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ISSEY MIYAKE','이세이 미야케','67','0','1','0','0','0','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ISSUE NUMBER','이슈넘버','128','2','4','4','0','42','175');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IXVI','이스비','74','3','2','0','8','101','295');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IST KUNST','이스트쿤스트','290','10','83','186','37','14,601','4,290');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ISABEL MARANT','이자벨마랑','68','0','1','0','0','1','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IZRO','이즈로','129','4','5','23','33','1,100','1,036');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ISBIM','이즈빔','57','1','3','3','1','8','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ICHINY','이치니','21','0','1','0','0','64','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ICIMI','이치미','62','5','16','18','20','1,205','1,029');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IPANEMA','이파네마','19','1','1','0','0','4','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INTHESTAR','인더스타','43','0','16','71','1','2','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INTHEPEOPLE','인더피플','31','2','3','2','4','104','211');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INDEP','인뎁','21','0','1','0','0','0','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INDIGO CHILDREN','인디고칠드런','168','4','2','0','89','557','991');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INDIESLOW','인디슬로우','4','1','1','0','0','0','43');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INDEPENDENT','인디펜던트','60','0','1','0','0','24','99');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INROWS','인로우스','61','4','16','86','6','1,210','477');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IN MY PARK','인마이파크','71','0','0','0','0','14','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IN SILENCE','인사일런스','391','7','271','411','115','48,197','18,102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INSANE GENE','인세인진','25','0','4','7','0','1','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INN-STANT','인스탄트','8','0','0','2','0','10','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INSTANCE','인스탠스','163','0','0','0','0','28','71');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INSTANTSUPPLYCO.','인스턴트서플라이','1','0','14','0','8','914','1,327');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INSTANTFUNK','인스턴트펑크','170','5','72','75','336','434','2,020');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INONE','인원','27','0','0','0','0','32','231');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INJIACTIVE','인지액티브','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INCASE','인케이스','290','0','3','2','0','653','1,335');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INTAR','인타','103','5','10','44','7','173','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INTERBREED','인터브리드','311','0','1','4','0','54','330');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INTERSECTION','인터섹션','23','1','2','4','2','7','204');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INTEMPOMOOD','인템포무드','42','0','1','24','0','43','282');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INFACELOOK','인페이스룩','49','0','1','0','0','0','88');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('INFLATION','인플레이션','150','0','4','1','1','305','544');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IL CORSO','일꼬르소','659','3','5','2','1','265','974');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ILLESTEVA','일레스테바','21','0','0','0','1','1','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IL-O-GONG-CHIL','일오공칠','99','6','15','0','15','41,029','2,251');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('IMPERIALMOTION','임페리얼모션','395','1','4','0','0','48','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ITSBAG','잇츠백','20','0','0','0','0','73','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ITSEAN','잇츠션','21','1','2','0','0','74','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ITSABOUTDETAIL','잇츠어바웃디테일','23','0','1','0','0','21','107');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ITER','잇터','46','2','16','89','20','583','694');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOHNNY CARSON','자니카슨','257','0','0','0','0','5,356','1,410');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JAMAIVU','자메뷰','30','1','1','4','1','12','123');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JANSPORT','잔스포츠','208','0','94','82','10','6,502','2,246');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JALDOENCASE','잘된케이스','121','0','0','0','0','4','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JALAN SRIWIJAYA','잘란 스리와야','24','0','0','0','0','3','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JAMBANGEE','잠뱅이','145','1','8','2','6','95','236');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JAM'T','잠트','183','1','7','23','10','76','193');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JEAN PAUL GAULTIER','장 폴 고티에','19','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JACKNICKLAUS','잭니클라우스','1','0','2','0','0','2','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JHONNY WEST','쟈니웨스트','659','4','28','2','7','25,147','8,632');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUSTLIKETHIS','저스트라이크디스','45','2','3','12','3','113','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUSTMYSIZE','저스트마이사이즈','34','0','0','0','0','7','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUST SATURDAY','저스트세러데이','532','8','41','210','6','3,010','1,174');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUMPFROMPAPER','점프프롬페이퍼','0','0','0','0','0','0','78');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JENNER','제너','192','0','4','1','0','4,344','176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JENNIFER LOPEZ','제니퍼로페즈','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JERRYBAG','제리백','20','0','1','0','0','11','159');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JEMUT','제멋','442','7','12','2','3','75,770','13,544');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('J.GRACELET','제이그레이슬렛','481','0','4','0','72','100','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('J.DAUL','제이다울','129','1','44','76','84','5,243','1,413');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JADE M','제이드 엠','169','1','0','0','0','113','127');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JADEGOLDNINE','제이드골드나인','30','0','2','3','1','45','41');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JRIUM','제이리움','159','1','2','0','0','3','198');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JMARKNEWYORK','제이마크뉴욕','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JAMIEWANDER','제이미원더','111','2','9','10','3','12','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JBANS CLASSIC','제이반스 클래식','2,314','3','3','0','0','4,758','1,061');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JBW','제이비더블유','42','0','0','0','0','10','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JASON MARKK','제이슨마크','8','0','0','0','0','238','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JEASHER','제이아셀','90','3','15','30','19','1,220','885');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('J&MOLLS','제이앤몰스','401','0','0','0','0','403','227');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JESTINA','제이에스티나','42','2','7','4','1','9','476');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JMY','제이엠와이','67','0','2','0','0','3','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JEONBELL','제이온벨','190','3','7','13','1','1,542','254');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('J INDUSTRY','제이인더스트리','55','2','1','0','1','3','135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('J.CHUNG','제이청','55','1','1','0','1','2','123');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JT&CO','제이티앤씨오','23','0','0','0','0','1','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JPLAY STUDIO','제이플레이','41','1','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JAIN SONG','제인송','61','0','3','0','8','15','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JAMES DEAN','제임스딘','48','0','0','0','0','163','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JENNE','젠느','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JEMKINS','젬킨스','76','0','0','0','0','1,228','325');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JONI JONI','조니조니','19','0','3','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JORENZ CARTIESS','조렌즈 까르띠스','24','2','1','0','1','0','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOSEPH&STACEY','조셉앤스테이시','386','9','88','254','191','1,927','3,216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOSLOUNGE','조스라운지','307','0','3','0','2','208','200');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOYMENT','조이먼트','54','0','0','0','16','111','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOY&MARIO','조이앤마리오','131','0','1','0','1','7','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOHNGYU','존규','11','0','0','0','0','1','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('John Varvatos','존바바토스','15','0','0','0','0','221','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOHN PETERS','존피터','167','0','2','5','44','1,151','487');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUNA FRIENDS','주나프렌즈','9','0','19','20','1','69','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JE NE SAIS QUOI','주느세콰','37','1','1','0','2','2','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUDE MCCALL','주드맥콜','190','0','11','34','4','92','486');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUROBOROS','주로보로스','53','0','1','0','0','384','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JOURDEJAJU','주르드자주','51','1','3','0','2','28','291');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUSTO','주스토','119','1','0','0','26','355','457');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUAN HOMME','주앙옴므','57','1','3','6','0','169','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUN BY JUN K','준바이준케이','174','5','9','15','11','30','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUNEHERITAGE','준헤리티지','37','0','2','1','0','8','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JULYFOUR','줄라이포','92','0','0','0','0','7','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JEDE KONNEN','쥬드코넨','82','0','16','54','2','0','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUBILER','쥬빌레','198','0','2','0','0','78','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUICY COUTURE','쥬시 꾸뛰르','126','1','5','0','1','0','165');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUCYJUDY','쥬시쥬디','85','1','2','1','0','7','199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JUANAYOON','쥬아나윤','73','0','0','0','0','2','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JULIY&CALLA','쥴리앤칼라','89','8','9','8','11','66','365');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JULIUS1','쥴리어스','192','0','1','4','0','84','62');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JIMIKO BLICO','지미코 브리코','26','0','2','0','1','1,391','272');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JEEP','지프','597','13','194','492','181','13,375','6,581');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JI HOON','지훈','51','2','5','0','3','78','116');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JINJONJAM','진존잼','10','0','10','0','1','0','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JINTUHA','진투하','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JILLSTUART','질스튜어트','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JILLSTUART SPORT NEWYORK','질스튜어트 스포츠 뉴욕','918','2','11','2','6','440','850');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('JIPSY','집시','205','1','53','4','8','32,307','11,599');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KENZO','겐조','224','0','7','6','0','4','616');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KENZO KIDS','겐조키즈','0','0','0','0','0','0','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KWONSEOK','권석','34','0','0','0','0','1','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KILUCKGI','기럭지','31','0','0','0','0','41','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KIMYUNG','기명','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KISJO','기스조','29','0','1','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KYHOLAB','기호랩','23','0','1','0','0','0','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('K-WAY','까웨','74','0','0','0','0','26','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KNOCKER'S HAND','노커즈 핸드','25','0','0','0','2','2','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KNOTTOLOGY','노톨로지','0','0','0','0','0','0','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KNITLY','니틀리','154','3','7','21','28','172','524');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KNITTED','니티드','408','13','110','177','61','33,352','9,519');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KSUBI','수비','34','0','0','0','0','8','205');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KANEI TEI','카네이테이','95','0','1','0','0','38','250');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KARAWAY','카라웨이','61','0','1','0','0','0','215');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KARIS','카리스','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAMOGRAPH','카모그라프','90','0','3','0','1','0','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAMOTO','카모토','45','0','1','2','0','1','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAVU','카부','308','0','5','2','0','66','495');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAWASHOKUNIN','카와쇼쿠닌','22','0','0','0','0','2','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KYE','카이','63','1','9','5','1','2','316');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KYISHOO','카이쇼','80','0','6','25','0','0','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KINDABABY','카인더베이비','59','0','5','0','0','49','163');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KIINDLOUNGE','카인드라운지','130','1','13','13','4','62','281');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAILUABAY','카일루아베이','106','0','0','0','0','295','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAKAO FRIENDS','카카오프렌즈','89','0','5','0','0','46','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KATHARSIS','카타르시스','76','1','2','0','0','10','157');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KATIACHO','카티아조','52','1','2','0','0','9','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAPPA','카파','884','0','188','220','43','7,984','9,209');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KAN6312','칸6312','307','3','1','3','3','71','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KANKEN','칸켄','200','0','0','0','0','5','130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KANCO','칸코','303','3','40','32','13','7,049','4,114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KARL LAGERFELD EYEWEAR','칼 라거펠트 아이웨어','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KARL LARGERFELD','칼라거펠트','0','0','0','0','0','0','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KANGOL','캉골','882','6','52','39','17','17,002','21,590');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KANGOL SUNGLASS','캉골 선글라스','0','0','0','0','0','19','135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KANGOL WATCH','캉골시계','155','0','1','0','0','2,796','1,360');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KENNETH YOUNG','케네스영','32','0','3','8','0','0','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KENNETH COLE','케네스콜','141','0','2','2','2','23','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KERRY WOOLLEN MILLS','케리울른밀즈','52','1','6','8','0','685','1,114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KERRIJADE','케리제이드','52','0','6','56','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEVIN SHOES','케빈슈즈','115','0','0','0','0','9','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KESSLER','케슬러','62','0','0','0','0','54','97');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KND','케이엔드','137','5','9','52','11','1,672','221');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KY'S','케이와이에스','28','0','1','0','0','41','68');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('K2','케이투','17','0','12','0','2','311','480');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KATE SPADE','케이트 스페이드','7','0','1','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KATIN','케이튼','24','1','1','0','0','1','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEIN PIONIER','케인 피오니어','16','1','1','0','1','6','99');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KONUS','코너스','668','4','9','13','48','1,306','408');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KODAK','코닥','12','0','9','3','27','109','941');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOSIDE','코시드','24','0','0','0','0','200','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOXA','코싸','90','0','2','0','0','1,190','331');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOLON SPORT','코오롱스포츠','425','1','72','5','16','688','631');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOIMOOI','코이무이','37','1','7','10','1','14','188');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOZNOK','코즈넉','45','0','1','0','0','7','60');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KONSFERO','콘스페로','108','0','0','0','0','6','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOLOK','콜록','222','0','0','0','0','335','200');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOLEAT','콜릿','76','2','13','2','28','662','493');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOLCA','콜카','113','9','30','230','61','3,750','1,076');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KOMPAKT RECORD BAR','콤팩트 레코드 바','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KWANI','콰니','52','1','4','2','4','31','153');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KRUCHI','크루치','79','0','4','0','0','50','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KROOKED','크루키드','0','0','0','0','0','0','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KLASSE14','클라쎄14','104','0','1','0','7','29','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KLEINESACHE','클라이네자케','7','0','0','0','0','10','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KLATTERMUSEN','클라터뮤젠','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KLEMAN','클레망','6','0','2','8','0','33','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KLEPTON','클렙튼','4','0','0','0','0','54','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KLEANKANTEEN','클린켄틴','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KLIPS URBAN','클립스 어반','299','0','0','0','0','511','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEYGEAR','키기어','34','0','0','0','0','62','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KIDAY','키데이','31','0','3','8','3','0','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KIRSH','키르시','663','18','358','314','45','27,926','35,685');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KIRSH POCKET','키르시 포켓','57','4','78','29','7','2,982','2,497');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEYMUN','키먼','64','3','4','24','19','61','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEEMOON','키믄','56','0','0','1','14','21','62');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KIMMY.J','키미제이','7','1','6','0','2','10','144');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEYBAK','키백','11','0','0','0','0','7','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KITSCHS','키치스','152','4','2','11','16','84','302');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KICHWORK','키치워크','137','5','5','21','3','356','742');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KITANICA','키타니카','0','0','0','0','0','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KIT','키트','27','2','4','7','1','48','196');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('keep'em','키픔','108','2','0','0','17','16','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEEN','킨','132','0','102','132','14','2,060','795');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KILLER BEE','킬러비','257','2','3','14','4','1,443','1,082');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KILIJARO','킬리자로','79','4','0','2','32','413','240');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KEEPBLACK','킵블랙','23','1','2','0','9','1','118');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('K-ING','킹','56','4','3','122','12','103','351');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KINGVERY','킹베리','24','0','0','0','0','17','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KING KROACH','킹크로치','118','1','3','0','9','274','674');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('KING POETIC','킹포에틱','0','0','0','0','0','0','22');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LA LINGERIE','라 란제리','71','1','2','0','0','7','120');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LA COKA NOSTRA','라 코카 노스트라','10','0','0','0','0','1','82');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LA CLOUDNINE','라 클라우드나인','56','3','2','4','0','156','275');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAGUNA BEACH JEAN','라구나비치진','954','0','4','0','0','291','592');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LANEIGE','라네즈','35','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LADLAB','라드랩','22','1','0','0','0','24','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LALASALAMA','라라살라마','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LA MER MA MAISON','라메르마메종','430','2','4','13','11','632','1,383');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAMODECHIEF','라모드치프','451','7','10','322','34','835','634');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAVANTANO','라반타노','92','0','2','2','0','0','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAVERIE','라베리에','18','0','0','0','0','1','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAVIE','라비','13','0','1','0','0','1','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LA STRADA','라스트라다','47','1','0','0','1','14','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOWT','라우트','15','0','0','0','0','4','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAUL','라울','426','0','7','2','7','940','1,129');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIKERISE','라이크라이즈','36','1','0','24','4','30','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIKE SOME MORE','라이크썸모어','44','1','1','0','0','8','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIKE JAZZ','라이크재즈','40','2','7','5','1','1','116');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIKELIHOOD','라이클리후드','153','0','1','4','0','2,547','395');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIGHTPLACE','라이트플레이스','96','1','1','11','7','3,250','792');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIFUL','라이풀','492','13','181','196','49','22,840','22,102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIFE','라이프 아카이브','80','2','10','1','4','118','402');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIFEWORK','라이프워크','1,068','3','18','160','42','226','725');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAKAI','라카이','123','1','8','70','9','598','457');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LACOSTE','라코스테','617','0','10','12','0','830','6,731');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LACOSTE EYEWEAR','라코스테 아이웨어','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LACOSTE UNDERWEAR','라코스테 언더웨어','70','0','2','0','0','182','314');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LARTIGENT','라티젠','1,050','10','36','32','11','642','2,141');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAFAYETTE','라파예트','392','3','1','1','0','67','300');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAFUDGESTORE','라퍼지스토어','126','20','283','204','51','85,895','30,527');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAPRICALA','라프리카라','14','0','1','9','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAPLAGE','라플라주','39','0','0','0','0','12','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAFLORIDA','라플로리다','129','0','4','0','0','1,306','324');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LA FILLETTE','라피예뜨','78','0','0','0','0','77','68');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAHYANG','라향','10','0','0','0','0','46','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOCK FINGER','락핑거','31','1','2','5','0','18','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LANVIN','랑방','21','0','3','0','0','0','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LANG VERSIO','랑베르시오','217','3','0','0','50','388','910');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LANGSAMER','랑자머','46','3','8','18','0','7','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAMB BY D','램바이디','40','1','0','18','16','1,315','899');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAP','랩','231','0','11','11','2','97','680');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAB101','랩101','150','8','24','18','88','948','1,248');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAB12','랩12','160','6','5','15','4','8,305','2,146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUGZ','러그즈','102','0','4','0','0','33','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOVE ME MONSTER','러브미몬스터','180','3','6','0','2','92','176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOVE ME BACK','러브미백','102','0','1','0','2','13','180');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUV IS TRUE','러브이즈트루','1,228','9','46','52','52','2,568','9,315');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUVISTRUE GIRL','러브이즈트루 걸','17','0','0','0','0','10','225');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUVISTRUE STREET','러브이즈트루 스트릿','25','0','0','0','0','542','190');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUCKYDICE','럭키다이스','24','1','3','0','0','8','130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUCKY PLANET','럭키플래닛','38','1','2','15','15','78','124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LONDONTRADITION','런던트레디션','59','1','2','4','0','42','351');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUVUR','럽유어','83','3','3','13','87','134','368');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LES COLORER','레꼴로헤','51','2','0','0','1','33','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEATHERGOODS','레더굿즈','27','0','2','2','0','2','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEATHERLESS','레더리스','92','0','3','13','0','60','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEATHERSMITH','레더스미스','95','0','2','0','0','104','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LESS, BUT BETTER','레스 벗 베러','51','0','5','2','0','1,200','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LESS IS MORE','레스이즈모어','86','0','0','0','0','51','80');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAYDEN','레이든','258','0','0','0','0','1,892','843');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LADY VOLUME','레이디 볼륨','229','14','71','177','28','5,090','4,235');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LABELESS','레이블리스','59','1','2','3','0','3','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEIVY','레이비','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEIUR','레이어','9','1','2','31','4','86','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAYER UNION','레이어 유니온','627','8','25','76','25','2,241','1,555');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAYERMOOD','레이어무드','180','2','9','17','3','17','158');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LETTER FROM MOON','레터프롬문','138','5','18','62','16','622','3,603');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LETTERCOMO','레테르코모','43','2','2','1','1','314','485');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LE2','레투','123','6','17','76','29','347','642');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LETTRE DE LE TOILE','레트흐드레뚜왈','47','0','1','4','2','25','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LETQ STUDIO','레티켓 스튜디오','111','2','3','1','0','112','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEFENERY','레페너리','47','1','3','8','0','0','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEFF AMSTERDAM','레프 암스테르담','62','0','2','4','0','5','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEFINO','레피노','82','0','2','0','4','98','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEXIS','렉시스','50','2','7','49','1','13','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LECTRO','렉트로','47','0','0','0','0','6','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LONER','로너','364','2','12','5','1','2,193','2,507');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LODIS','로디스','205','0','0','0','0','86','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOSTGARDEN','로스트가든','86','1','15','28','45','781','599');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOSTANDFOUND','로스트앤파운드','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOYALFRIEND','로얄프랜드','11','0','0','0','0','1','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOEIL','로에일','246','3','8','0','3','369','589');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOWER','로우어','147','0','13','45','5','5','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOISSHOE','로이스슈','4','0','0','0','0','35','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEUCHTFEUER STRICKWAREN','로이흐트포이어 슈트릭바렌','64','0','1','0','0','1,022','551');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAUSANNE','로잔','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOJEL','로젤','79','1','0','0','1','16','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOKWARD','로커드','183','1','1','5','0','729','431');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOCATE','로케이트','21','1','1','0','0','80','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOCLE','로클','1,215','5','31','7','6','1,463','2,845');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOTUFF','로터프','512','0','8','12','0','570','446');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOFI','로파이','76','11','111','57','35','19,578','9,478');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOKCHE','록체','35','0','6','19','1','5','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LONSDALE','론즈데일','145','0','0','0','0','228','124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOHNT','론트','70','3','4','6','2','529','710');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOLO','롤로','61','1','1','0','6','126','80');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('L'OMBRILLANT','롬브리앙','131','0','3','10','14','4','125');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOMHEAVEN','롬헤븐','25','1','3','0','0','0','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LONGCHAMP','롱샴','204','0','1','0','0','3','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LONGPLAYINGRECORD','롱플레잉레코드','28','0','9','0','1','15','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUNA','루나','4','0','1','2','0','5','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUNA SANDALS','루나샌들','0','0','0','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUNACY','루나시','48','3','0','2','2','28','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUDE','루드','171','0','0','1','0','22','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUMINOX','루미녹스','79','0','0','0','0','4','138');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOUPS BLANCS','루블랑','334','7','0','42','9','4,397','2,888');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUCY CREW','루시크루','0','1','6','32','20','2','103');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUOESPAC','루오에스팩','29','1','3','24','4','846','261');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUWU','루우','30','0','0','0','0','105','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOUIS QUATORZE','루이까또즈','118','1','8','0','2','155','385');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOOSE RIDERS','루즈 라이더스','28','0','0','0','0','2','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOOKING4U','루킹포유','151','3','31','2','4','341','236');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOOKAST','룩캐스트','978','10','54','80','60','881','2,533');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUNECAVE','룬케이브','46','0','2','0','0','35','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUNPEL','룬펠','28','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LOOM LOOM','룸룸','41','1','7','18','9','3','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LUEUR PARIS','뤼에르','27','0','6','2','1','7','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LECOQ','르꼬끄','891','19','69','47','18','5,333','6,218');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LE CORDONNIER','르꼬르도니에','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LENOID','르노이드','67','0','4','0','1','596','290');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LENINA','르니나','38','1','2','0','0','1','190');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LE_DAZZLE','르다즐','24','1','1','0','0','13','245');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEMASKA','르마스카','55','1','2','0','3','107','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LE MASQUE','르마스크','65','5','7','13','20','120','263');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEMINE','르마인','128','6','4','43','1','518','372');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LE MINUIT','르미닛','48','0','0','0','0','124','153');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEVOU','르보우','9','0','0','0','0','182','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LECHATELARD1802','르샤트라1802','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LE SPECS','르스펙스','22','0','1','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEIRE','르아르','145','4','22','142','19','3,771','1,478');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEE','리','34','2','25','76','5','4,456','2,592');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIRIKOS','리리코스','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIRIK','리릭','16','0','0','0','0','3','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEVI'S','리바이스','397','1','77','75','4','1,960','2,867');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIBERTENG','리베르텡','170','6','34','27','21','2,796','2,342');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LYCEENNE','리센느','28','1','2','0','0','112','191');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEESLE','리슬','23','0','0','0','1','3','137');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('leeENoir','리엔느와르','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIEU','리우','1,144','7','20','22','20','3,174','1,135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEEJEE','리지','43','0','1','0','0','18','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIQUOR BRAND','리쿼브랜드','154','0','0','0','0','32','204');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEATA','리타','796','0','2','0','0','5,412','4,970');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIT','리트','95','7','12','4','25','1,064','764');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LI FLA','리플라','204','0','13','71','0','204','293');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEAPLING','리플링','30','0','1','0','0','2','80');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEE FIELDS','리필즈','36','1','0','0','1','44','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LINBO','린보','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LIINTA','린타','19','0','0','0','0','1','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LINCOLNFRAME','링컨프레임','84','0','2','1','0','22','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LWL','엘더블유엘','0','0','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LMOOD','엘무드','167','2','20','35','3','10,657','5,082');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LANDJ','엘앤드제이','6','0','0','0','0','29','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LSW','엘에스더블유','13','0','0','0','0','15','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LAR','엘에이알','15','4','1','0','1','65','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('L.L.BEAN','엘엘빈','7','0','0','1','0','5','43');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LMC','엘엠씨','973','15','374','203','66','95,689','71,506');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LMN3011','엘엠엔3011','62','6','0','2','18','24','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('L.U.P','엘유피','219','4','0','0','10','37','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LTCK','엘티씨케이','75','6','0','76','10','91','356');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LPC','엘피씨','8','1','1','0','2','3','163');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEE SEUNGBIN','이승빈','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('LEEHO','이호','22','0','4','6','1','1','148');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARGARIN FINGERS','마가린핑거스','327','7','41','117','35','755','8,151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANAVIS7','마나비스세븐','177','6','11','34','10','91','134');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANES','마네스','137','3','22','12','2','631','393');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANYOFACTORY','마녀공장','42','0','1','0','1','7','249');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANOD','마노드','43','3','0','24','1','9','116');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANOMOS','마노모스','173','2','4','0','115','28','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANOTI','마노티','52','0','0','0','0','267','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANI E PIEDI','마니에피에디','192','5','13','36','89','71','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARE','마레','8','1','1','0','0','1','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARNI','마르니','40','0','3','2','0','0','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARCELO BURLON','마르셀로 불론','17','0','0','0','0','3','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARSBOM','마르스봄','70','0','0','0','0','5','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARCIO DIEGO','마르시오디에고','34','0','1','0','0','1','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARCOROHO','마르코로호','18','0','0','0','0','654','404');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARTENATA','마르테나타','16','0','1','0','0','1','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARHEN.J','마르헨제이','32','0','4','0','2','38','394');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARITHE FRANCOIS GIRBAUD','마리떼 프랑소와 저버','18','1','5','3','7','91','480');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARYMOND','마리몬드','286','6','30','5','5','1,346','2,650');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARMOT','마모트','299','0','26','1','4','176','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAMONDE','마몽드','86','0','0','0','0','19','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARVEL','마블','149','0','2','0','0','22','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MASA DE OSCURA','마사드오스큐라','12','0','1','0','0','1','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MASKA','마스카','181','2','6','0','45','52','191');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOTIVE MASCOLANZA','마스콜란자','5','0','2','0','1','219','137');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MASKITSCH','마스키치','99','0','2','0','0','54','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARSILER','마실러','701','0','0','0','0','478','440');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAEDA RYUTO','마에다 류토','51','0','1','7','22','774','1,319');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAUI&SONS','마우이앤선즈','112','4','21','71','19','609','420');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINUS-8','마이너스 에잇','9','0','1','0','0','4','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINU','마이누','60','1','2','3','0','27','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MY MIXED DESIGN','마이믹스드디자인','163','0','0','0','0','135','116');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIAMIPROJECT','마이애미프로젝트','26','0','0','0','9','1,727','698');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAIOUN','마이오운','12','0','1','0','0','8','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MICHAEL KORS','마이클 코어스','160','0','4','1','0','7','157');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIND MASTER','마인드 마스터','0','0','0','0','0','0','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINDBRIDGE','마인드브릿지','159','2','0','0','0','30','107');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILDMODE','마일드모드','17','2','1','7','5','87','176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAJESTIC','마제스틱','111','2','2','10','2','518','316');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MA JOURNEE','마조네','68','2','22','18','5','19','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAJO FACTORY','마조팩토리','31','2','6','12','0','21','378');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARGESHERWOOD','마지셔우드','4','0','6','2','2','3','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAZI UNTITLED','마지언타이틀','49','4','3','90','4','141','223');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARCHWITH','마치위드','163','0','0','0','0','985','772');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARK GONZALES','마크 곤잘레스','300','13','301','231','148','62,904','40,069');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARK-4','마크-4','396','0','0','0','1','10,055','1,610');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARKMATE','마크메이트','193','0','0','0','0','1,436','449');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAC MOC','마크모크','355','0','23','39','1','232','728');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARCATORY','마크에이토리','42','4','0','48','33','9','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARKM','마크엠','414','3','54','66','56','175','558');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARC JACOBS','마크제이콥스','285','0','4','5','0','80','1,569');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MATHEMATIK','마테마틱','64','0','1','1','0','52','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARTISTIQUE','마티스티크','5','0','0','0','0','1','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARTINCOKS','마틴콕스','56','1','2','10','2','164','206');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAHAGRID','마하그리드','432','10','148','90','60','48,728','30,622');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAHOGANI','마호가니','41','0','2','0','0','2','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAXMARA','막스마라','350','0','2','4','0','1','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARKSMAN','막스맨','13','0','0','0','0','6','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('man.G','만지','556','0','6','2','0','268','1,510');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MALRANG','말랑','86','1','2','0','0','21','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MALEN','말렌','82','1','3','0','1','26','404');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MALOJA','말로야','298','0','0','0','0','2','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MALIBU SANDALS','말리부샌들','18','0','1','1','0','85','167');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAGAZINE B','매거진 비','32','0','5','0','0','18','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANIAMASS','매니아매스','104','0','0','8','0','32','140');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANNEQUIN','매니퀸','357','0','2','0','0','309','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MENIPELLO','매니펠로우','16','1','4','1','0','77','228');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MADGOAT','매드고트','189','0','2','0','0','64','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MADMARS','매드마르스','607','10','100','55','57','12,878','7,057');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MADN','매든','42','0','1','21','0','473','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAEDY','매디','209','0','1','0','1','19','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MASSNOUN','매스노운','510','9','58','306','72','5,248','4,170');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MASSIVE GROOVE','매시브그루브','24','1','0','0','0','130','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MALE 24365','매일 24365','319','1','1','0','1','18','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEZMIC','매즈믹','138','0','0','0','9','4','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAGICMOHICAN','매직모히칸','15','0','0','0','0','735','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAGIC CHANNEL','매직채널','274','0','0','0','0','137','99');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MATCHGLOBE','매치글로브','1,291','15','115','246','26','5,388','6,838');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MACKAY','매카이','73','1','2','0','1','307','78');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MACK BARRY','맥베리','152','4','4','1','54','3,904','887');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MACARTHUR','맥아더','12','0','0','0','0','7','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MCNCHIPS','맥앤칩스','48','4','3','1','3','425','1,448');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAGOODGAN','맥우드건','249','11','14','61','15','1,063','539');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MACKAGE','맥케이지','0','0','0','0','0','0','104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MCCOIN','맥코인','77','0','0','0','0','18','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAGPIEROBIN','맥파이로빈','64','1','1','2','2','249','1,094');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAGFORCE','맥포스','159','0','0','0','0','104','298');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAGFORCEBLACKLABEL','맥포스블랙라벨','0','0','0','0','0','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANSIONAIR','맨셔네어','75','1','0','0','0','4','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEN IN JUNGLE','맨인정글','137','3','2','7','4','143','184');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANHATTAN PORTAGE','맨하탄 포티지','148','0','46','98','8','907','639');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MANHATTANPASSAGE','맨하탄페세지','49','0','0','0','0','2','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MATT&NAT','맷앤냇','6','0','0','0','0','2','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUVECLOTHING','머브클로딩','12','0','1','23','1','3','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERZE','머즈','12','2','1','0','0','0','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUFF','머프','3','1','3','0','1','34','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONDAY EDITION','먼데이에디션','92','2','22','30','4','403','493');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONDAY HIKING','먼데이하이킹','65','2','6','69','9','272','771');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MULLIGAN','멀리건','6','0','1','0','0','20','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERLIC','멀릭','60','0','3','0','22','1','71');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MULBERRY','멀버리','171','0','0','0','0','2','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEGA PACK','메가팩','244','2','14','45','1','726','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEGAPHONE','메가폰','93','1','0','0','0','153','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEROMERO','메로메로','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERCEDES-BENZ','메르세데스-벤츠','23','0','3','0','0','7','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERSUA','메르수아','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERKEN','메르켄','77','0','9','0','1','4','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERRIMENT','메리먼트','415','7','8','81','11','1,623','550');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERRYMOTIVE','메리모티브','206','6','11','0','1','87','368');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MARYJAMES','메리제임스','716','1','5','18','0','774','1,334');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MERRYCOOP','메리쿱','36','1','1','1','0','10','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEMENMORI','메멘모리','25','0','2','0','0','94','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MESSAGE IN THE SOCKS','메시지인더삭스','46','1','2','4','0','71','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MADEHANMUT','메이드한멋','29','0','2','0','1','16','255');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MADIN'LY','메이딘리','125','0','0','0','20','0','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEIEL DEW','메이엘듀','63','0','4','6','0','0','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAKE D','메이크 디','15','1','0','0','0','4','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAINBOOTH','메인부스','459','10','118','30','108','12,052','16,422');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEZZOKUNST','메조쿤스트','135','5','4','50','5','67','497');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAISON MARGIELA','메종 마르지엘라','116','0','44','3','0','13','701');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAISON DE SUCRE','메종드슈크레','79','0','0','0','0','130','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAISONDEINES','메종드이네스','150','2','4','1','2','15','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAISON MINED','메종미네드','140','7','37','49','33','8,670','3,897');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MECHANIX WEAR','메카닉스웨어','60','0','0','0','0','33','109');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('METAPHER','메타퍼','166','18','37','22','40','2,862','1,328');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('METAL MULISHA','메탈물리샤','241','0','0','0','0','90','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MATHEY-TISSOT','메티티솟','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('METIF','메티프','35','0','0','0','0','13','17');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MCCOII','멕코이','208','4','8','0','7','100','237');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MELANGE MASTER','멜란지 마스터','204','5','139','248','20','43,331','6,805');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MELLOWUS','멜로우어스','62','0','1','0','0','127','194');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MELIC','멜릭','101','0','1','0','0','25','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MELTINGLOW','멜팅글로우','50','0','0','0','0','10','179');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MO SPORTS','모 스포츠','34','2','8','9','6','247','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONONO','모노노','72','0','9','3','0','9,298','1,455');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOLOUNGE','모노라운지','134','3','16','30','37','497','420');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOMANIA','모노마니아','0','0','0','0','0','0','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOCLOTHES','모노클로즈','65','4','4','0','5','129','173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOTYPE','모노타이프','61','0','3','0','0','261','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOTHEME','모노템','11','0','0','0','0','3','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOPATIN','모노파틴','135','2','0','7','0','15','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOFOLD','모노폴드','32','1','1','0','0','206','210');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONOFLOW','모노플로우','120','7','21','57','18','1,606','1,444');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODERATE','모더레이트','20','1','14','1','3','0','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODERMENT','모더먼트','251','8','17','213','17','5,429','1,179');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODERNSTUDIOS','모던스튜디오','37','1','3','0','5','106','144');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODERNABLE','모던에이블','58','0','3','0','2','5','122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODGONE','모드곤','130','0','0','0','0','1','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODNINE','모드나인','177','4','24','46','26','22,381','9,476');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODELIMITE','모드리미트','12','2','6','29','13','55','67');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MODIFIED','모디파이드','1,381','5','114','30','8','85,396','29,546');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORANYIF','모라니프','29','0','1','0','2','3','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORAN','모란','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORO','모로','18','0','2','0','1','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORL','모르','44','0','7','35','0','21','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORPYN','모르핀','9','0','0','0','0','6','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOMENT WATCHES','모먼트워치','174','0','0','0','0','3','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAUVAIS GARCONS','모베가르송','20','0','0','0','0','54','188');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAUVE','모브','191','3','3','2','1','164','621');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOVINS.R','모빈스알','97','7','2','8','3','7','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOAA','모아','242','10','63','221','17','5,322','6,326');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORE THAN LIKE','모어댄라이크','75','0','0','0','26','151','2,467');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORE OR LESS','모어올레스','205','6','14','22','13','194','694');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOREJUDE','모어쥬드','53','1','3','0','2','7','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOYEN','모옌','330','1','0','39','0','2,581','1,560');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOIMOII','모이모이','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOI STUDIO','모이스튜디오','105','0','0','0','16','27','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOZMOZ','모즈모즈','28','1','0','0','0','42','208');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOCCASOM','모카썸','61','0','3','4','0','63','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOKUYOBI','모쿠요비','50','0','0','0','0','7','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOTOMOTO','모토모토','98','2','5','0','1','293','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOTT','모트','60','0','4','23','0','22','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOTIVESTREET','모티브스트릿','569','10','79','127','37','12,952','5,909');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORP','모프','73','2','1','0','0','18','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOHAN','모한','194','0','0','1','0','37','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOHO','모호','28','0','2','8','0','9','76');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONDAINE','몬데인','0','0','0','0','0','0','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONSTER REPUBLIC HEADWEAR','몬스터 리퍼블릭 헤드웨어','19','0','0','0','0','15','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONSTER REPUBLIC','몬스터리퍼블릭','48','2','48','8','10','15,747','2,090');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONTANA','몬타나','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MORE THAN DOPE','몰덴돕','287','5','10','12','19','463','2,021');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOLLIVE','몰라이브','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOLIBDENO','몰리브데넘','20','0','1','0','1','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOLLIOLLI','몰리올리','55','0','5','18','0','26','80');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MALLING BOOTH','몰링부스','895','0','12','0','4','1,340','848');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOLING BLING','몰링블링','24','0','0','0','0','33','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOLESKINE','몰스킨','39','0','0','0','1','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONTBELL','몽벨','250','1','13','3','1','629','359');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONBRIC','몽브릭','25','1','1','0','0','8','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONTBRUN','몽브항','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONTBLANC','몽블랑','679','0','2','0','0','437','969');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONCHOUCHOU','몽슈슈','425','0','2','0','0','19','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONCLER','몽클레어','789','0','8','2','0','0','591');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Monkey Flower','몽키플라워','214','1','5','16','0','26','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MONGTANA','몽타나','21','2','0','6','1','392','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOONEED','무니드','69','1','0','0','0','13','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUDERN','무던','19','0','0','0','0','1','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOOD DOOP','무드 둡','0','2','4','4','2','16','304');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUDIDI','무디디','22','1','3','0','0','8','118');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOOMUUA','무무아','33','0','0','0','0','4','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUSEIONE','무세이온','22','2','2','0','0','9','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOOSE KNUCKLES','무스너클','203','0','6','2','0','252','791');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUSINSA','무신사','56','0','309','11','8','1,496','1,960');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUSINSA STANDARD','무신사 스탠다드','1,698','10','681','514','132','671,805','60,949');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOOSIM','무심','44','1','0','3','0','105','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUJJO','무쪼','75','0','0','0','0','25','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOOCHUU','무츄','67','0','7','5','1','155','100');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MSKN2ND','문수권세컨','400','6','41','59','145','1,153','2,813');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOONSWARD','문스워드','25','2','14','0','2','1','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOON=BLUE','문이퀄블루','47','0','8','4','9','2','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUNN','뮌','7','0','4','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUGUET','뮤게','80','5','2','2','61','19','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUER','뮤에','15','1','2','4','0','0','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUSEE','뮤제','179','3','14','3','112','32','267');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUSEMONT','뮤즈몽','59','0','8','5','3','8','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUSE BY ROSE','뮤즈바이로즈','245','2','3','3','2','25','150');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUZIK','뮤지크','215','1','9','4','57','26','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUTO','뮤토','148','1','12','0','1','734','149');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUTEMENT','뮤트먼트','29','0','0','1','3','27','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUTEMUSE','뮤트뮤즈','54','6','4','0','1','2','405');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MUTECOMMONSENSE','뮤트커먼센스','17','0','1','0','0','3','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINAV','미나브','304','2','88','242','83','40,390','10,167');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIGNONNEUF','미뇽네프','534','8','141','217','58','17,095','14,248');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINUTTE','미뉴뜨','0','0','0','0','0','0','1');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINIMALCODE','미니멀코드','202','4','11','49','8','3,748','856');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINIMALPROJECT','미니멀프로젝트','165','4','9','35','7','2,338','2,027');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIDNIGHT MOVE','미드나잇 무브','537','8','45','118','30','1,396','2,231');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIIMAMASK','미마마스크','6','0','0','0','2','5','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIMIXIU','미미시우','31','0','1','0','24','16','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIMICAWE','미미카위','453','6','16','11','5','307','1,423');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIMINKO','미밍코','247','0','0','0','1','12','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MISSUE','미슈','95','1','4','0','0','1','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MISHUU SOMUCH','미슈쏘머치','43','0','3','9','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MR MUSTARD STUDIO','미스터 머스타드 스튜디오','34','0','0','0','0','111','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MR&MRS','미스터앤미세스','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MISTER CHILD','미스터차일드','62','2','6','24','7','104','404');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MYSTERYRANCH','미스테리랜치','30','0','2','0','0','3','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MISTICDUN','미스틱던','18','1','3','0','0','31','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MISHKA','미시카','339','0','1','1','0','202','638');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIXXO','미쏘','893','1','17','5','8','480','1,099');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEOWBYMINA','미야우바이미나','47','0','1','0','0','3','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIU MIU','미우미우','74','0','0','12','0','0','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIZU','미쥬','143','0','5','0','0','107','155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Mitchell and Ness','미첼앤네스','30','0','4','0','1','108','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIK','미크','141','0','0','0','0','2','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MITTE','미테','50','1','0','0','0','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIP','미프','35','0','3','0','1','31','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MICKS','믹스','16','0','0','1','0','9','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MINTA RETRO','민타레트로','185','0','0','0','6','12','236');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLET','밀레','122','2','51','46','0','146','699');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLET CLASSIC','밀레 클래식','152','8','102','214','81','5,081','4,320');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLOGREM','밀로그램','581','5','7','1','84','160','392');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLIBAR','밀리바','15','1','2','0','1','21','122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLIONAIRE HATS','밀리어네어햇','101','3','44','24','21','6,001','870');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLIONCOR','밀리언코르','319','0','32','182','202','1,780','1,911');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILITARIA PRESS','밀리터리아프레스','38','0','1','0','0','2','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MWC WATCH','밀리터리와치','9','0','0','0','0','28','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLIN','밀린','65','3','19','1','3','21','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILSPEC MONKEY','밀스펙몽키','116','0','0','0','0','13','106');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILKY','밀키','14','1','2','15','4','38','501');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILTON STELLE','밀튼 스텔리','196','0','0','0','0','13','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILTONM','밀튼엠','43','0','2','0','0','1','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MILLFLAT','밀플랫','12','1','1','0','0','33','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIMTHEWARDROBE','밈더워드로브','8','0','0','0','0','432','241');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEETMETMEET','밋맷밋','108','0','2','0','0','628','361');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('M082','엠공팔이','31','1','2','0','6','0','134');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MGLAM','엠글램','116','3','8','2','5','2,944','420');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('M.Nii','엠니','226','0','14','0','3','643','456');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MWC','엠더블유씨','40','0','3','0','0','7','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MDOC','엠도씨','54','0','3','0','1','26','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MD PLUS','엠디플러스','24','1','1','0','0','0','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('M-LIMITED','엠리밋','3','0','6','0','2','300','43');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MVIO','엠비오','108','2','28','31','21','351','598');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MIS','엠아이에스','117','0','0','0','0','4','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MSMS','엠에스엠에스','5','1','1','6','1','76','244');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MSUL','엠에스유엘','45','0','0','0','0','29','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MSGM','엠에스지엠','298','0','2','5','0','3','165');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MAW','엠에이더블유','275','4','20','43','51','3,725','891');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MFNT','엠에프엔티','13','0','1','1','0','6','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MNW','엠엔더블유','103','2','9','2','0','418','292');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MLB','엠엘비','1,427','12','153','156','31','9,512','9,562');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MMIC','엠엠아이씨','436','4','16','277','83','247','578');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MMH','엠엠에이치','2','2','5','14','33','183','222');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MMGL','엠엠지엘','209','8','53','200','16','6,011','2,594');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOL','엠오엘','156','2','5','9','3','200','122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('M.O.M.G','엠오엠지','37','1','3','0','0','6','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MOO','엠오오','76','2','1','0','0','154','173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MEP','엠이피','67','2','2','2','58','127','125');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MGMG STUDIO','엠지엠지 스튜디오','328','9','20','21','6','389','2,280');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MCASE','엠케이스','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MTO DESIGN','엠토디자인','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MTM','엠티엠','53','0','0','1','0','0','78');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('MPG','엠피지','124','1','1','0','0','6','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAGUISA','나귀사','194','2','8','18','1','1','145');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NANA CREW','나나크루','76','3','3','4','3','41','611');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAR','나르','64','0','1','0','31','3','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAVA DESIGN','나바디자인','23','0','0','0','0','2','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAU','나우','56','2','5','0','1','8','328');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOWANDTOMORROW','나우앤투모로우','36','3','2','12','14','240','435');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOWWHAT','나우왓','99','3','8','43','6','651','419');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAISHO','나이쇼','66','1','2','11','1','62','226');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NIKE','나이키','5,294','0','1,290','1,079','2','47,376','69,745');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NIKE SWIM','나이키 스윔','158','1','2','0','0','108','604');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NIKE EYEWEAR','나이키 아이웨어','77','0','10','0','3','21','259');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NIGHT FLOW','나이트플로우','77','3','2','0','28','27','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NINE DOLLAR','나인달러','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NINEOCTOPUS','나인옥토퍼스','36','1','3','0','2','165','523');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NINE ELEVEN','나인일레븐','111','3','0','0','43','242','347');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAPAPIJRI','나파피리','57','0','32','56','6','74','162');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOTKNOWING','낫노잉','77','7','21','138','24','277','390');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOTHINGISBETTERTHANME','낫띵이즈베럴댄미','14','1','1','3','7','22','192');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOTNNOT','낫앤낫','177','6','21','19','13','7,815','1,853');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOTYETGUYS','낫옛가이즈','7','1','1','0','3','2','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOT4NERD','낫포너드','116','8','18','47','12','2,306','1,466');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NARROWMIND','내로우마인드','27','3','1','0','13','28','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NATIONAL PUBLICITY','내셔널 퍼블리시티','50','0','9','13','4','10,050','1,008');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NATIONALGEOGRAPHIC','내셔널지오그래픽','1,184','8','313','80','40','46,122','44,682');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUTANDBOLT','너트앤볼트','104','0','0','0','0','481','1,220');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUL','널','12','0','2','11','0','40','176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NERDY','널디','445','10','66','18','2','5,691','10,007');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUMVERSTAR','넘버스타','52','0','0','0','1','16','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUMBERPLANT','넘버플랜트','7','0','0','0','0','34','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEVERCOMMON','네버커먼','59','0','0','0','1','135','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEVERFLOW','네버플로우','17','0','0','0','0','63','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NASTYKICK','네스티킥','744','14','151','239','120','18,512','21,705');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NASTY PALM','네스티팜','767','2','13','12','7','4,506','8,308');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NASTY FANCY CLUB','네스티팬시클럽','231','3','44','166','65','3,253','4,492');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NASTYHABIT','네스티해빗','49','0','0','0','0','64','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NASTY HABIT COLLECTION','네스티해빗 컬렉션','35','1','0','0','0','1','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAMERCLOTHING','네이머클로딩','75','7','6','23','3','343','899');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEIGHBORS','네이버스','305','1','2','1','4','281','310');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAVY','네이비','3','0','1','0','1','0','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEIKIDNIS','네이키드니스','235','3','97','62','21','13,165','2,984');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAKED&FAMOUS','네이키드앤페이머스','266','1','2','0','0','229','1,122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NATIVE','네이티브','8','0','0','0','0','113','150');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NATIVE SONS','네이티브선스','0','0','0','0','0','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAMED SHOES','네임드슈즈','118','1','1','0','4','8','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NAMEOUT','네임아웃','98','0','0','1','0','117','235');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NETT GRAY','네트그레이','30','0','0','0','0','73','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEPA','네파','43','1','35','19','8','712','1,519');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEXTORCH','넥스토치','51','0','0','0','0','5','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NODOUBT NOWAY','노다웃노웨이','33','0','1','0','0','3','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NODE','노드','23','2','1','11','1','11','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NORDICISLAND','노르딕아일랜드','248','2','9','12','1','1,080','626');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOMAD','노마드','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOMADIC','노마딕','17','0','1','0','0','13','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NO MAS','노마스','223','0','0','0','0','83','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOMANUAL','노매뉴얼','321','5','23','103','29','8,462','6,305');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NORMALPEOPLE','노멀피플','27','1','1','4','0','0','138');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOMONICO','노모니코','63','0','5','20','2','20','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOMINATE','노미나떼','197','6','6','0','4','182','697');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOMINATION','노미네이션','123','0','0','0','25','40','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOVESTA','노베스타','192','0','53','105','10','1,576','609');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOVELLA','노벨라','88','1','1','6','5','112','158');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOVELCLOTHES','노블클로즈','129','2','1','9','10','114','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOBIS','노비스','0','0','0','0','0','0','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOVIO','노비오','16','0','2','0','0','54','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOART','노아트','118','0','0','0','0','289','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOHANT','노앙','263','5','39','6','2','927','3,502');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOIRER','노이어','262','5','4','11','5','319','561');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOIZE','노이즈','12','1','0','0','0','0','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOIZYCOMPANY','노이지컴퍼니','120','3','6','105','5','290','893');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOYCOMMON','노이커먼','507','9','19','387','11','2,764','2,806');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOCLAIM','노클레임','58','2','1','4','0','69','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOTABAG','노타백','28','0','1','4','1','18','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOPASTNOFUTURE','노패스트노퓨처','20','1','2','1','0','4','168');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOPAINNOSAKS','노페인노삭스','30','0','1','0','0','691','231');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOFFICIALNOFFICE','노피셜노피스','184','0','19','20','3','54','340');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOK NOK','녹녹','14','0','0','0','0','2','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NONENON','논논','161','1','7','5','52','5,622','1,968');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NONDISCLOTHES','논디스클로즈','49','1','5','6','3','167','1,844');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NONLOCAL','논로컬','479','8','49','109','57','524','997');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NONMAINSTREAMER','논메인스트리머','13','1','13','0','1','0','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NONSEASON BY MARGESHERWOOD','논시즌 바이 마지셔우드','6','0','2','1','0','2','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUKAK','누깍','1,554','0','4','6','0','132','370');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOONOO FINGERS','누누핑거스','323','4','5','13','1','61','578');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUDIEJEANS','누디진','221','0','21','18','1','5,800','5,409');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUBES','누베스','115','0','2','0','0','178','212');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOUVEAU AND MORE','누보 앤드 모어','52','0','0','0','0','6','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUVO10','누보텐','165','4','9','17','8','27','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUANAME','누아네임','109','0','0','27','5','593','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUAVO','누아보','103','1','4','39','1','2','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUEVO','누에보','132','0','0','2','0','1,005','703');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOUVENE','누엔','84','1','3','0','8','19','212');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUUY GNASEEL','누이 그나실','533','3','9','4','3','4,107','788');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NU PARCC','누팍','214','4','14','0','6','14','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NUPER','누퍼','26','0','1','0','0','16','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEWNOW','뉴나우','305','0','0','0','0','115','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEW BALANCE','뉴발란스','380','10','400','330','59','15,393','18,996');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEWBIE','뉴비','52','2','2','28','3','53','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEW YORK HAT CO.','뉴욕 햇','122','0','1','1','0','121','224');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEW:KIT','뉴킷','163','6','10','46','41','4,694','1,039');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEWHATTAN','뉴해튼','49','0','2','0','0','562','240');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOIR','느와','698','10','54','210','19','523','3,155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NII','니','508','1','1','11','4','161','388');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NINANOSANO','니나노사노','61','0','2','3','0','43','88');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NINA RICCI','니나리치','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEED','니드','658','0','0','2','0','220','195');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEEDMORE','니드모어','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NIVELCRACK','니벨크랙','20','2','2','0','0','17','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEAR&DEAR','니어앤디어','89','2','7','7','40','14','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NIGER','니제르','207','2','1','5','0','1,035','361');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEEDUSHOP','니쥬샵','16','0','1','0','0','4','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEATA','니트에이','17','0','0','0','0','13','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NICK&NICOLE','닉앤니콜','195','0','9','19','1','187','367');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NEIL BARRETT','닐바렛','72','0','0','1','0','1','150');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NCOVER','앤커버','1,314','6','16','33','5','3,520','3,226');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NTHROPOID','앤트로포이드','82','1','1','0','0','3','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NDOZEN','엔더즌','37','2','8','10','9','340','278');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NBA','엔비에이','999','19','41','63','8','482','2,124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NND','엔엔디','83','1','2','0','1','5','137');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('NOT','엔오티','159','0','3','1','1','8','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OHUUU','스튜디오 오후','63','2','1','0','6','4','60');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OTHERSIDE','아더사이드','202','5','10','25','8','292','409');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OTHER-worldly','아더월들리','137','7','14','75','64','34','399');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUND','아운드','112','1','4','3','1','2','20');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OWL91','아울나인티원','125','10','37','18','13','1,385','1,176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OWL91-WOMAN','아울나인티원-우먼','10','0','0','0','0','13','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUTDOOR RESEARCH','아웃도어 리서치','31','0','2','0','1','1','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUTDOOR PRODUCTS','아웃도어 프로덕츠','212','17','115','79','36','10,377','8,163');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUTMODE','아웃모드','25','2','6','4','9','68','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUTSHELL','아웃셀','46','0','2','0','0','3','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUTSTANDING','아웃스탠딩','1,044','4','17','17','2','6,299','5,083');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUTX.O','아웃엑소','46','1','2','3','1','3','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUTOFCIRCLE','아웃오브서클','25','1','1','0','0','25','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUT OF OFFICE','아웃오브오피스','7','1','2','0','0','1','124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUR','아워','50','1','2','2','1','1','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OURSCOPE','아워스코프','23','2','18','19','8','26','892');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OURHISTORY','아워히스토리','6','4','23','44','4','3,484','1,309');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OCT31','악토버31','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OGANACELL','오가나셀','13','0','1','0','0','2','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OGOTAI','오고타이','38','0','0','0','0','37','60');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OGRAM','오그램','135','3','4','1','5','369','161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUGHIC','오그힉','82','0','0','0','0','12','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONORE','오노레','391','0','0','0','0','36','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONEILL','오닐','159','1','1','0','0','4','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ORDERPLEASE','오더플리즈','121','2','11','43','5','1,914','1,383');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ODD MONOCLE','오드모노클','55','0','1','0','0','1','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ODDMOOD','오드무드','14','0','0','0','0','42','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ODDSTUDIO','오드스튜디오','112','1','6','9','10','493','477');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ODDEYEWEAR','오드아이웨어','39','1','1','1','0','0','175');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ODDONEOUT','오드원아웃','494','8','62','84','26','3,011','8,777');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ODDCOLLET','오드콜렛','86','1','0','0','35','33','131');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ODD FUTURE','오드퓨처','36','0','0','1','0','4','1,130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OORRDDIINNAARRYY','오디너리','3','0','0','1','0','177','95');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ORDINARY DAY','오디너리 데이','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ORDINARY PEOPLE','오디너리피플','68','8','44','30','175','4,665','5,317');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OLIGHT','오라이트','0','0','0','0','0','0','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OHLADY','오레이디','10','0','2','0','0','73','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ORTLIEB','오르트립','13','0','0','0','0','9','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OHRLIN','오를린','67','1','6','0','4','0','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ORIGINAL SWAT','오리지날 스왓','39','0','0','0','0','17','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ORIGINAL CHUCK','오리지날 척','29','0','1','0','0','7','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OMETO','오메토','5','1','4','0','2','0','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OMOPLATAA','오모플라타','42','0','0','0','0','21','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OMOO JEANS','오무진','128','0','0','0','0','1,713','350');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OBAKU','오바쿠','82','0','0','0','0','12','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OVERTHEONE','오버더원','62','4','16','39','28','1,371','615');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OHVERDOSE','오버도스','86','0','0','28','9','275','195');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OVRDRV','오버드라이브','14','1','1','0','1','8','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OVERLAB','오버랩','13','0','0','0','6','12','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OVERBOARD','오버보드','130','0','1','0','0','7','68');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OVERCAST','오버캐스트','178','6','46','333','33','1,180','1,355');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OBERON','오베론','0','0','0','0','0','0','14');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OVERR','오베르','591','9','75','179','74','18,992','14,854');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OBEY','오베이','2,904','0','11','31','0','4,407','18,215');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OVDY','오브이디와이','144','2','8','61','20','164','544');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OBJECT','오브젝트','51','2','4','7','5','79','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OBLA','오블라','79','0','8','46','6','173','174');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OBLESS','오블레스','51','3','2','0','3','21','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OBG','오비지','48','2','7','16','3','185','197');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OCEANPACIFIC','오션퍼시픽','16','1','3','1','2','14','220');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OSMO','오스모','0','0','0','0','0','1','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OSEE','오씨','55','0','0','1','0','0','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OAAR','오아르','66','0','0','0','0','18','61');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OiOi','오아이오아이','389','5','52','45','71','767','25,829');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OROR','오알오알','95','9','10','51','9','275','235');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONA','오앤에이','211','7','35','65','37','14,402','7,666');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OH L','오앨','202','1','11','3','1','105','712');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ORYANY','오야니','57','0','4','2','0','7','345');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OST','오에스티','929','0','1','1','1','441','650');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OA STUDIO','오에이스튜디오','20','0','0','0','0','2','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OX STUDIOS','오엑스 스튜디오','104','0','0','0','0','264','219');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OOD','오오디','67','4','17','53','73','195','592');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OHOHEX','오오엑스','45','0','0','0','0','22','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OY','오와이','212','8','25','103','5','2,443','2,437');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OWNU','오운유','62','0','1','0','0','6','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OIAUER','오이아우어','68','2','19','5','2','7','358');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OIL LEAK','오일릭','23','0','0','0','0','1','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OJEH','오제','26','3','5','29','9','89','274');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OTZ','오찌','77','0','2','5','1','209','487');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OAKLEY','오클리','67','0','10','1','0','10','297');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OKIDOKI','오키도키','56','0','1','0','0','33','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OTTO CAP','오토캡','34','0','0','0','0','32','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OOPARTS','오파츠','157','3','7','22','2','260','730');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OFF ROUTE FESTIVAL','오프 루트 페스트','6','0','3','0','1','3','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OFF THE RECORD','오프더레코드','284','0','4','0','0','45','376');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OFFICIAL GARMENT','오피셜가먼트','81','1','3','12','0','163','145');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OHHIOH','오하이오','16','0','0','0','0','151','182');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OCT.3','옥토버써드','504','8','14','54','42','346','2,370');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONNE','온느','43','1','6','0','5','1','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONLYONCE','온리원스','60','0','0','0','0','6','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OLDIES&GOODIES','올디스앤구디스','21','0','0','0','0','3','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OLIVER PEOPLES','올리버 피플스','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OLIVERGOLDSMITH','올리버골드스미스','33','0','1','0','0','0','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OLIVERCUSTOM','올리버커스텀','24','0','0','0','3','932','170');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OLZEN','올젠','420','3','20','0','5','969','348');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('optical W','옵티칼더블유','301','0','1','0','4','129','165');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OOH-AHH','우아','380','8','61','81','26','4,091','8,390');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUAHSOMMET','우아솜메','212','0','5','0','53','12','129');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUSE','우즈','40','0','1','1','0','422','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OOFOS','우포스','8','0','7','1','0','2,011','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONE BRILLIANT','원브릴리언트','100','2','2','0','4','23','69');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONERM','원알엠','51','0','0','0','0','67','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONEOSEVEN','원오세븐','0','0','0','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONE ENOUGH','원이너프','159','0','6','22','15','491','312');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONEINAMILLION','원인어밀리언','70','1','2','0','102','22','131');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONEHUNNNIT','원허닛','107','7','1','4','23','70','300');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUI MAIS NON','위메농','91','1','10','9','5','102','469');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUI PANAME','위빠남','178','5','18','0','10','71','275');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('OUI,TT','위티','17','1','5','4','1','0','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ONENINENINEONE','일구구일','115','4','8','13','7','49','228');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PADAM VIEW','빠담뷰','68','0','0','0','1','5','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARS','빠흐','50','1','2','0','112','144','336');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PM 06:17','여섯시십칠분','53','1','4','0','1','7','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARABOOT','파라부트','29','0','30','5','2','196','814');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARACIA','파라시아','26','0','2','1','1','117','310');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARA JUMPERS','파라점퍼스','80','0','0','0','0','7','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARTIMENTO','파르티멘토','623','15','163','118','33','74,136','20,113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PASES','파세스','18','0','0','0','2','3','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PASOTTI','파소티','31','0','1','0','0','9','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PASCOROZEN','파스코로젠','37','1','0','0','1','16','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PASTEL CLOUD','파스텔 클라우드','25','0','2','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAARANMASK','파아란마스크','0','0','0','0','0','0','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAUSENBREAK','파우즈앤브레이크','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POUT','파우트','16','0','1','0','0','21','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POWERTOTHEPEOPLE','파워투더피플','62','0','0','0','0','107','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POSITIVE.V','파지티브브이','159','1','3','0','5','33','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARTS','파츠','10','3','13','40','10','162','810');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PACO RABANNE','파코라반','30','0','0','0','0','5','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARTY AFTER DARK','파티 에프터 다크','55','0','6','10','1','3','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PANDORA','판도라','390','0','2','0','0','26','315');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PANDORAFIT','판도라핏','51','0','3','0','1','110','242');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PALLADIUM','팔라디움','151','0','14','37','0','1,706','1,408');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PALACE SKATEBOARDS','팔라스 스케이트보드','27','0','41','1','0','3','1,693');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PALETTE ON','팔레트온','89','1','2','0','1','1','61');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POPSOCKET','팝소켓','119','0','1','0','0','25','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PARALYZE','패럴라이즈','33','1','1','0','3','13','62');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PATRICK','패트릭','25','0','2','0','0','14','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PANDORUMJEWELRY','팬도럼주얼리','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAN AM','팬암','46','1','5','34','4','124','230');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PANTONE TRAVEL','팬톤 트래블','44','0','0','0','1','6','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PUBLISH','퍼블리쉬','126','0','12','60','6','45','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PUBLIC ICON','퍼블릭아이콘','235','0','1','0','2','10,797','1,823');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PERSTEP','퍼스텝','665','12','4','1','2','21,627','9,537');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PACIFIC LEGEND','퍼시픽레전드','10','0','0','0','0','2','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PUNCHLINE','펀치라인','444','2','1','0','2','7,914','4,377');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEGADOR','페가도르','32','1','6','3','1','573','174');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PERENAIDO','페레나이도','4','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEMONT','페몬트','23','0','0','0','0','40','107');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAIRWEL','페어웰','34','1','2','0','0','7','113');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAIRS','페얼스','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAVEMENT','페이브먼트','133','5','29','36','13','2,220','1,258');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAPERISM','페이퍼리즘','309','0','57','53','8','31,327','9,489');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAINORPLEASURE','페인오어플레져','93','1','8','22','2','244','1,868');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEPPERSEASONING','페퍼시즈닝','70','1','2','1','1','2,364','477');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PENFIELD','펜필드','414','9','59','78','44','1,139','1,685');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PALETOT','펠토','158','0','1','0','0','969','352');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEMBROKE','펨브룩','20','1','0','2','0','8','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PETDERELLA PROJECT','펫데렐라 프로젝트','94','0','0','0','0','7','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PONERBROW','포너브로우','23','0','0','0','0','15','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PHONO PHONO','포노포노','26','0','2','2','2','55','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POSH-PROJECTS','포쉬프로젝트','140','0','7','0','3','294','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PHOS333','포스333','21','1','2','2','1','0','137');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POSTLUDE','포스트루드','301','0','14','4','1','117','209');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POSTX','포스트엑스','36','0','0','0','0','107','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POANE','포안','70','0','0','0','0','12','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POESIEDAME','포에지담','60','1','7','2','5','64','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POWIT','포윗','119','4','9','34','9','284','174');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POSZER','포저','16','1','0','0','5','0','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POSEGANCH','포즈간츠','21','6','9','83','10','150','525');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POCKET SHOT','포켓샷','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POCKETPISTOLS','포켓피스톨','50','0','0','0','0','23','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PHOTON','포톤','0','0','0','0','0','0','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POFF','포프','98','0','0','0','0','89','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAUL REVERE','폴 리비어','62','0','2','0','0','223','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POLAR','폴라','279','1','1','5','0','34','232');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POLO RALPH LAUREN','폴로 랄프 로렌','449','2','182','270','50','2,488','11,326');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POLLUTION','폴루션','28','1','1','2','1','3','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POLICE','폴리스','95','1','2','2','2','2','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAUL SMITH','폴스미스','163','0','3','1','0','7','132');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAULSBOUTIQUE','폴스부띠끄','121','2','4','0','0','161','528');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POLKA POLKA','폴카폴카','33','1','2','0','3','36','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAUL HAN','폴한','26','0','1','1','0','15','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('POLHAM','폴햄','694','5','39','7','15','4,069','2,832');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PAUL HUEMAN','폴휴먼','128','0','0','0','0','11','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PUMA','푸마','715','8','407','282','90','9,025','11,511');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRADA','프라다','1,802','0','37','19','0','21','738');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROUNS','프라운스','862','2','3','2','3','34','130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRATESI','프라테시','10','1','0','0','0','1','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Predator','프레데터','38','0','0','0','0','47','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRAIRIE','프레리','493','9','115','120','38','13,427','7,334');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRESTONS','프레스톤즈','64','0','0','0','0','686','524');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROSPECS','프로스펙스','244','3','99','165','38','9,085','1,005');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROJECT 624','프로젝트 624','454','6','5','2','3','1,137','563');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROJECT FOCE','프로젝트 포체','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROJECTVV','프로젝트브이브이','219','0','0','0','0','2','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROJECTM','프로젝트엠','407','1','4','6','1','471','246');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROJECTIN','프로젝트인','163','0','1','2','32','76','361');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRO-KEDS','프로케즈','31','0','3','0','1','15','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROCLUB','프로클럽','9','0','0','0','0','11','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROPPER','프로퍼','281','0','0','1','0','37','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PROOF','프루프','12','0','0','0','0','2','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRIMA PUNTA','프리마 푼타','129','1','0','0','0','383','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRIMAVERA','프리마베라','83','1','0','0','0','9','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRIMAUTER','프리마우터','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRIMA CLASSE','프리마클라쎄','113','0','0','0','0','1','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PREMIER','프리미어','394','0','0','0','0','229','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PREMIER X FLIPPER','프리미어 X 플리퍼','362','0','0','0','0','180','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PREMIER FITS','프리미어 피츠','0','0','0','0','0','0','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRIMITIVE','프리미티브','62','0','0','0','0','89','152');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PRETTEE','프리티','27','2','0','3','0','75','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLASTICPRODUCT','플라스틱프로덕트','19','0','0','0','0','1','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLAGE','플라주','19','0','0','0','0','5','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLASMA SPHERE','플라즈마 스페어','877','7','18','15','4','1,387','3,030');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLANET REMAKER','플래닛리메이커','58','0','1','2','1','272','106');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLANETSURF','플래닛서프','0','0','0','0','0','1','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLATEAU','플래토','276','1','3','2','2','1,322','368');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLAC','플랙','932','5','103','61','112','26,753','15,629');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLUGNPLAY','플러그앤플레이','80','0','4','0','1','8','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLUSSQUE','플러스에스큐','15','0','1','0','0','6','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLAYMONSTER','플레이몬스터','430','2','17','14','17','9,450','2,959');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLAYMONSTER EYEWEAR','플레이몬스터 아이웨어','95','0','4','0','0','111','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLACEMENT','플레이스먼트','16','1','4','2','1','520','141');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLAYIAN','플레이언','207','1','2','1','1','930','196');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLAYTEX','플레이텍스','75','0','0','0','0','22','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PFS','플레이페넥','65','1','14','3','3','125','283');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLAINWORKS','플레인웍스','8','1','1','92','2','27','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLEATSMAMA','플리츠마마','35','0','3','0','2','34','148');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PLHAMING','플하밍','22','0','0','0','0','6','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIGMILLION','피그밀리언','119','4','6','1','1','78','329');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIGANDHEN','피그앤헨','39','0','0','0','0','2','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIGLES','피글스','71','3','1','11','10','11','135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PINEA','피네아','12','0','0','0','0','2','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEACE MAKER','피스메이커','11','1','10','1','5','0','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIECE MAKER','피스메이커','396','13','41','53','32','9,444','3,750');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEACE BE SARAH','피스비사라','26','0','0','0','7','6','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIECE WORKER','피스워커','443','9','182','316','132','61,379','19,022');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PISCATOR','피스케이터','177','4','5','13','3','87','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PISTILO','피스틸로','26','0','0','0','0','1','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIANER','피아네르','89','0','0','4','0','16','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIANARI','피어나리','61','3','3','16','19','20','269');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIER4','피어포','226','0','18','38','0','626','478');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIERRE CARDIN','피에르가르뎅','25','0','0','1','0','20','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PS MERCI','피에스 메르시','32','0','1','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PSMARYJANE','피에스메리제인','475','8','48','97','4','10','230');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PF-FLYERS','피에프 플라이어스','61','0','7','1','0','677','535');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PMCO','피엠코','46','0','2','15','0','55','354');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('P.O.A','피오에이','144','0','1','1','0','148','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEACH&BANANA','피치앤바나나','52','0','0','0','0','315','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PICOMETER','피코미터','33','0','1','0','0','0','107');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PIQUADRO','피콰드로','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PETER BAG','피터백','10','0','0','0','0','51','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PETER JENSEN','피터젠슨','411','1','2','16','0','242','398');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEOPLE FOOTWEAR','피플풋웨어','129','0','26','9','0','743','300');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('P.P.P','피피피','92','2','3','1','12','328','363');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PINDEX','핀덱스','13','0','0','0','0','16','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PINBLACK','핀블랙','280','3','8','8','67','24','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PHILOCALY','필로컬리','187','6','8','27','2','94','358');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PHILIPPEMODEL','필립모델','0','0','0','0','0','0','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PHILIPP PLEIN','필립플레인','0','0','0','0','0','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('PEEPS','핍스','467','4','4','25','1','6,476','1,386');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUACI','콰시','71','2','2','0','1','23','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUIETIST','콰이어티스트','386','12','65','56','45','9,289','6,872');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QANTO DE LOCOS','콴토데로코스','190','0','1','0','0','24','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUA VINO','쿠아비노','43','1','2','0','1','7','185');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUARQOR','쿼르코어','57','0','2','1','27','733','478');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUALPACK','퀄팩','73','0','0','0','0','703','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUISQUE de nimes','퀴스케','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUIKSILVER','퀵실버','388','0','5','0','1','183','165');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QMILE','큐마일','143','2','0','0','0','19','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QV','큐브이','11','0','0','0','0','2','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QSLEATHER','큐스레더','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUI','큐이','73','1','0','1','0','3','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QCUMBERS','큐컴버스','62','2','1','0','5','271','162');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QT8','큐티에잇','1,089','9','36','94','26','3,289','1,817');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('QUAY EYEWARE','키 아이웨어','82','0','0','0','0','6','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RADINEO','라디네오','102','3','2','89','8','25','182');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RADIOS','라디오스','147','1','3','1','9','793','368');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAMOLIN','라모랭','61','3','27','39','8','4,401','404');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RA VIDE','라비드','64','3','3','4','8','5','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAVIIN','라빈','74','0','3','3','1','30','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RA_ON','라온','49','1','4','9','0','4','147');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROUNDLAB','라운드랩','14','0','3','0','1','24','252');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RIDER COMMUNE','라이더커뮨','50','0','0','0','0','9','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RISEBELOW','라이즈앤빌로우','15','1','2','1','2','1','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RIGHT ROUTE','라잇루트','156','2','1','0','20','137','195');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RATIO LAB','라치오 랩','0','0','0','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAPID DOMINANCE','라피드 도미넌스','166','0','0','0','0','23','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCKPSYCHO','락사이코','4','0','0','0','0','3','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROKSPRING','락스프링','78','0','0','0','0','1','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCK AMERICA','락아메리카','189','0','0','0','0','537','893');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCK'N FRESH','락앤프레쉬','13','0','0','0','0','36','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCKING AG','락킹에이지','168','0','2','0','0','36','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCKED GARAGE','락트개러지','183','0','0','0','0','2,069','1,116');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCKPORT','락포트','47','0','0','0','0','78','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCKFISH','락피쉬','216','3','10','4','8','182','198');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RALMODE','랄모드','56','3','0','0','3','1','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RENVERSE','랑베르세','35','0','3','10','47','104','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RASKAL','래스칼','214','4','4','1','1','605','1,575');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAT FINK','랫핑크','27','0','0','0','0','4','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUGGED HOUSE','러기드하우스','982','6','7','9','4','8,090','3,559');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUNNING HIGH','러닝하이','644','13','82','516','32','2,264','4,124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUBBERMAID','러버메이드','3','0','0','0','0','21','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUSSELL ATHLETIC','러셀 애슬레틱','150','0','31','6','4','490','436');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUSH OFF','러쉬오프','274','0','2','0','11','1,530','720');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUSTIC DIME','러스틱다임','36','0','1','0','0','1','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUCKUZ','러커즈','14','0','5','2','0','690','315');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROUGHNECK','러프넥','64','0','1','0','0','201','165');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROUGHSIDE','러프사이드','25','1','2','4','0','13','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUNDS','런디에스','309','0','5','3','28','1,237','1,306');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RENOMA','레노마','26','1','0','0','0','3','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RENOMASWIM','레노마수영복','275','2','2','0','0','112','144');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RED KAP','레드 캡','35','0','0','0','0','2','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REDMETEOR DESIGN','레드미티어 디자인','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REDWING','레드윙','277','0','3','33','0','685','2,452');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REDKROC','레드크록','22','1','1','0','1','2','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REBEL8','레벨8','827','0','0','0','0','78','368');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REVE DE AGNEAU','레브드앙뉴','156','1','0','1','4','104','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RATIONNEMENT','레숑멍트','27','1','2','0','0','314','129');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RHEA ROCKIN','레아라킨','35','3','2','12','7','20','130');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RARESOME','레어썸','96','0','0','0','0','50','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAIVE','레이브','198','5','45','42','219','273','1,505');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAVE UP','레이브업','140','0','13','37','1','16','294');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAVEN TEARS','레이븐 티얼스','204','0','4','0','0','27','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RACY','레이시','24','0','0','0','0','11','189');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAYSHISO','레이시소','55','2','5','12','11','149','491');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REIKU','레이쿠','106','2','1','7','1','365','323');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAYETOG','레이토그','56','1','12','67','1','3','315');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REINDEER','레인디어','171','0','6','2','0','4','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAINBOW WATCH','레인보우 와치','0','0','0','0','0','0','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAINBOW SANDALS','레인보우샌들','6','0','2','1','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REPETTO','레페토','0','0','0','0','0','0','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REXY','렉시','134','0','0','0','0','43','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REKKEN','렉켄','351','3','23','68','331','109','347');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RODD','로드','21','1','1','0','0','3','217');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROLAROLA','로라로라','962','17','131','51','90','4,642','11,802');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROMANSON','로만손','910','1','5','0','2','198','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROMANTICPIRATES','로맨틱 파이어리츠','542','7','28','0','13','32,804','12,109');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROMANTIC MOVE','로맨틱무브','679','1','14','7','2','1,583','867');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROMANTIC MOVE WOMAN','로맨틱무브 우먼','121','0','6','0','0','69','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROMANTIC CROWN','로맨틱크라운','1,184','30','338','280','62','71,062','65,725');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROBERT J.C HAWAII','로버트제이씨 하와이','8','1','0','0','0','56','206');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROBERTA DI CAMERINO','로베르타 디 카메리노','2','0','0','0','0','4','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCIETY','로사이어티','17','1','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROSA.K','로사케이','24','1','5','0','0','2','236');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROSHOEMAN','로슈맨','513','0','1','0','0','58','122');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROTHCO','로스코','574','0','25','44','3','7,175','2,720');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCCI ROCCI','로씨로씨','16','1','6','41','5','18','303');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROIDESROIS','로아드로아','343','4','12','94','16','5,687','1,673');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROYALLIFE','로얄라이프','1,302','12','77','127','58','20,502','6,542');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROYAL PIECE','로얄피스','56','0','0','0','0','24','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROYALHAWAIIANCREATIONS','로얄하와이안크리에이션스','88','2','1','0','1','124','215');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROAR','로어','66','2','2','6','0','38','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAW TO RAW','로우 투 로우','315','0','1','0','0','86','193');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RAWROW','로우로우','184','1','78','12','17','2,376','2,370');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROWTIQUE','로우티크','14','0','0','0','0','22','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROIDETER','로이데테르','30','0','0','0','0','10','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROYROYSEOUL','로이로이서울','35','0','2','2','10','18','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROYSCA','로이스카','46','0','0','0','0','332','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROI'AL','로이알','15','0','0','0','0','5','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROY&RAY','로이앤레이','1','0','0','0','0','952','613');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROILROIL','로일로일','25','1','4','3','2','331','138');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROSIER','로지에','115','6','28','6','43','161','399');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROCKET X LUNCH','로켓런치','703','9','35','42','81','621','1,996');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROXY','록시','236','0','2','0','0','20','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RONRON','론론','145','4','8','11','1','471','768');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROLLIENATION','롤리네이션','17','0','0','4','1','3','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROLLINGSTUDIOS','롤링스튜디오','25','1','2','0','8','19','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUTHLESS','루스리스','67','0','5','0','3','109','109');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUONINE','루오나인','51','4','1','24','4','73','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROUGE ET LE NOIR','루즈엣르누와','40','1','1','0','1','42','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROOTOTE','루토트','12','0','2','0','0','28','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROUTE1','루트원','40','1','2','3','11','3','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROOTAGE','루티지','21','1','5','0','2','2,560','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ROOPRETELCHAM','루프리텔캄','14','0','0','0','0','11','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RUHM','루흠','904','7','71','105','15','1,995','3,112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RYUL+WAI','률앤와이','502','8','21','19','46','85','587');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REVER&CO','르버앤코','454','0','0','3','5','1,474','331');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REVOIRSIS','르브아시스','29','0','2','0','1','0','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RECLOW','리끌로우','923','4','34','7','3','3,045','801');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RENINE','리나인','131','3','3','27','19','808','203');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REED PAGES','리드페이지','0','0','0','0','0','0','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RIMOU','리모우','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('R ZIOZIA','리버스 지오지아','704','4','22','2','11','1,387','499');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REEBOK','리복','764','3','521','443','115','20,952','15,352');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REBLANK','리블랭크','73','0','0','0','0','42','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RE:VIN','리빈','23','0','0','0','0','6','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RESELECT','리셀렉트','56','0','0','0','0','132','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RESHOEVN8R','리슈브네이터','22','0','2','0','0','353','90');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RESPECT','리스펙트','343','9','8','52','13','2,921','2,065');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REALIZATION','리얼라이제이션','55','2','2','0','6','179','103');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REALEESM','리얼리즘','66','0','4','2','5','19','106');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REAL CONTENTS','리얼컨텐츠','65','0','1','0','0','723','290');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RIETI','리에티','131','0','3','0','0','1,951','496');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RIOKAIRYU','리오카이류','67','0','0','0','0','544','574');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REORG','리올그','385','9','68','152','24','5,387','3,333');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RWDER','리와인더','59','0','1','0','6','81','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RE RHEE','리이','49','1','7','70','8','13','204');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RITA MONICA','리타모니카','106','0','0','0','0','17','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REFRAME','리프레임','13','1','2','20','3','2','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REPRE','리프리','54','2','13','35','2','17','382');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REFLYPERKY','리플라이퍼키','124','5','10','57','8','2,285','911');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REPLAY','리플레이','121','0','0','0','0','3','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('REPLAY CONTAINER','리플레이컨테이너','198','3','15','6','12','14,994','11,270');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('rinse&co','린스앤코','13','2','3','4','0','681','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RELIZMPRODUCT','릴리즘프로덕트','65','0','0','5','0','134','398');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RIPNDIP','립앤딥','80','1','0','0','0','164','643');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RIPCURL','립컬','0','0','0','0','0','0','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RDVZ','알디브이제트','153','6','1','10','67','360','642');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RDC','알디씨','42','2','3','0','4','88','228');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('R.SHEMISTE','알쉬미스트','60','3','18','38','40','165','846');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RCKT','알씨케이티','52','0','2','0','0','82','149');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RS9seoul','알에스나인서울','63','1','5','8','1','2','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RSVP','알에스브이피','106','6','13','25','55','127','320');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RNOT','알엔오티','114','0','1','0','2','21','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('RYOO','알와이오오','19','1','0','0','1','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SARTOR RESARTUS','사르토르 리사르투스','71','1','4','3','0','671','184');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SABE','사베','41','1','3','0','1','46','222');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOUNDS BMUET','사운즈 비뮈에트','66','0','0','0','0','22','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAII','사이','70','0','1','50','0','2','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SILENT SOCIETY','사일런트 소사이어티','64','0','0','0','0','26','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SACAI','사카이','2','0','9','1','0','0','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SATORISAN','사토리산','63','0','1','4','0','80','403');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SATYA','사티아','25','0','0','0','0','56','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAPHIR','사피르','50','0','0','0','0','312','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOCKS THE LANGUAGE','삭스더랭귀지','474','0','1','0','0','190','183');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOXX SYNDROME','삭스신드롬','320','0','9','0','0','1,180','500');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOCKS APPEAL','삭스어필','614','0','6','0','0','644','724');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOCKSTAZ','삭스타즈','21','0','1','0','0','2,638','325');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOXFIT','삭스핏','74','1','1','0','1','32','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SANTA CRUZ','산타크루즈','57','1','2','1','1','11','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALRANG','살랑','144','0','0','0','0','168','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALOMON','살로몬','81','0','8','2','0','4','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALON DE YOHN','살롱 드 욘','461','2','35','55','24','192','1,448');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALON DE SEOUL','살롱드서울','249','5','11','9','66','348','1,058');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALVATOS','살바토스','19','0','1','4','0','58','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAMSUNG ELECTRONICS','삼성전자','37','0','21','0','5','1,992','846');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SATTCHI','삿치','69','0','7','16','7','0','19');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SANGSANG POWER STATION','상상발전소','1,494','0','3','0','0','437','1,029');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAESOCKS','새싹스','63','0','0','0','0','124','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAC','색','102','5','17','68','12','909','1,401');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SANDPIPER','샌드파이퍼','143','8','2','0','3','246','261');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALAD BOWLS','샐러드볼','698','10','94','311','70','2,570','6,391');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALLY ARIEL','샐리에리얼','20','0','0','0','0','1','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAINT LAURENT','생로랑','666','0','17','10','0','28','980');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHARON6','샤론6','105','0','1','0','2','268','248');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHAKA','샤카','148','2','64','194','14','688','409');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHAKA WEAR','샤카웨어','22','0','0','0','0','235','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SURREALBUTNICE UNISEX','서리얼벗나이스 유니섹스','55','1','4','3','0','92','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEOULAPPAREL','서울어패럴','0','0','0','0','0','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPPORTLIGHT','서포트라이트','242','3','1','0','5','5','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEOKWOON YOON','석운 윤','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUNDAYLOUNGE','선데이라운지','38','1','1','0','0','25','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUNDAYOFFCLUB','선데이오프클럽','108','4','0','0','0','102','472');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUNSKI','선스키','22','0','1','0','0','2','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SONS OF ANARCHY','선즈오브애너키','37','0','0','0','0','4','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SULLY WONG','설리웡','22','0','0','0','0','33','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUB','섭','71','1','1','0','0','15','141');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCENUERDO','세누에르도','51','2','2','0','0','71','155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SATURDAY ELEVEN','세러데이일레븐','23','1','1','5','5','75','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SERIGRAPHIE','세리그라피','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SELIVER','세리버','24','2','0','3','4','6','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEMICODE','세미코드','27','0','5','0','1','33','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEMICOLON EYEWEAR','세미콜론 아이웨어','21','2','14','30','42','739','384');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEVENDROPS','세븐드롭스','13','1','1','0','0','0','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEVENSELAH','세븐셀라','197','0','58','16','19','18,413','5,295');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEVENTEENTH','세븐틴스','432','0','0','0','0','544','183');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAVAGE','세비지','17','0','0','0','0','48','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEIRUS','세이러스','13','0','0','0','0','5','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAMO ONDOH','세이모 온도','446','2','19','18','69','820','1,188');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEIKO','세이코','106','0','2','0','0','15','326');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAFE HOUSE','세이프하우스','20','1','0','0','2','65','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAINT GALLERY','세인트 갤러리','85','0','0','0','0','209','158');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAINTROBE','세인트로브','0','0','0','0','0','0','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAINT SHOW','세인트쇼','41','0','1','0','6','94','61');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAINT SCOTT','세인트스코트','103','1','7','11','0','26','209');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ST.SCOTT LONDON','세인트스코트런던','298','0','0','0','0','38','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAINT JAMES','세인트제임스','51','0','0','0','0','99','937');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAINTPAIN','세인트페인','903','11','217','298','119','28,503','15,104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAME FORTS','세임폴츠','49','2','1','1','3','151','267');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEJINIST','세지니스트','19','1','1','0','12','0','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SECONNATION','세컨네이션','25','2','1','0','3','124','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SECOND CORNER','세컨드 코너','331','0','3','0','1','264','760');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SECOND UNIQUE NAME','세컨드유니크네임','319','0','1','0','0','711','488');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEKANSKEEN','세컨스킨','397','0','12','13','6','169','239');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEC','세크','39','0','0','0','0','4','33');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEKHMET','세크메트','21','0','1','0','1','0','173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEC BY RIGOON','섹 바이 리군','225','1','5','0','5','40','244');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEXTO','섹스토','1,175','2','5','322','3','6,727','1,285');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEXTO' N.XX LINE','섹스토넘버xx라인','321','0','4','0','0','158','131');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEXY CHAMPION','섹시챔피언','88','1','4','2','7','1,287','220');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SENSELECT','센셀렉트','139','0','3','0','13','9','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SELLERIASTAMERRA','셀러리아 스타메라','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SELFISH','셀피쉬','115','2','4','0','2','363','224');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEBS','셉스','36','1','2','0','0','115','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEPTEMBER5','셉텐벌5','219','0','1','0','2','1,920','409');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEPTEMBER29','셉템버29','60','1','1','3','0','228','280');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SETUP-EXE','셋업이엑스이','78','0','0','0','0','50','340');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHIRTER','셔터','35','1','1','0','0','28','625');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHUTTER','셔터','275','0','6','0','0','1,710','612');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEANMAKESCLOTH','션메익스클로스','681','3','27','18','6','557','1,899');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHEERK','셜크','35','2','1','0','1','28','139');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOGONSOGON','소곤소곤','164','0','10','0','0','431','841');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOGNAREBY','소냐레바이','133','0','0','0','0','35','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SONOVESTO','소노베스토','0','0','0','0','0','0','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SONIAVIA','소니아비아','33','1','5','4','0','1','80');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SODAMON','소다몬','32','0','0','0','0','5','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOVERMENT','소버먼트','229','10','38','3','11','34,128','13,027');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOSOLIFE','소소라이프','27','4','9','39','2','462','191');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOWERIUM','소어리움','19','4','2','8','1','25','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOUL ASSASINS','소울어세신','26','0','0','0','0','1','43');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEWINGBOUNDARIES','소윙바운더리스','85','6','22','17','6','117','628');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOAQ','소크','18','0','1','0','1','23','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOTT','소트','18','1','1','9','2','23','516');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOFRESHANDCLEAN','소프레쉬앤드클린','6','0','0','0','0','6','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOFTUR','소프터','31','1','2','0','2','2','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOPHY & TAYLOR','소피앤테일러','132','0','3','0','0','1','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOLACE BY DENNIS','솔라스 바이 데니스','43','1','2','0','0','6','110');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOLOVAIR','솔로베어','11','0','0','0','0','3','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SORTIE','솔티','137','0','4','0','0','67','139');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHOVEOFF','쇼브오프','126','2','9','119','57','5,457','1,010');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHOJIAMI','쇼지아미','18','0','0','0','5','26','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Schott NYC','쇼트 뉴욕','47','0','5','0','0','733','627');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUARE','수아레','413','11','29','54','84','2,224','1,143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUADD','수애드','35','1','0','0','0','32','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUICIDALTENDENCIES','수어사이덜 텐덴시','23','0','1','0','0','8','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUICIDAL HIKIKOMORI','수어사이둘 히키코모리','22','1','1','9','0','23','297');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUENOA','수에노아','0','0','0','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUIGENERIC','수이제네릭','0','0','0','0','0','0','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUICOKE','수이코크','151','1','29','68','2','1,043','514');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUITSUIT','수잇수잇','106','0','2','0','0','11','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUITABLE','수트에이블','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERGA','수페르가','125','2','11','5','10','1,902','2,190');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOOHYANG','수향','18','0','8','0','1','3','290');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SSUM','숨','20','0','0','0','0','21','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOUP','숲','120','0','0','0','0','20','120');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUGAPOINT','슈가포인트','1,290','0','3','0','0','273','172');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCHNEIDER','슈나이더','89','0','2','3','0','16','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLAMODE','슈라모드','118','0','0','0','0','361','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUBET','슈벳','369','0','18','0','1','1,311','742');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHOBONYATA','슈보니에타','6','0','3','0','0','25','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUATELIER','슈아뜰리에','0','0','0','0','0','0','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHOECUS','슈커스','28','0','0','0','0','11','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUECOMMA BONNIE','슈콤마보니','33','2','3','0','1','2','342');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERLIT','슈퍼릿','100','0','0','0','2','23','261');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERINC','슈퍼링크','865','0','4','0','0','41','67');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERMOON','슈퍼문','42','1','2','3','2','1','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPER BY RETROSUPERFUTURE','슈퍼바이레트로슈퍼퓨처','71','0','1','0','0','0','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERBASIC','슈퍼베이직','20','0','0','0','0','6,884','247');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERVISION','슈퍼비젼','228','0','1','0','0','3,610','748');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERCROC','슈퍼크록','232','0','0','0','0','531','207');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPERCROC ACTION','슈퍼크록 액션','35','0','0','0','0','44','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHOOPEN','슈펜','724','2','61','50','15','17,546','3,845');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUPREME','슈프림','355','0','152','127','0','147','10,095');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SNOUT','스나웃','75','1','0','2','1','3,317','221');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SNACKCULTURE','스낵컬쳐','95','2','0','18','2','117','200');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SNOWMOON','스노우문','78','0','0','0','0','16','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SNOW BISON','스노우바이슨','50','0','3','4','0','73','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SNOOZY','스누지','56','0','0','0','0','31','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SNOOPY','스누피','2','0','0','0','0','1','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SMAS','스마스','86','0','0','1','0','3','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SMILEY','스마일리','1','0','1','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SMAASH STUDIO','스매쉬스튜디오','70','1','1','0','0','23','345');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SMOKINGLIFE','스모킹라이프','15','0','0','0','0','2','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SMITH','스미스','42','0','0','6','0','6','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SMITH ARMOR','스미스아머','341','8','17','58','17','407','865');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWYNES','스와인즈','74','0','0','0','0','570','520');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWALLOWTALE','스왈로테일','78','8','2','61','18','129','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWAGGER','스웨거','26','0','1','0','2','252','445');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWEAR','스웨어','101','0','0','0','0','60','85');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWELLMOB','스웰맙','800','1','9','26','2','1,533','1,983');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWIB','스위브','1,061','13','54','76','59','5,266','2,967');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWISS MILITARY CARRIER TRAVEL','스위스 밀리터리 캐리어 트래블','149','0','4','0','1','98','54');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWISS MILITARY HANOWA','스위스 밀리터리 하노와','56','0','0','2','0','2','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWEETCH','스위치','62','2','3','1','1','296','273');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWITFISH','스윗피쉬','37','2','23','45','8','592','858');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SKAGEN','스카겐','101','0','0','0','0','2','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCALETTOBLACK','스칼렛또블랙','101','2','2','1','5','667','329');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SKAMP','스캠프','42','0','0','0','0','488','104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SKULLCANDY','스컬캔디','34','0','5','0','0','64','80');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCULPTOR','스컬프터','1,187','11','328','812','117','32,524','31,615');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SKULLPIG','스컬피그','435','0','8','11','7','912','317');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCHERZANDO','스케르잔도','30','0','3','5','0','6','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SKATERSOCKS','스케이터삭스','1','0','0','0','0','9','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SKONO','스코노','248','1','7','9','14','458','561');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCORPION','스콜피온','121','1','1','0','23','8','186');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCUDERIA FERRARI','스쿠데리아 페라리','15','0','1','0','0','271','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SKRAP','스크랩','31','0','8','9','1','46','82');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STAR.B','스타비','16','0','0','1','8','27','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STYLE PLAN','스타일플랜','68','1','2','21','0','479','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STARTER','스타터','48','6','28','28','8','1,122','1,688');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STATIC FLOW','스태틱플로우','5','0','0','0','0','1','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STANDARD CURVE','스탠다드커브','224','3','13','18','16','3,255','1,910');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STAND OUT STORE','스탠드 아웃 스토어','16','1','1','0','0','13','197');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STANDUP','스탠드업','151','0','1','4','0','185','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STANRAY','스탠레이','62','3','3','2','0','189','386');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STANLEYKUBRICK','스탠리큐브릭','73','0','2','4','0','21','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STAN ARD','스탠아드','218','3','3','1','29','150','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STUNT','스턴트','170','1','0','3','5','950','445');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STERLINGWORTH','스털링워스','184','1','0','0','101','196','354');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STUMP STUDIO','스텀프 스튜디오','61','0','1','0','1','61','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEADY EVERY WEAR','스테디 에브리웨어','61','4','5','6','3','490','533');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEADY COMMA','스테디콤마','136','6','12','32','49','465','229');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEADEPOD','스테디포드','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEREO VINYLS','스테레오 바이널즈','175','16','118','104','113','10,474','6,344');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STARE','스테어','156','5','4','2','54','771','535');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STAY WITH ME','스테이 위드 미','50','0','0','0','3','10','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STAY GOLD','스테이골드','46','0','2','0','0','3','93');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STAGE NAME','스테이지 네임','55','7','19','382','14','599','555');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STELLAREALE','스텔라레알레','15','1','3','0','0','979','302');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STELLA MCCARTNEY','스텔라맥카트니','0','0','0','0','0','0','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STELLA BE','스텔라비','76','1','3','4','5','614','271');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STAFFONLY','스텝온리','241','6','21','13','17','5,915','7,161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STOE','스토','24','0','2','0','0','14','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STONY STRIDE','스토니 스트라이드','277','5','16','65','10','516','566');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STORYUS','스토리어스','34','1','2','0','1','7','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STOCKHOLM SYNDROME','스톡홀름 신드롬','708','0','1','31','3','410','775');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STONE ISLAND','스톤아일랜드','347','0','23','20','0','49','2,786');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STUSSY','스투시','2,042','0','30','75','0','2,902','24,242');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STUDIO SELMYEOT','스튜디오 슬몃','24','0','2','0','1','1','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STUDIO.G','스튜디오 지','123','1','2','0','1','5','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STUDIO TOMBOY','스튜디오 톰보이','153','0','6','0','0','10','918');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STUDIO UZU','스튜디오우주','23','1','3','1','0','4','317');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STRIKE','스트라이크','1,047','1','0','1','2','609','351');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STRATIC','스트라틱','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STRETCH ANGELS','스트레치 엔젤스','416','8','77','237','112','654','1,367');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STRONGSTRAW','스트롱스트로우','33','2','2','45','1','49','189');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STREET STANDARD','스트리트 스탠다드','47','1','2','4','1','29','202');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STREET FOOT','스트릿풋','8','0','0','0','0','10','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STIGMA','스티그마','1,586','10','19','86','1','4,037','3,639');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEALER','스틸러','241','1','11','0','33','24','102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEAL MONSTER','스틸몬스터','81','0','1','0','0','78','56');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEALEARTH','스틸어스','21','1','1','0','1','4','109');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STEEL WHEELS','스틸휠즈','339','3','1','2','2','883','1,068');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STING925','스팅925','78','0','3','1','0','30','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPAO','스파오','183','14','75','11','16','11,063','6,173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPYPAUL','스파이폴','58','2','3','35','5','199','132');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPUNKY','스펑키','192','10','37','121','11','272','941');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPERONE','스페로네','253','8','24','40','32','1,474','890');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPECIAL GUEST','스페셜게스트','81','0','0','0','0','28','58');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPAVER','스페이버','112','0','0','0','0','81','105');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPACE AGE','스페이스에이지','31','2','1','1','0','363','486');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPETTRO','스페트로','234','0','1','0','0','3','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPORTEAR','스포트이어','5','0','0','0','0','4','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPRIS','스프리스','29','3','7','0','0','163','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPITFIRE','스핏파이어','92','0','1','0','0','13','71');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLANT','슬랜트','0','0','0','0','0','0','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLEY','슬레이','95','0','0','1','1','101','132');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLEAZY CORNER','슬레지코너','182','3','11','14','13','828','1,159');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOWMOVE','슬로우무브','63','0','1','0','0','13','57');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOWSERVICE','슬로우서비스','110','1','3','0','0','360','395');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOW ACID','슬로우애시드','356','10','140','148','57','24,466','12,161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOWATTENTION','슬로우어텐션','104','2','6','7','30','29','117');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOWUNIVERSE','슬로우유니버스','78','1','4','1','4','131','172');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOWPOKE','슬로우포크','220','3','4','0','0','191','347');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOW HUMAN','슬로우휴먼','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLOWEING','슬로윙','63','1','5','0','2','633','322');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SLEEPYSLIP','슬리피슬립','201','9','28','27','31','2,666','852');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIGNAP','시그냅','84','0','2','20','0','78','169');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIGNATURE','시그니처','607','10','94','383','51','18,547','4,542');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIGNIFICANT','시그니피컨트','30','1','0','0','0','12','173');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCENERY','시너리','31','0','0','0','0','33','161');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SINOON','시눈','119','3','10','3','4','150','1,300');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHETHISCOMMA','시디스콤마','313','7','60','209','143','5,465','3,634');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEALANDGEAR','시랜드기어','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHIROI NEKO','시로이네코','242','0','0','0','0','90','270');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIERO','시에로','100','4','23','106','30','1,179','1,044');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIERO COSMETIC','시에로 코스메틱','66','1','9','0','1','29','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEIZETHEDAY','시즈더데이','101','3','3','1','9','222','276');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIXSOX','식스삭스','4','1','2','0','0','4','164');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIXTY SEVEN','식스티 세븐','37','0','0','0','0','3','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SINSNEAKERS','신스니커즈','3','0','0','0','0','9','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SHINJEO','신저','0','0','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SYMBOLER','심볼러','18','0','0','0','0','9','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIMPLAIN','심플레인','80','1','3','13','2','12','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SINCLAIR','싱클레어','0','0','0','0','0','0','48');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAKK','싹','28','1','3','0','0','1','66');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAMSONITE','쌤소나이트','247','1','1','1','0','17','204');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SAMSONITE RED','쌤소나이트 레드','310','2','4','0','1','106','248');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SER','써','364','0','3','1','0','175','618');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEARCH410','써치410','456','8','17','12','27','1,620','1,446');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SUNDAY SOMEWHERE','썬데이썸웨어','78','0','1','0','3','4','52');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOMETHING ACOUSTIC','썸띵어쿠스틱','179','0','5','9','0','878','458');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SSERPE','쎄르페','35','0','0','0','12','10','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SETSETSET','쎄쎄쎄','170','1','6','0','0','9','143');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCENE','쎈느','13','0','0','0','0','8','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('sorry, too much love','쏘리, 투 머치 러브','306','2','11','6','35','8','276');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEW CLASSIC','쏘우클래식','440','11','10','7','10','1,840','1,589');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SSOC','쏙','23','0','1','0','0','1','100');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SOLELOOP','쏠룹','242','1','2','0','1','9','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SISNBRO','씨스앤브로','0','0','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEESAW','씨쏘','85','0','1','0','0','399','412');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SEANLIP','씨앤립','86','2','1','0','14','113','234');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SIWY','씨위','154','0','0','0','0','4','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('S.T.DUPONT','에스.티.듀퐁','100','2','6','9','2','24','183');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SWSW','에스더블유에스더블유','66','0','3','1','3','121','149');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('S'LOW','에스로우','101','0','2','0','1','17','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SPOCHE','에스뽀쉬','132','0','0','0','0','30','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SCS','에스씨에스','164','8','19','75','2','157','373');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('S.I.C','에스아이씨','17','1','1','3','0','44','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SSRL','에스에스알엘','118','3','10','65','39','957','697');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SSY','에스에스와이','289','6','19','51','22','3,960','2,291');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SSQR','에스에스큐알','153','1','0','1','0','8','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SMCL','에스엠씨엘','30','0','0','0','0','29','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SJYP','에스제이와이피','376','1','16','15','2','48','743');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('STU','에스티유','39','0','0','7','1','208','499');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('SALVATORE FERRAGAMO','페라가모','791','0','3','0','0','12','174');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE GREATEST','그레이티스트','319','12','23','80','49','843','1,104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE NORTH FACE','노스페이스','846','2','82','56','7','8,455','6,792');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('the lutin','더 루틴','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE MADNESS','더 매드니스','349','4','2','0','3','548','809');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE VERY THING','더 베리 띵','193','3','3','9','20','108','139');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE STUDIO K','더 스튜디오 케이','227','11','40','167','110','72','599');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE QUIET LIFE','더 콰이엇 라이프','30','0','1','0','0','3','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE CLOTHO','더 클로토','25','0','0','0','0','13','32');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE T-SHIRT MUSEUM','더 티셔츠 뮤지엄','217','6','11','2','2','4,730','3,135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE PERFECT HAND','더 퍼펙트 핸드','56','0','0','0','0','6','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THEKNITCOMPANY','더니트컴퍼니','123','1','9','0','8','1,103','2,557');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THEDEF','더데프','43','1','2','0','0','38','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THEDOSI','더도시','52','0','0','0','0','54','43');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE LOGUE','더로그','90','0','0','0','0','442','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THELOOM','더룸','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE VERYOUNG','더베리영','28','0','0','0','0','2','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE BLACK SWAN','더블랙스완','72','0','2','0','0','5','12');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE SALLYS LAW','더샐리스로우','332','0','0','0','1','50','99');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE CENTAUR','더센토르','73','0','2','2','0','9','114');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THESOGA','더소가','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE SHOW'S NOT OVER','더쇼즈낫오버','77','0','0','9','0','376','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THESTORI','더스토리','717','6','79','346','70','19,878','5,344');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE SPRING HOME','더스프링홈','146','1','1','0','0','88','218');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE SLOWING LOT','더슬로잉랏','23','0','0','0','0','2','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE ASHLYNN','더애쉴린','20','0','2','0','1','0','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE HOMME LOOSE','더옴므루즈','37','3','7','0','2','69','224');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THEWANDER','더완더','172','6','11','25','1','363','1,248');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THEKLAXON','더클랙슨','102','0','8','6','0','164','429');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THECHLIA','더클리아','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THETINT','더틴트','259','3','10','24','2','35','255');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THEFRECCIA','더프레치아','75','0','0','0','0','34','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE HUNDREDS','더헌드레드','236','0','5','0','0','140','402');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THENCE','덴스','194','4','3','4','2','434','1,898');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THAT'S IT','뎃츠잇','106','3','10','18','34','1,171','536');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THISRESPECT','디스리스펙','10','1','2','21','5','56','319');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THISISNEVERTHAT','디스이즈네버댓','2,418','12','491','237','71','131,379','103,702');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THIS IS . H','디스이즈에이치','15','0','1','4','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE EARTH','디얼스','537','5','28','16','7','2,902','892');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE ORA','디오라','156','2','8','15','2','30','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TTANGBYEOL MEDLEY','땅별메들리','36','0','0','0','0','10','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THREADS','뜨레즈','100','2','6','12','0','449','140');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THI:M','띔','48','2','13','47','3','4','72');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THINCKER','띵커','99','0','2','0','0','3,062','597');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE ROYAL 'WE','로얄위','536','3','2','0','6','2,625','1,048');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THIRD','서드','206','0','3','0','0','479','409');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THIRDWEAVE','써드위브','181','1','9','22','11','3,119','1,199');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THIRTEEN','써틴','73','0','1','0','0','56','123');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THOROGOOD','쏘로굿','24','1','24','49','6','5,168','3,923');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THRASHER','쓰레셔','702','0','25','66','6','5,217','10,838');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THREE KNOCKS','쓰리노크스','123','6','21','17','6','356','335');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THREE TO EIGHTY','쓰리투에이티','56','2','7','2','2','27','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE-ABON','에이본','1,452','0','4','2','1','1,218','666');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THEWANKSERS','웽커스','59','4','8','3','5','61','185');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TWENTY SIX . SEVEN','이십육점칠','14','1','4','6','0','135','88');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE INTERNATIIIONAL','인터내셔널','53','2','0','0','4','30','84');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TARGETTO','타게토','605','12','92','230','250','4,680','6,193');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOMMY JEANS','타미진스','644','4','55','31','16','3,747','8,425');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOMMY HILFIGER','타미힐피거','310','1','35','41','6','2,749','8,863');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAMIM STUDIO','타밈스튜디오','9','0','0','0','0','1','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIMEX','타이맥스','212','0','5','0','0','197','370');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIEMEYOUNG','타이미영','27','1','3','0','1','2','77');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIGHT.INSPIRED','타이트인스파이어드','20','0','0','0','0','103','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIMESLIP','타임슬립','79','1','0','0','2','22','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TACHI','타치','15','0','0','0','0','51','52');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TATASOCKS','타타삭스','12','0','0','0','0','16','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TATRAS','타트라스','55','0','4','6','1','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TACS','탁스','16','0','0','0','0','3','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TACTFUL KIOSK','탁풀키오스크','239','2','4','9','4','12','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TANTAN','탄탄','72','1','7','32','2','152','222');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOMOC','탐탁','125','0','0','0','0','45','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOPTEN','탑텐','2,767','5','114','23','14','7,964','2,578');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAEWOO','태우','14','1','1','0','5','21','224');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TACKLEESEARCH','태클리서치','131','0','1','1','0','62','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TENDER LAB','탠더랩','78','2','20','43','9','1,395','524');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TERG','터그','17','0','2','0','0','32','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOUCH GROUND','터치그라운드','105','0','1','1','0','99','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TENER','테네르','45','1','1','1','13','34','213');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TENUE','테뉴','61','0','0','0','4','37','158');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TED BAKER','테드 베이커','0','0','0','0','0','0','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TERRANATION','테라네이션','11','0','0','0','0','4','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TERRYWOOD','테리우드','60','0','0','0','0','37','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEVA','테바','184','0','72','99','6','10,656','2,422');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TABLETALK','테이블토크','301','0','3','0','1','323','135');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TASTE OF ESSENCE','테이스트 오브 에센스','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAZE','테이즈','363','2','3','0','2','17','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAKUS','테이커스','60','0','0','0','0','167','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAKEWHATYOUNEED','테이크 왓 유니드','11','0','0','0','0','3','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAKEASY','테이크이지','273','5','26','37','25','12,998','3,205');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAILOR STUDIO','테일러 스튜디오','145','7','7','0','3','1,869','3,017');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TECHNE','테크네','60','0','0','0','0','15','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TECHFLAVOR','테크플레이버','98','4','11','71','18','4,249','1,997');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TENMORE','텐모어','251','7','18','62','9','405','267');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TENBLADE','텐블레이드','215','8','20','12','14','5,463','1,631');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TENSOR','텐서','0','0','0','0','0','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEN POINTS','텐포인츠','115','0','2','0','0','9','82');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TELIC','텔릭','8','0','1','0','0','17','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEMBEA','템베아','0','0','0','0','0','0','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TONYMOLY','토니모리','82','0','2','0','1','11','147');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TONYWACK','토니웩','194','3','2','5','28','818','2,770');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TORY BURCH','토리버치','753','0','0','5','0','4','330');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THOMAS VAILEY','토마스 베일리','528','0','1','0','0','871','338');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOBOGGAN','토바간','24','1','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TAW&TOE','토앤토','8','0','1','0','0','33','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOI','토이','121','3','1','1','1','53','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOD'S','토즈','102','0','1','1','0','0','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOTTENHAM APPAREL','토트넘 어패럴','21','1','1','0','1','17','643');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOFFEE','토피','141','4','9','10','4','16,746','3,601');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOFIT','토핏','0','0','0','0','0','0','43');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THOM BROWNE','톰브라운','308','0','5','2','0','0','537');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOMTOMORROW','톰투머로우','10','1','1','20','0','27','163');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOM FORD','톰포드','0','0','0','0','0','0','26');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TUGU','투구','37','2','0','0','16','3','17');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TWONIQUE','투니크','73','0','2','4','0','30','128');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TUMI','투미','142','0','2','1','0','2','74');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOWBINARE','투빛나래','54','0','0','0','0','11','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TUSTUS','투스투스','87','0','1','0','0','52','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOAT','투앳','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TWELVESOME','투엘브썸','63','1','4','0','0','1','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TUO','투오','60','1','2','5','0','8','28');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THULE','툴레','171','0','2','0','0','30','97');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TUFEIS','튜페이스','89','0','8','14','0','4','37');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRAVS','트라비스','55','2','3','0','2','220','174');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRY','트라이','86','0','0','0','0','260','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRIDENT CASE','트라이덴트 케이스','36','0','0','0','0','1','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRITONE','트라이톤','43','0','0','0','0','3','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRYTOTALK','트라이투톡','822','5','32','110','4','1,561','1,037');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRAVEL','트래블','110','14','71','49','26','25,226','7,999');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRAVEL237','트래블237','14','0','0','0','0','7','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRAVELMATE','트래블메이트','97','4','7','4','1','54','157');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRAVELON','트래블온','6','0','0','0','0','1','6');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRUNK PROJECT','트렁크프로젝트','222','13','27','53','279','964','2,240');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TREAJU','트레쥬','86','0','10','0','0','107','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRETORN','트레통','24','0','1','0','0','31','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TREND FACTORY','트렌드팩토리','77','0','1','0','0','4','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TROIS POINT','트로이스포인트','51','0','0','0','0','6','19');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TROPICS','트로픽스','19','1','0','0','0','2','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRUEPENNY','트루페니','14','1','0','0','1','25','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRIWA','트리바','29','0','3','0','1','2','401');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRISHA','트리샤','68','0','1','0','0','37','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRIOP','트리옵','13','1','1','1','0','3','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRICKER'S','트리커스','4','0','1','0','0','5','41');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('triplePAM','트리플팸','113','0','0','0','0','118','98');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRIPPIN CLOTHES','트리핀 클로즈','29','0','0','0','14','16','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRIPPIN CELL','트리핀셀','138','2','3','0','0','137','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRILLION','트릴리온','61','4','10','28','16','2,922','1,339');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRIP LE SENS','트립르센스','553','13','38','111','82','3,798','3,233');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRIPSHION','트립션','830','7','5','15','31','1,775','890');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TLEYOUNG','틀영','56','2','1','33','5','42','86');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TINABLOSSOM','티나블러썸','0','0','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TDN','티디앤','112','0','3','0','0','1','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TWN','티떠블유엔','599','12','14','2','3','20,150','10,164');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('T-LEVEL','티레벨','107','0','0','0','0','415','550');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('T-REIGN','티레인','26','0','0','0','0','3','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIBAEG','티백','125','0','4','1','0','15','113');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TVOBT','티브이오비티','220','0','1','0','0','22','192');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TBJ ADVANCED','티비제이 어드벤스드','396','1','1','0','0','91','106');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TISSU CLUBBAND','티슈클럽밴드','11','0','10','0','2','0','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEETHOFFICE','티스오피스','25','0','3','0','0','3','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TISSOT','티쏘','324','0','0','0','0','16','294');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('T.I FOR MEN','티아이포맨','170','1','8','9','34','21','410');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEEAZ','티아즈','185','4','3','6','4','4,027','561');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TRMARK','티알마크','1,111','0','22','0','6','26,278','4,071');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TSNINE','티에스나인','222','0','0','0','0','9','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TNGT','티엔지티','1,680','3','10','0','0','359','700');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TNP','티엔피','191','2','4','0','6','2,887','374');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TMRW','티엠알더블유','112','4','38','64','76','2,245','838');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TMO BY 13MONTH','티엠오 바이 써틴먼스','101','5','26','18','6','106','318');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOU','티오유','123','0','10','0','28','322','406');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TOTM','티오티엠','115','0','0','0','0','99','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('T.U.K','티유케이','105','0','1','16','0','430','623');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEATIME OF SPRING','티타임 오브 스프링','69','4','3','1','41','20','144');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TTMAB','티티맙','7','1','5','11','1','0','124');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TYPICA','티피카','50','0','1','0','0','32','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THUD','티허드','19','1','3','14','16','101','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TICTECTOC','틱택톡','121','0','0','0','0','29','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TILL I DIE','틸 아이 다이','179','1','10','2','2','57','382');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEAMSCULPTOR','팀 스컬프터','221','2','13','23','10','2,245','2,001');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIMBERLAND','팀버랜드','137','0','135','295','17','2,455','4,764');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIMBUK2','팀벅2','634','2','5','2','2','766','606');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TEAMS','팀스','35','0','0','0','0','44','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('TIPTOP POMADE','팁탑포마드','3','0','0','0','0','20','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('THE HERMIT PROJECT','허미트 프로젝트','52','2','1','0','2','17','146');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UGG','어그','57','0','8','0','0','10','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UGLYBEAVER','어글리비버','17','0','2','11','1','3','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UGLYSHADOW','어글리쉐도우','147','4','21','192','0','313','1,512');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNALLOYED','어널로이드','496','11','65','46','401','4,501','6,675');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UMUN','어뮨','44','0','1','11','0','0','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URBANDTYPE','어반디타입','827','18','107','242','112','6,384','3,909');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URBANLIKE','어반라이크','5','0','0','0','0','6','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URBANSTOFF','어반스터프','519','16','135','172','60','22,244','14,043');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URBAN STRIKERS','어반스트라이커즈','13','0','0','0','0','9','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URBAN PLAYERS','어반플레이어스','169','4','5','22','3','1,299','482');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('USS2','어스투','156','0','0','0','0','20','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNNOWN','언노운','213','0','5','4','0','281','197');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNDERBASE','언더베이스','100','0','0','0','0','862','296');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNDERARMOUR','언더아머','518','0','16','2','0','1,276','2,225');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNDERAIR','언더에어','728','4','36','9','2','17,755','9,389');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNDERYOUTH','언더유스','69','2','2','0','6','481','405');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNDERCONTROL','언더컨트롤','415','7','20','43','5','5,406','2,086');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNDERCONTROL STUDIO','언더컨트롤 스튜디오','158','4','28','28','2','664','668');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNLIKELOOK','언라이크룩','85','5','5','1','10','451','591');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNLIMIT','언리미트','396','2','0','0','4','19,370','7,911');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNBOUNDED AWE','언바운디드 어위','27','0','0','0','0','30','49');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNBDAY','언비데이','44','0','1','0','0','127','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNOTHER','언아더','86','1','1','0','0','16','99');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNCOMMEN','언커맨','45','0','0','0','0','1','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNCONSTRAINED','언컨스트레인드','121','2','4','0','1','16','228');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNCOS','언코즈','50','1','5','6','1','118','554');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNCLOCKWISM','언클락와이즘','97','1','0','1','0','137','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNCLOSE','언클로즈','6','1','0','2','0','1','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNTOUCHED','언터치드','253','5','29','83','16','6,289','1,546');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNTAGE','언티지','623','2','6','3','1','607','1,333');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNFOLD','언폴드','30','0','9','0','4','1,383','627');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNHATE','언헤이트','65','1','5','16','2','17','136');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URBANORIGINALS','얼반오리지널','15','0','1','0','0','2','36');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ULKIN','얼킨','1,588','5','25','23','52','189','801');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UMBRO','엄브로','685','26','175','44','34','12,260','11,668');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UPSTATE STOCK','업스테이트 스탁','34','0','2','0','0','24','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UPFRONT','업프론트','87','0','0','0','0','23','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNERI','우네리','23','1','2','3','0','112','104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIVERSO','우니베르소','65','0','1','3','0','34','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ULLALA PAJAMAS','울랄라파자마','94','1','2','0','1','48','378');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UKNOW ALICE','유노앨리스','15','0','0','0','0','57','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNI','유니','70','1','2','1','1','56','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIVERSAL OVERALL','유니버셜 오버롤','156','2','5','5','4','181','447');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIVERSAL CHEMISTRY','유니버셜 케미스트리','480','0','24','2','1','419','400');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIIS DESIGN','유니스디자인','348','18','134','204','34','15,925','5,417');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNI APPAREL','유니어패럴','303','1','1','0','0','14,487','2,710');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIERE','유니에르','18','0','0','0','0','11','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNION OBJET','유니온 오브제','257','3','15','78','93','689','752');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNION GARMENTS','유니온가먼츠','11','1','2','0','0','218','201');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIONLOW','유니온로우','347','4','3','5','2','292','245');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIPOP LEGWEAR','유니팝 레그웨어','107','0','1','2','0','19','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIPAIR','유니페어','31','0','7','0','0','5','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UNIFORM BRIDGE','유니폼브릿지','1,472','17','344','272','134','76,638','27,631');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URAGO','유라고','1,716','15','52','95','37','973','2,138');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URANGS','유랑스','62','0','1','0','0','83','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('URIMERA','유리메라','105','0','21','104','2','0','69');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UBESCO','유베스코','141','3','0','0','0','2,076','2,102');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('U&LC','유앤엘씨','360','2','10','35','7','599','471');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('U AND J PROJECT','유앤제이 프로젝트','96','0','8','13','4','19','89');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('U.S.A MERCHANDISING','유에스에이 머친다이징','308','0','0','0','0','10','136');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UST','유에스티','62','0','0','0','0','13','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UAG','유에이지','212','0','0','0','0','270','107');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('USUAL EDIT','유주얼 에딧','157','1','4','88','1','344','429');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UJEWELSCENT','유주얼센트','71','3','2','0','2','30','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('USED FUTURE','유즈드퓨처','405','7','5','4','1','250','649');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('USITE','유지떼','112','2','16','84','11','40','111');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UMM','음','302','5','34','206','20','12,089','3,151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('UIMIGA','의미가','81','0','0','0','0','208','53');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VANADIS','바나디스','56','3','8','18','4','213','145');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VASTIC','바스틱','944','9','128','305','34','43,311','7,418');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOWELER','바울러','7','0','0','0','0','5','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIINUT','바이넛','54','0','2','13','5','552','274');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIBRATE','바이브레이트','288','4','35','20','46','326','1,383');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VITAL','바이탈','122','2','6','60','1','436','156');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VITALBEAUTIE','바이탈뷰티','0','0','0','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VITALSIGN','바이탈싸인','102','2','11','16','8','77','771');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VARZAR','바잘','342','10','18','78','48','2,777','954');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VATOZ','바토즈','16','0','4','0','0','71','47');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VANVAN','반반','0','0','0','0','0','0','8');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VANS','반스','2,163','4','959','1,840','189','75,395','87,846');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VANONE','반원','232','5','15','52','21','2,220','1,516');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VANTIQUE','반티크','9','0','1','1','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VALEXTRA','발렉스트라','51','0','0','0','0','1','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VALENTINO GARABANI','발렌티노 가라바니','747','0','0','0','0','7','352');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VALENTINO RUDY','발렌티노 루디','883','0','3','1','2','1,743','669');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VALIANT','발리안트','134','0','2','2','1','477','243');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VENTE','방떼','20','1','3','0','0','2','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VANNWORKS','밴웍스','941','2','13','11','3','17,758','5,284');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERMILAN','버밀란','74','0','1','0','0','453','411');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERTX','버텍스','0','0','0','0','0','0','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERTEXNEXTLEVEL','버텍스넥스트레벨','78','1','0','0','0','11','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERSE ONE','벌스원','14','2','0','0','5','22','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Vulcanizer','벌커나이저','20','0','2','0','0','0','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VEGACE','베가스','9','0','1','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VENICATE','베니카테','37','0','0','0','4','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VEDA','베다','13','1','2','0','0','0','107');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERDAMT','베담트','46','2','6','10','15','214','356');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERESTO','베레스토','17','0','1','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERONICA FOR LONDON','베로니카포런던','52','2','7','1','4','71','304');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERSACE','베르사체','42','0','22','3','0','4','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERT ET NOIR','베르에누아','34','0','4','3','0','2','24');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERYNINEFLUX','베리나인플럭스','241','6','6','4','60','646','376');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERYVAIN','베리베인','155','2','17','6','6','17,117','2,416');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VARISONC','베리송크','222','1','2','0','3','31','50');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VERRIS','베리스','158','0','0','0','8','48','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VEAK','베아크','52','0','0','0','0','68','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VEIMODE','베이모드','20','0','0','0','0','53','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VEI-8','베이에잇','167','3','10','14','7','48','619');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VETEZE','베테제','292','2','8','7','15','6,484','3,533');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VENDETTA','벤데타','35','1','3','13','0','33','168');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VANQUEST','벤퀘스트','49','0','0','0','0','2','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VENQUE','벤크','107','1','2','2','0','120','116');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VENTEZ','벤테즈','54','0','0','2','1','146','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VENTOLATION','벤톨레이션','30','0','1','0','1','19','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VEM.VER','벰버','413','1','8','3','2','45','816');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOGATHA','보가타','58','0','0','0','4','5','29');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOGMASK','보그마스크','20','0','2','0','1','88','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOYONN','보연','45','0','1','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOWOOD','보우드','107','0','1','0','0','21','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOILE BLANCHE','보일블량쉐','0','0','0','0','0','0','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOLD','볼드','10','1','1','1','0','5','126');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOLTERRA','볼테라','28','0','4','0','0','339','172');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOUMUIEL','부뮈엘','42','0','3','16','0','1','35');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VUIEL','뷔엘','33','3','2','0','0','295','696');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOIEBIT','브아빗','342','15','102','467','133','5,738','2,484');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VVV','브이브이브이','227','2','8','21','37','206','1,726');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('V2','브이투','175','4','15','28','6','1,144','1,270');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VLADO','블라도','15','0','0','0','0','20','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VLADVLADES','블라드블라디스','395','10','11','29','38','933','1,764');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VLNDFLES','블라인드파일즈','33','0','1','0','0','10','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VLACK','블랙','39','0','2','700','1','2','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VEGAN TIGER','비건타이거','100','0','2','0','2','4','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VINAJ','비나제이','12','1','4','0','2','2','123');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VDR','비디알','174','11','21','287','43','1,139','2,720');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIVASTUDIO','비바스튜디오','1,300','16','428','344','147','85,795','55,723');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIVACLASSY','비바클래시','95','5','12','67','25','226','586');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIVANT','비방트','98','1','1','0','6','1','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ViVe','비베','96','0','0','0','0','9','40');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIVIENNE WESTWOOD','비비안 웨스트우드','105','0','8','1','0','6','281');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VISTIC','비스틱','17','0','0','0','0','37','22');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIAMONOH','비아모노','200','1','0','4','0','84','100');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIABON DE VIA','비아봉드비아','178','3','5','12','1','354','586');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIOLLINA','비올리나','45','0','0','0','0','4','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VISITINNEWYORK','비지트인뉴욕','63','0','0','0','0','22','76');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VGTB','비지티비','35','1','3','0','1','26','240');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VICO CRISTALLINI','비코크리스탈리니','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VITALY','비탈리','98','0','0','0','0','23','73');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VITTER','비터','46','0','0','0','0','261','80');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VIKTOR&ROLF','빅터앤롤프','0','0','0','0','0','0','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VICTORIA HYDE','빅토리아하이드','4','0','0','0','0','2','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VINCIS'','빈치스','266','3','5','0','0','5','237');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VINKAN','빈칸','9','1','2','0','3','44','281');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('VOLKSVAGEN WATCH','폭스바겐 와치','180','0','6','13','4','1,386','384');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('W-STAR','더블스타','36','0','1','0','0','17','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WDRESSROOM','더블유드레스룸','65','0','3','0','1','1,215','478');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WV PROJECT','더블유브이프로젝트','507','7','76','4','3','81,822','51,313');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WRANGLER','랭글러','12','0','0','1','0','3','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WRONGDIRECTION','롱디렉션','29','1','5','25','16','7','178');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WUNDER GEIST','분더가이스트','105','0','2','0','0','3','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WARDROBE','와드로브','366','4','11','39','13','151','460');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WABANAKKI','와바나키','54','0','0','0','0','26','118');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHY-RI ROVER','와이리로버','515','4','8','4','2','71','543');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHY STYLE','와이스타일','59','0','0','0','0','2','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WAIKEI','와이케이','210','10','50','61','313','5,652','7,314');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WILD BRICKS','와일드 브릭스','419','9','44','105','1','6,968','3,948');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WACKOMARIA','와코마리아','630','0','9','1','1','90','529');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WACOQ','와코크','70','0','0','0','0','1,999','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WANTON','완톤','188','5','1','0','2','274','258');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WALLOW&CO','왈로우앤코','28','1','1','0','0','3','154');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WATHEN','왓슨','9','0','0','0','0','1','1');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHATEVERWEWANT','왓에버위원트','194','2','3','1','0','93','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WATCHOUTBABY','왓치아웃베이비','98','5','21','101','13','122','707');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHATHAPPEN','왓해픈','109','3','6','12','4','94','163');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WANGGWAN','왕관','114','4','15','49','7','318','175');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOOZO','우조','114','4','8','38','16','298','543');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WUZU STUDIO','우주스튜디오','129','7','22','516','21','174','745');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOOJIN PLASTIC','우진플라스틱','25','0','0','0','0','14','15');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOTANCRAFT','우탄크래프트','24','0','1','0','0','0','17');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOONMU','운무','67','4','3','14','16','34','155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOOLRICH','울리치','30','0','4','0','0','93','227');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOLVERINE','울버린','11','0','21','101','6','509','495');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOONG','웅','92','0','0','0','0','15','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WANNAFIT','워너핏','23','0','0','2','0','8','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WARRIOR CLOTHING','워리어클로징','5','0','0','0','0','25','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WORK OR DANCE','워크 오얼 댄스','10','0','0','0','0','22','25');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WALK&REST','워크앤레스트','37','0','2','0','0','7','94');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WORKS PEDITION','웍스페디션','60','0','1','0','0','1,490','391');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WONDER VISITOR','원더 비지터','72','3','1','6','0','71','229');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WONDERBRA','원더브라','393','0','6','0','0','496','267');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WOLGAN','월간','66','0','1','0','81','27','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WORLD ANTHEM WAVE','월드 앤썸 웨이브','34','2','8','25','6','188','191');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WESTWARDCALIFORNIA','웨스트 워드 캘리포니아','0','0','0','0','0','0','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WEST COAST CHOPPERS','웨스트코스트 차퍼스','0','0','0','0','0','0','44');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WEARPANDA','웨어판다','43','0','0','0','0','9','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WADE','웨이드','62','2','4','33','0','853','574');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WAVEGUN','웨이브건','79','1','10','62','28','38','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WAVE UNION','웨이브유니온','77','3','10','20','10','142','264');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WAZE','웨이즈','92','4','16','57','32','284','857');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WAKEMEUP','웨이크미업','17','0','0','1','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHENIDIFF','웬아이디프','16','0','0','0','0','1','34');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHENIWASYOUNG','웬아이워즈영','41','4','4','10','3','89','42');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WELDER','웰더','15','0','1','1','0','0','492');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WELLDONE','웰던','5','5','1','0','0','1,361','87');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WELLMADECOM','웰메이드컴','27','1','2','5','2','11','218');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WELCOME RECORDS','웰컴 레코드','8','0','1','0','0','0','0');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WIGGLE WIGGLE','위글위글','92','0','2','0','3','1,341','904');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WIGGYS','위기스','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WETHEROAD','위더로드','31','2','27','146','23','5,226','1,559');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WITH TORY','위드토리','50','0','1','0','0','26','16');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WISH BLACK','위시블랙','38','0','0','0','0','1','7');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WISSY','위씨','215','0','6','0','0','4,541','1,032');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WEIRD WAVE','위어드 웨이브','73','1','1','0','0','20','177');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WESC','위에스씨','1,476','0','1','0','0','312','1,054');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WEALLKNOWIT','위올노잇','50','0','1','0','0','210','176');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WKNDRS','위캔더스','545','17','70','98','148','1,656','2,468');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WEEKADE','위크에이드','168','0','0','0','0','67','55');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WITTMAN','위트맨','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WITINART','위티나트','125','0','0','11','0','189','84');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WEFAM','위팸','59','0','0','0','0','40','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WEKSNOOP','윅스눕','90','1','0','4','8','1,260','1,427');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WILLIE and DUFFY','윌리앤더피','80','0','1','0','0','696','888');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('willicot','윌리콧','155','0','2','0','0','1,540','746');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WILS FABRIK','윌스 파브릭','0','0','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHITESANDS','화이트샌즈','308','3','6','0','0','51','91');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHITE PROJECT','화이트프로젝트','29','1','3','0','2','4','140');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHODINGS','후딩스','58','1','2','0','0','7','293');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHOLOVESART','후러브스아트','85','3','16','2','1','3,980','669');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('WHOAU','후아유','364','3','21','22','10','6,489','4,342');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XDDESIGN','엑스디디자인','13','0','1','0','2','26','64');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('X-LARGE','엑스라지','5','0','8','1','0','1','327');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Xmm','엑스밀리미터','42','0','1','0','0','84','79');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('X-SACKY','엑스사키','108','0','1','3','0','655','609');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XCXMAIN','엑스씨엑스메인','242','8','7','42','33','1,792','1,717');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XS','엑스에스','25','0','0','0','0','1','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XYZ','엑스와이지','97','3','14','83','32','70','290');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XTONZ','엑스톤즈','273','12','21','70','34','3,438','1,555');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XTM','엑스티엠','7','0','1','0','0','7','134');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XPERIMNT','엑스페리먼트','70','1','7','2','7','9','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XPIER','엑스피어','186','1','7','0','2','6,185','633');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XERO','제로','786','11','116','9','13','51,055','16,344');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('XESS','제스','7','0','0','0','0','1','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YASE','야세','7','1','26','88','8','1,977','779');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YEOMIDA','여미다','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YEOMIM','여밈','123','0','6','11','1','280','341');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YUPPIE','여피','33','4','8','32','6','29','179');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YUPPE','엽페','463','9','55','189','41','873','2,735');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YRN','영리치네이션','33','0','0','0','0','5','38');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOUNGSTERNA','영스터나','15','0','0','0','0','1','14');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOUNGANDONE','영앤드원','0','0','0','0','0','0','1');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YESEYESEE','예스아이씨','233','3','3','17','12','566','1,127');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YESEASY','예스이지','40','1','0','4','1','2','39');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YELLOWSTONE','옐로우스톤','463','2','7','83','3','3,141','910');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Y NOT C','와이낫씨','66','3','3','20','3','49','205');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YWZ','와이더블유젯','129','0','1','0','0','4','23');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YMCL KY','와이엠씨엘케이와이','282','0','16','39','2','2,276','3,528');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YYCC','와이와이씨씨','22','1','0','0','0','0','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YKR','와이케이알','77','1','3','28','7','361','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YEAR2KILO','와이투케이','24','1','6','13','0','78','216');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YPY DESIGN STUDIO','와이피와이 디자인 스튜디오','49','2','2','13','8','23','115');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOMON','요몬','79','5','4','4','0','184','361');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOWE','요위','48','2','8','57','6','97','208');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOHJI YAMAMOTO','요지야마모토','83','0','4','0','0','11','235');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOKOMALL','요코몰','0','0','0','0','0','0','3');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YORKMINSTER','요크민스터','85','1','0','1','0','80','237');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOBS','욥스','109','0','0','0','0','10','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YUEMAI','위에마이','170','0','0','0','0','36','49');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOU NEED GARMENTS','유니드가먼츠','61','0','2','0','0','323','545');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOUNESS','유니스','43','1','1','1','0','4','21');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YRAGRAY','유라그레이','145','0','0','0','0','289','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOUTHFORYOUTH','유스포유스','102','5','3','49','26','46','157');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOUTHBATH','유쓰배쓰','78','11','36','121','60','919','1,620');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOURMONTH YOURDAY','유어먼스 유어데이','18','0','2','0','3','2','121');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YUIMARU','유이마루','144','0','0','0','0','77','99');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YOUSER','유저','7','0','6','1','1','4','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YIGNIL','이그닐','55','3','6','7','19','13','101');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('YIYOON','이윤','0','0','0','0','0','0','2');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZIKLAG','시글락','36','0','0','0','0','164','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZAMU','자무','59','1','0','0','0','310','155');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZAODAM','자오담','8','0','2','0','1','3','96');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZATO','자토','65','2','1','17','1','177','272');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZAXY','작시','26','0','0','0','0','1','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZANCA','잔카','104','0','0','0','1','1','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('Zadig & Voltaire','쟈딕앤볼테르','0','0','0','0','0','0','10');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZANIMAL','제니멀','260','0','4','0','1','59','65');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZERO DE CONDUITE','제로드컨듀잇','54','0','0','0','0','35','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZEROSTREET','제로스트리트','111','5','10','77','18','88','794');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZEROJ','제로제이','20','0','0','0','0','80','81');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZEROPLANET','제로플래닛','206','3','2','0','3','6','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZCOLICO','젯콜리코','0','0','0','0','0','0','30');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZOGGS','조그스','100','0','1','0','0','4','51');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZOD','조드','51','0','0','8','0','47','120');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZOENA','조에나','5','0','13','7','3','62','145');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZUDRITT','주드리뜨','0','0','0','0','0','0','11');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZOOICY','주씨','0','0','0','0','0','169','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZULUPACK','줄루팩','2','0','0','0','0','2','112');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZLEY HARDI','즐리하디','46','0','0','0','6','64','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZIGDIG','지그디그','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZIZIS','지지스','0','0','0','0','0','0','5');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZPLISH','지플리시','832','11','53','60','32','6,192','2,656');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZIHEE','지희','43','0','1','0','1','1','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('ZIMZUM','짐줌','10','0','0','0','0','569','93');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('407하우스','','18','1','2','0','0','271','340');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('090FACTORY','090팩토리','224','2','1','0','1','28','134');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('108SEOUL','108서울','48','0','0','0','0','116','171');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('13BLUES','13블루스','38','0','1','0','0','200','45');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('14 STUDIO','14 스튜디오','130','3','0','1','0','102','166');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('18HOUR','18아워','8','1','0','0','0','23','31');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('1993STUDIO','1993스튜디오','50','0','2','6','4','147','1,369');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('2001 TWIN SCALP','2001 트윈스컬프','0','0','0','0','0','0','151');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('235LABORATORY','235연구소','164','0','0','0','0','53','70');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('247 SEOUL','247 서울','140','3','24','22','8','13,169','1,383');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('2MONKEY','2몽키','39','0','0','0','0','4','18');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('320SHOWROOM','320쇼룸','136','10','22','98','17','230','401');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('33MUSEMENT','33뮤즈먼트','27','0','0','0','0','1','13');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('38COMEONCOMMON','38컴온커먼','202','11','51','93','16','632','1,559');

INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('40oz NYC','40온즈 엔와이씨','23','0','0','0','0','18','266');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('47 BRAND','47브랜드','702','1','8','0','0','9,562','2,215');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('5.11 TACTICAL','5.11택티컬','356','0','1','0','0','34','314');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('5252BYOIOI','5252 바이 오아이오아이','773','12','287','167','181','33,550','66,882');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('69SLAM','69슬램','382','0','0','0','0','39','20');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('7.62DESIGN','7.62 디자인','56','0','0','0','0','3','164');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('726GEARS','726기어','84','0','0','0','0','11','59');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('803STUDIO','803스튜디오','35','0','5','0','0','20','75');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('86ROAD','86로드','426','4','88','224','170','33,982','9,467');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('888STUDIO','888스튜디오','16','1','1','0','0','6','83');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('100%','백퍼센트','41','0','0','0','0','1','12');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('2ND LIFE','세컨라이프','36','0','4','0','1','1','133');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('6MASK','식스마스크','40','0','0','0','0','3','9');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('60BRIX','식스티브릭','5','0','1','0','1','16','92');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('13MONTH','써틴먼스','198','6','75','80','22','1,867','4,917');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('13PERCENT','써틴퍼센트','1','0','0','0','0','7','132');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('8DIVISION','에이트디비젼','19','1','2','1','0','10','203');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('8SECONDS','에잇세컨즈','10,141','19','128','184','18','34,195','9,231');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('1LOVE','원러브','22','0','0','0','0','1','108');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('1'SOFT','원소프트','29','1','4','1','2','30','213');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('23.65','이십삼점육오','94','5','20','3','10','5,618','2,358');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('25PERCENTAGE','이십오퍼센테이지','74','4','2','0','1','427','676');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('210X297','이일공 이구칠','12','1','3','0','0','0','48');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('2PJT','이피제이티','82','4','1','12','0','54','109');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('199X KIDS','일구구엑스키즈','75','1','3','2','3','140','252');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('134MM','일삼사엠엠','227','0','1','0','0','42','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('12','일이','0','0','0','0','0','0','27');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('1159STUDIO','일일오구스튜디오','415','7','37','2','8','73','961');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('1000V','천볼트','31','0','0','0','7','1','46');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('79BY79','칠구바이칠구','183','0','2','0','0','112','181');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('2MOD','투모드','0','0','0','0','0','0','4');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('2CUBE','투큐브','131','1','15','3','3','743','294');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('2XU','투타임즈유','804','4','12','10','11','8','104');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('87MM','팔칠엠엠','889','14','114','337','26','61,467','52,734');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('4DIMENSION','포디멘션','42','0','3','0','0','60','259');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('4DEAWORKS','포디어웍스','52','0','3','0','0','11','63');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('4XR','포엑스알','22','2','6','0','3','230','373');
INSERT INTO BRAND_INFO(BRD_NAME_ENG, BRD_NAME_KOR, PRODUCT, LOOKBOOK, ARTICLE, STYLE, CONTENTS, REVIEW, LIKES) VALUES('4T2ND','포티세컨드','16','0','0','2','0','12','6');